// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Lino Laske

import Foundation

/// Original practice material for the topics "Betriebsrat & Tarifrecht" and
/// "Sozialversicherung & Steuern". See `ExamCatalog` for the overall structure.
extension ExamCatalog {

    // MARK: - Betriebsrat & Tarifrecht

    static let mitbestimmung: [ExamCard] = [
        // Choice
        .choice(id: "mit-c01", topic: .mitbestimmung,
                prompt: "Ab wie vielen wahlberechtigten Arbeitnehmern kann in einem Betrieb ein Betriebsrat gewählt werden?",
                options: ["Ab 5 wahlberechtigten Arbeitnehmern, von denen 3 wählbar sein müssen",
                          "Ab 3 wahlberechtigten Arbeitnehmern",
                          "Ab 10 wahlberechtigten Arbeitnehmern",
                          "Ab 20 wahlberechtigten Arbeitnehmern",
                          "Erst ab 50 Arbeitnehmern"],
                explanation: "Nach § 1 BetrVG braucht ein Betrieb mindestens 5 ständige wahlberechtigte Arbeitnehmer, von denen 3 wählbar sein müssen."),
        .choice(id: "mit-c02", topic: .mitbestimmung,
                prompt: "Wer ist bei der Betriebsratswahl wahlberechtigt?",
                options: ["Alle Arbeitnehmer des Betriebs ab 16 Jahren",
                          "Nur Arbeitnehmer ab 18 Jahren",
                          "Nur unbefristet Beschäftigte",
                          "Nur Mitglieder einer Gewerkschaft",
                          "Nur Arbeitnehmer mit mindestens 1 Jahr Betriebszugehörigkeit"],
                explanation: "Nach § 7 BetrVG sind Arbeitnehmer seit 2021 bereits ab 16 Jahren wahlberechtigt."),
        .choice(id: "mit-c03", topic: .mitbestimmung,
                prompt: "Wer ist bei der Betriebsratswahl wählbar?",
                options: ["Wahlberechtigte ab 18 Jahren mit mindestens 6 Monaten Betriebszugehörigkeit",
                          "Alle Arbeitnehmer ab 16 Jahren",
                          "Nur Arbeitnehmer mit abgeschlossener Berufsausbildung",
                          "Nur Gewerkschaftsmitglieder",
                          "Auch leitende Angestellte"],
                explanation: "Wählbar sind volljährige Wahlberechtigte mit 6 Monaten Betriebszugehörigkeit. Leitende Angestellte zählen nicht als Arbeitnehmer im Sinne des BetrVG."),
        .choice(id: "mit-c04", topic: .mitbestimmung,
                prompt: "Wie lange dauert die regelmäßige Amtszeit des Betriebsrats?",
                options: ["4 Jahre", "2 Jahre", "3 Jahre", "5 Jahre", "6 Jahre"],
                explanation: "Nach § 21 BetrVG finden die regelmäßigen Betriebsratswahlen alle 4 Jahre statt (z. B. 2022, 2026, 2030)."),
        .choice(id: "mit-c05", topic: .mitbestimmung,
                prompt: "In einem Betrieb der fiktiven Firma „Kernwerk Solutions GmbH“ gibt es 120 wahlberechtigte Arbeitnehmer. Wie viele Mitglieder hat der Betriebsrat?",
                options: ["7", "5", "9", "11", "13"],
                explanation: "Nach § 9 BetrVG hat der Betriebsrat bei 101 bis 200 wahlberechtigten Arbeitnehmern 7 Mitglieder."),
        .choice(id: "mit-c06", topic: .mitbestimmung,
                prompt: "Welche Aufgabe hat der Wirtschaftsausschuss?",
                options: ["Er wird vom Arbeitgeber über wirtschaftliche Angelegenheiten des Unternehmens unterrichtet",
                          "Er verhandelt Tarifverträge mit den Gewerkschaften",
                          "Er entscheidet über Kündigungen",
                          "Er legt die Höhe der Löhne fest",
                          "Er vertritt die Auszubildenden"],
                explanation: "In Unternehmen mit mehr als 100 Arbeitnehmern muss der Arbeitgeber den Wirtschaftsausschuss unterrichten (§ 106 BetrVG) – ein reines Informationsrecht."),
        .choice(id: "mit-c07", topic: .mitbestimmung,
                prompt: "Was gilt für eine Betriebsvereinbarung?",
                options: ["Sie wird zwischen Arbeitgeber und Betriebsrat geschlossen und gilt unmittelbar für alle Arbeitnehmer des Betriebs",
                          "Sie wird zwischen Gewerkschaft und Arbeitgeberverband geschlossen",
                          "Sie gilt nur für Betriebsratsmitglieder",
                          "Sie kann die Lohnhöhe abweichend vom Tarifvertrag frei regeln",
                          "Sie muss vom Arbeitsgericht genehmigt werden"],
                explanation: "Nach § 77 Abs. 3 BetrVG gilt ein Tarifvorrang: Üblicherweise tariflich geregelte Löhne darf die Betriebsvereinbarung nicht ohne Öffnungsklausel regeln."),
        .choice(id: "mit-c08", topic: .mitbestimmung,
                prompt: "Worüber informiert der Arbeitgeber die Belegschaft auf der Betriebsversammlung?",
                options: ["Über Angelegenheiten von allgemeiner Bedeutung für den Betrieb, mindestens einmal im Quartal",
                          "Nur einmal jährlich über den Jahresabschluss",
                          "Nur bei Kündigungen",
                          "Nur auf Verlangen der Gewerkschaft",
                          "Nie – das ist allein Aufgabe des Wirtschaftsausschusses"],
                explanation: "Betriebsversammlungen finden regelmäßig vierteljährlich statt (§ 43 BetrVG)."),
        .choice(id: "mit-c09", topic: .mitbestimmung,
                prompt: "Wann muss bei einer Betriebsänderung ein Sozialplan aufgestellt werden?",
                options: ["Wenn ein Unternehmen mit mehr als 20 Arbeitnehmern eine Betriebsänderung mit wirtschaftlichen Nachteilen für die Belegschaft plant",
                          "Immer, wenn ein einzelner Arbeitnehmer gekündigt wird",
                          "Nur wenn die Gewerkschaft es ausdrücklich verlangt",
                          "Nur im Fall einer Insolvenz",
                          "Nur wenn mehr als 100 Arbeitnehmer betroffen sind"],
                explanation: "Nach §§ 111, 112 BetrVG verhandeln Arbeitgeber und Betriebsrat bei Betriebsänderungen in Unternehmen mit mehr als 20 Arbeitnehmern einen Interessenausgleich und einen erzwingbaren Sozialplan."),
        .choice(id: "mit-c10", topic: .mitbestimmung,
                prompt: "Personalleiter Berger von der fiktiven „Kernwerk Solutions GmbH“ möchte eine neue Software zur Zeiterfassung der Beschäftigten einführen. Welches Beteiligungsrecht hat der Betriebsrat dabei?",
                options: ["Ein zwingendes Mitbestimmungsrecht, da es sich um eine technische Überwachungseinrichtung handelt",
                          "Nur ein Recht auf Information",
                          "Kein Beteiligungsrecht, da es eine reine Investitionsentscheidung ist",
                          "Nur ein unverbindliches Vorschlagsrecht",
                          "Ein Vetorecht, das nur der Gewerkschaft zusteht"],
                explanation: "Nach § 87 Abs. 1 Nr. 6 BetrVG ist die Einführung technischer Einrichtungen zur Überwachung von Verhalten oder Leistung zwingend mitbestimmungspflichtig."),
        .choice(id: "mit-c11", topic: .mitbestimmung,
                prompt: "Bei welcher Angelegenheit hat der Betriebsrat KEIN Mitbestimmungsrecht?",
                options: ["Bei der unternehmerischen Entscheidung, in welche Maschinen investiert wird",
                          "Bei Beginn und Ende der täglichen Arbeitszeit",
                          "Bei der Aufstellung von Urlaubsgrundsätzen",
                          "Bei der Einführung von Kurzarbeit",
                          "Bei den Grundsätzen der Entlohnung"],
                explanation: "Reine unternehmerische Entscheidungen wie Investitionen sind mitbestimmungsfrei; die sozialen Angelegenheiten aus § 87 BetrVG sind dagegen mitbestimmungspflichtig."),
        .choice(id: "mit-c12", topic: .mitbestimmung,
                prompt: "Was gilt, wenn der Arbeitgeber einem Arbeitnehmer kündigen möchte?",
                options: ["Er muss den Betriebsrat vorher anhören, sonst ist die Kündigung unwirksam",
                          "Der Betriebsrat muss der Kündigung zustimmen",
                          "Der Betriebsrat hat kein Recht, darüber informiert zu werden",
                          "Der Betriebsrat kann die Kündigung selbst aussprechen",
                          "Der Betriebsrat entscheidet abschließend über die Kündigung"],
                explanation: "Nach § 102 BetrVG hat der Betriebsrat ein Anhörungs- und Widerspruchsrecht, aber kein Mitbestimmungsrecht bei Kündigungen."),
        .choice(id: "mit-c13", topic: .mitbestimmung,
                prompt: "Was ist die JAV?",
                options: ["Die Jugend- und Auszubildendenvertretung, die die Interessen jugendlicher und auszubildender Beschäftigter wahrnimmt",
                          "Ein weiterer Name für den Betriebsrat",
                          "Eine eigene Gewerkschaft für junge Arbeitnehmer",
                          "Ein Ausschuss der IHK",
                          "Eine Vertretung nur für Werkstudenten"],
                explanation: "Die JAV vertritt Beschäftigte unter 18 Jahren sowie Auszubildende unter 25 Jahren und arbeitet über den Betriebsrat."),
        .choice(id: "mit-c14", topic: .mitbestimmung,
                prompt: "Ab welcher Voraussetzung kann in einem Betrieb eine JAV gebildet werden?",
                options: ["Wenn mindestens 5 Arbeitnehmer unter 18 Jahren oder Auszubildende unter 25 Jahren beschäftigt sind und ein Betriebsrat besteht",
                          "Ab 20 Auszubildenden, unabhängig von einem Betriebsrat",
                          "In jedem Ausbildungsbetrieb, unabhängig von der Größe",
                          "Nur wenn kein Betriebsrat besteht",
                          "Ab 5 Auszubildenden über 25 Jahren"],
                explanation: "Voraussetzung für die JAV ist ein bestehender Betriebsrat sowie mindestens 5 wahlberechtigte Jugendliche oder Auszubildende."),
        .choice(id: "mit-c15", topic: .mitbestimmung,
                prompt: "Was bedeutet Tarifautonomie?",
                options: ["Die Tarifparteien regeln Arbeitsbedingungen eigenständig ohne staatliche Einmischung",
                          "Der Staat legt die Löhne einer Branche gesetzlich fest",
                          "Jeder Arbeitgeber verhandelt einzeln mit jedem Arbeitnehmer über den Tariflohn",
                          "Der Betriebsrat verhandelt die Tarifverträge",
                          "Gewerkschaften dürfen ohne Arbeitgeberverband verbindliche Löhne festsetzen"],
                explanation: "Tarifautonomie folgt aus der Koalitionsfreiheit (Art. 9 Abs. 3 GG); Tarifparteien sind Gewerkschaften und Arbeitgeberverbände bzw. einzelne Arbeitgeber."),
        .choice(id: "mit-c16", topic: .mitbestimmung,
                prompt: "Wer sind die Tarifparteien (Sozialpartner)?",
                options: ["Gewerkschaften und Arbeitgeberverbände bzw. einzelne Arbeitgeber",
                          "Betriebsrat und Arbeitgeber",
                          "Bundesregierung und Gewerkschaften",
                          "IHK und Handwerkskammer",
                          "Betriebsrat und Gewerkschaft"],
                explanation: "Tarifverträge schließen Gewerkschaften mit Arbeitgeberverbänden oder – als Haustarifvertrag – mit einzelnen Arbeitgebern."),
        .choice(id: "mit-c17", topic: .mitbestimmung,
                prompt: "Was regelt ein Manteltarifvertrag typischerweise?",
                options: ["Allgemeine Arbeitsbedingungen wie Arbeitszeit, Urlaub, Kündigungsfristen und Zuschläge",
                          "Ausschließlich die Höhe der Löhne",
                          "Nur die Höhe der Ausbildungsvergütung",
                          "Nur die Entgeltgruppen",
                          "Die Regeln der Betriebsversammlung"],
                explanation: "Manteltarifverträge haben meist eine lange Laufzeit; die Lohnhöhe regelt der Entgelttarifvertrag."),
        .choice(id: "mit-c18", topic: .mitbestimmung,
                prompt: "Was unterscheidet einen Entgelttarifvertrag von einem Manteltarifvertrag?",
                options: ["Er regelt vor allem die Höhe der Löhne und Gehälter und hat meist eine kürzere Laufzeit",
                          "Er regelt ausschließlich die Arbeitszeit",
                          "Er hat immer eine längere Laufzeit als der Manteltarifvertrag",
                          "Er gilt nur für Auszubildende",
                          "Er wird zwischen Betriebsrat und Arbeitgeber geschlossen"],
                explanation: "Entgelttarifverträge laufen wegen der Lohnentwicklung meist nur etwa 1 bis 2 Jahre."),
        .choice(id: "mit-c19", topic: .mitbestimmung,
                prompt: "Was bedeutet Tarifbindung?",
                options: ["Der Tarifvertrag gilt für Mitglieder der tarifschließenden Gewerkschaft und des tarifschließenden Arbeitgeberverbands",
                          "Der Tarifvertrag gilt automatisch für alle Betriebe der Branche",
                          "Nur der Betriebsrat ist an den Tarifvertrag gebunden",
                          "Tarifbindung entsteht allein durch den Arbeitsvertrag",
                          "Tarifbindung gilt nur für neu eingestellte Arbeitnehmer"],
                explanation: "Tarifbindung entsteht durch beiderseitige Mitgliedschaft in Gewerkschaft und Arbeitgeberverband oder durch einen Firmentarifvertrag."),
        .choice(id: "mit-c20", topic: .mitbestimmung,
                prompt: "Wodurch kann ein Tarifvertrag auch für nicht organisierte Arbeitgeber und Arbeitnehmer einer Branche gelten?",
                options: ["Durch Allgemeinverbindlicherklärung des Bundesministeriums für Arbeit und Soziales",
                          "Durch Beschluss des Betriebsrats",
                          "Automatisch nach 6 Monaten Laufzeit",
                          "Durch Zustimmung der IHK",
                          "Durch Entscheidung des Arbeitsgerichts"],
                explanation: "Die Allgemeinverbindlicherklärung erfolgt durch das Bundesministerium für Arbeit und Soziales mit Zustimmung des Tarifausschusses."),
        .choice(id: "mit-c21", topic: .mitbestimmung,
                prompt: "Was bedeutet die Friedenspflicht während der Laufzeit eines Tarifvertrags?",
                options: ["Arbeitskampfmaßnahmen zu den tariflich geregelten Inhalten sind grundsätzlich ausgeschlossen",
                          "Es darf während der gesamten Laufzeit überhaupt nicht mehr verhandelt werden",
                          "Streiks sind für Nichtgewerkschaftsmitglieder trotzdem erlaubt",
                          "Der Arbeitgeber darf während der Laufzeit keine neuen Arbeitnehmer einstellen",
                          "Die Friedenspflicht gilt nur für den Arbeitgeber"],
                explanation: "Die relative Friedenspflicht bezieht sich auf die im Tarifvertrag geregelten Inhalte und endet mit Ablauf bzw. Kündigung des Tarifvertrags."),
        .choice(id: "mit-c22", topic: .mitbestimmung,
                prompt: "Nach dem Scheitern der Tarifverhandlungen stimmen die Gewerkschaftsmitglieder eines fiktiven Betriebs über einen Streik ab. Wie nennt man diese Abstimmung?",
                options: ["Urabstimmung", "Betriebsversammlung", "Sozialwahl", "Einigungsstelle", "Schlichtungsverfahren"],
                explanation: "Vor einem Streik ist in der Regel eine Urabstimmung mit mindestens 75 % Zustimmung der Gewerkschaftsmitglieder erforderlich."),
        .choice(id: "mit-c23", topic: .mitbestimmung,
                prompt: "Welches Kampfmittel steht der Arbeitgeberseite im Arbeitskampf zur Verfügung?",
                options: ["Die Aussperrung", "Der Warnstreik", "Die Urabstimmung", "Der Sympathiestreik", "Das Streikgeld"],
                explanation: "Die Aussperrung ist das Gegenstück des Arbeitgebers zum Streik der Arbeitnehmerseite."),
        .choice(id: "mit-c24", topic: .mitbestimmung,
                prompt: "Welches Gericht ist bei einem Streit aus dem Arbeitsverhältnis zuständig?",
                options: ["Das Arbeitsgericht", "Das Sozialgericht", "Das Amtsgericht", "Das Verwaltungsgericht", "Das Finanzgericht"],
                explanation: "Das Arbeitsgericht entscheidet in erster Instanz ohne Anwaltszwang nach einer Güteverhandlung."),

        // Statements
        .statement(id: "mit-s01", topic: .mitbestimmung,
                   text: "Der Betriebsrat wird von allen Arbeitnehmern des Betriebs gewählt, unabhängig vom Alter.",
                   isTrue: false,
                   explanation: "Wahlberechtigt sind Arbeitnehmer erst ab 16 Jahren (§ 7 BetrVG)."),
        .statement(id: "mit-s02", topic: .mitbestimmung,
                   text: "Leitende Angestellte zählen nicht als Arbeitnehmer im Sinne des Betriebsverfassungsgesetzes.",
                   isTrue: true,
                   explanation: "Leitende Angestellte sind vom Anwendungsbereich des BetrVG ausgenommen und daher weder wahlberechtigt noch wählbar."),
        .statement(id: "mit-s03", topic: .mitbestimmung,
                   text: "Die Amtszeit des Betriebsrats beträgt regelmäßig 4 Jahre.",
                   isTrue: true,
                   explanation: "§ 21 BetrVG sieht regelmäßige Wahlen alle 4 Jahre vor."),
        .statement(id: "mit-s04", topic: .mitbestimmung,
                   text: "Betriebsratsmitglieder üben ihr Amt grundsätzlich hauptamtlich gegen ein zusätzliches Gehalt aus.",
                   isTrue: false,
                   explanation: "Das Betriebsratsamt ist ein Ehrenamt; erst ab 200 Arbeitnehmern gibt es eine Freistellung von der Arbeit."),
        .statement(id: "mit-s05", topic: .mitbestimmung,
                   text: "Ab 200 Arbeitnehmern kann mindestens ein Betriebsratsmitglied von der Arbeit freigestellt werden.",
                   isTrue: true,
                   explanation: "Die Freistellung richtet sich nach der Zahl der Arbeitnehmer im Betrieb."),
        .statement(id: "mit-s06", topic: .mitbestimmung,
                   text: "Eine Betriebsvereinbarung darf die Lohnhöhe frei regeln, auch wenn dafür bereits ein Tarifvertrag gilt.",
                   isTrue: false,
                   explanation: "Der Tarifvorrang (§ 77 Abs. 3 BetrVG) schließt das aus, sofern keine tarifliche Öffnungsklausel besteht."),
        .statement(id: "mit-s07", topic: .mitbestimmung,
                   text: "Bei sozialen Angelegenheiten nach § 87 BetrVG hat der Betriebsrat ein zwingendes Mitbestimmungsrecht.",
                   isTrue: true,
                   explanation: "Kommt keine Einigung zustande, entscheidet die Einigungsstelle."),
        .statement(id: "mit-s08", topic: .mitbestimmung,
                   text: "Der Wirtschaftsausschuss entscheidet verbindlich über unternehmerische Investitionen.",
                   isTrue: false,
                   explanation: "Er hat nur ein Informations- und Beratungsrecht, keine Entscheidungsbefugnis."),
        .statement(id: "mit-s09", topic: .mitbestimmung,
                   text: "Die JAV kann unabhängig vom Betriebsrat eigene Beschlüsse gegenüber dem Arbeitgeber durchsetzen.",
                   isTrue: false,
                   explanation: "Die JAV arbeitet über den Betriebsrat, der ihre Anliegen gegenüber dem Arbeitgeber vertritt."),
        .statement(id: "mit-s10", topic: .mitbestimmung,
                   text: "Nach dem Günstigkeitsprinzip gilt bei widersprüchlichen Regelungen die für den Arbeitnehmer günstigere.",
                   isTrue: true,
                   explanation: "Das Günstigkeitsprinzip durchbricht die Rangfolge zugunsten des Arbeitnehmers."),
        .statement(id: "mit-s11", topic: .mitbestimmung,
                   text: "Tarifverträge stehen in der Normenhierarchie über Betriebsvereinbarungen.",
                   isTrue: true,
                   explanation: "Rangfolge: Grundgesetz, Gesetz, Tarifvertrag, Betriebsvereinbarung, Arbeitsvertrag."),
        .statement(id: "mit-s12", topic: .mitbestimmung,
                   text: "Ein Warnstreik findet meist bereits während laufender Tarifverhandlungen statt.",
                   isTrue: true,
                   explanation: "Warnstreiks sind kurze Aktionen, um während der Verhandlungen Druck aufzubauen."),
        .statement(id: "mit-s13", topic: .mitbestimmung,
                   text: "Ein wilder Streik ohne Aufruf der Gewerkschaft ist rechtmäßig, solange die Mehrheit der Belegschaft mitmacht.",
                   isTrue: false,
                   explanation: "Ein wilder Streik ohne Gewerkschaft ist rechtswidrig, unabhängig von der Beteiligung."),
        .statement(id: "mit-s14", topic: .mitbestimmung,
                   text: "Gewerkschaften zahlen ihren Mitgliedern im Streikfall Streikgeld.",
                   isTrue: true,
                   explanation: "Streikgeld ist eine typische Gewerkschaftsleistung, da Streikende kein Entgelt erhalten."),
        .statement(id: "mit-s15", topic: .mitbestimmung,
                   text: "Arbeitslosengeld wird im Streikfall von der Gewerkschaft ausgezahlt.",
                   isTrue: false,
                   explanation: "Arbeitslosengeld zahlt die Bundesagentur für Arbeit; Gewerkschaften zahlen im Streikfall Streikgeld, kein Arbeitslosengeld."),

        // Multiple
        .multiple(id: "mit-m01", topic: .mitbestimmung,
                  prompt: "Wähle alle sozialen Angelegenheiten aus, bei denen der Betriebsrat nach § 87 BetrVG ein zwingendes Mitbestimmungsrecht hat.",
                  correct: ["Beginn und Ende der täglichen Arbeitszeit",
                            "Aufstellung der Urlaubsgrundsätze",
                            "Einführung technischer Überwachungseinrichtungen",
                            "Grundsätze der Entlohnung"],
                  wrong: ["Die Entscheidung über eine Preiserhöhung",
                          "Die Auswahl der Werbeagentur",
                          "Die Investitionsentscheidung für eine neue Maschine"],
                  explanation: "Alle vier genannten Punkte zählen zu den sozialen Angelegenheiten des § 87 BetrVG; unternehmerische Entscheidungen wie Preise, Werbung oder Investitionen sind mitbestimmungsfrei."),
        .multiple(id: "mit-m02", topic: .mitbestimmung,
                  prompt: "Wähle alle Aussagen aus, die für die Wahl zum Betriebsrat zutreffen.",
                  correct: ["Wahlberechtigt sind Arbeitnehmer ab 16 Jahren",
                            "Wählbar sind Wahlberechtigte ab 18 Jahren mit 6 Monaten Betriebszugehörigkeit",
                            "Leiharbeitnehmer sind nach mehr als 3 Monaten Einsatz wahlberechtigt"],
                  wrong: ["Leitende Angestellte sind wählbar",
                          "Die Wahl findet jedes Jahr statt",
                          "Nur Gewerkschaftsmitglieder dürfen wählen"],
                  explanation: "Leitende Angestellte fallen nicht unter das BetrVG, die Wahl findet alle 4 Jahre statt und das Wahlrecht ist unabhängig von einer Gewerkschaftsmitgliedschaft."),
        .multiple(id: "mit-m03", topic: .mitbestimmung,
                  prompt: "Wähle alle Tarifvertragsarten aus.",
                  correct: ["Manteltarifvertrag", "Entgelttarifvertrag", "Entgeltrahmentarifvertrag"],
                  wrong: ["Betriebsvereinbarung", "Sozialplan", "Interessenausgleich"],
                  explanation: "Betriebsvereinbarung, Sozialplan und Interessenausgleich werden zwischen Arbeitgeber und Betriebsrat geschlossen, nicht zwischen den Tarifparteien."),
        .multiple(id: "mit-m04", topic: .mitbestimmung,
                  prompt: "Wähle alle Streikformen aus.",
                  correct: ["Warnstreik", "Flächenstreik", "Schwerpunktstreik", "Sympathiestreik"],
                  wrong: ["Aussperrung", "Urabstimmung", "Schlichtung"],
                  explanation: "Die Aussperrung ist ein Kampfmittel der Arbeitgeberseite, Urabstimmung und Schlichtung sind Verfahrensschritte, aber keine Streikformen."),

        // Match
        .match(id: "mit-p01", topic: .mitbestimmung,
               prompt: "Ordne die Angelegenheit dem passenden Beteiligungsrecht des Betriebsrats zu.",
               pairs: [("Einführung von Kurzarbeit", "Mitbestimmung (§ 87 BetrVG)"),
                       ("Einstellung eines neuen Mitarbeiters in einem Unternehmen mit 40 wahlberechtigten Arbeitnehmern", "Zustimmungsverweigerungsrecht (§ 99 BetrVG)"),
                       ("Kündigung eines Arbeitnehmers", "Anhörung (§ 102 BetrVG)"),
                       ("Bauliche Veränderung der Werkshalle", "Unterrichtung und Beratung (§ 90 BetrVG)"),
                       ("Entscheidung über den Verkaufspreis eines Produkts", "Keine Beteiligung")],
               extra: ["Zustimmung der Betriebsversammlung"],
               explanation: "Die Beteiligungsrechte reichen von zwingender Mitbestimmung über Zustimmungsverweigerung und Anhörung bis zu reiner Information; bei rein unternehmerischen Entscheidungen besteht keine Beteiligung."),
        .match(id: "mit-p02", topic: .mitbestimmung,
               prompt: "Ordne die Regelung der passenden Ebene zu.",
               pairs: [("Homeoffice-Regeln für den Betrieb", "Betriebsvereinbarung"),
                       ("Höhe der Ausbildungsvergütung der Branche", "Tarifvertrag"),
                       ("Kündigungsfristen nach § 622 BGB", "Gesetz"),
                       ("Individuelle Vereinbarung der Wochenarbeitszeit mit einem Arbeitnehmer", "Arbeitsvertrag")],
               extra: ["Satzung der IHK"],
               explanation: "Die Rangfolge lautet Gesetz, Tarifvertrag, Betriebsvereinbarung, Arbeitsvertrag; jede Ebene regelt Arbeitsbedingungen auf ihrer eigenen Reichweite."),
        .match(id: "mit-p03", topic: .mitbestimmung,
               prompt: "Ordne den Begriff der passenden Institution bzw. Vertretung zu.",
               pairs: [("Verhandelt Tarifverträge für die Arbeitnehmerseite", "Gewerkschaft"),
                       ("Verhandelt Tarifverträge für die Arbeitgeberseite", "Arbeitgeberverband"),
                       ("Erklärt einen Tarifvertrag für allgemeinverbindlich", "Bundesministerium für Arbeit und Soziales"),
                       ("Entscheidet über Streitigkeiten aus dem Arbeitsverhältnis", "Arbeitsgericht"),
                       ("Vertritt die Auszubildenden im Betrieb", "Jugend- und Auszubildendenvertretung")],
               extra: [],
               explanation: "Jede Institution hat eine klar abgegrenzte Rolle im Tarif- und Betriebsverfassungsrecht."),
        .match(id: "mit-p04", topic: .mitbestimmung,
               prompt: "Ordne die Phase der Tarifrunde ihrer Beschreibung zu.",
               pairs: [("Gewerkschaft kündigt den bestehenden Tarifvertrag", "Beginn der Tarifrunde"),
                       ("Kurze Protestaktionen während laufender Verhandlungen", "Warnstreik"),
                       ("Abstimmung der Mitglieder vor dem Streik", "Urabstimmung"),
                       ("Arbeitgeber schließt Betriebe für die Beschäftigten", "Aussperrung")],
               extra: ["Betriebsversammlung"],
               explanation: "Die Tarifrunde durchläuft mehrere typische Phasen von der Kündigung des Tarifvertrags bis zum Arbeitskampf."),
        .match(id: "mit-p05", topic: .mitbestimmung,
               prompt: "Ordne die Anzahl wahlberechtigter Arbeitnehmer der passenden Betriebsratsgröße zu.",
               pairs: [("5 bis 20 wahlberechtigte Arbeitnehmer", "1 Mitglied"),
                       ("21 bis 50 wahlberechtigte Arbeitnehmer", "3 Mitglieder"),
                       ("51 bis 100 wahlberechtigte Arbeitnehmer", "5 Mitglieder"),
                       ("101 bis 200 wahlberechtigte Arbeitnehmer", "7 Mitglieder")],
               extra: ["9 Mitglieder"],
               explanation: "§ 9 BetrVG legt die Betriebsratsgröße nach der Zahl der wahlberechtigten Arbeitnehmer fest."),

        // Order
        .order(id: "mit-o01", topic: .mitbestimmung,
               prompt: "Bringe den Ablauf einer Tarifrunde in die richtige Reihenfolge.",
               steps: ["Die Gewerkschaft kündigt den bestehenden Tarifvertrag",
                       "Gewerkschaft und Arbeitgeberseite stellen ihre Forderungen und verhandeln",
                       "Die Verhandlungen scheitern, es kommt zu Warnstreiks",
                       "Die Gewerkschaftsmitglieder stimmen in der Urabstimmung über den Streik ab",
                       "Es kommt zum Streik, gegebenenfalls zur Aussperrung",
                       "Beide Seiten einigen sich in neuen Verhandlungen",
                       "Ein neuer Tarifvertrag tritt nach der zweiten Urabstimmung in Kraft"],
               explanation: "Ablauf: Kündigung, Verhandlung mit Friedenspflicht, Scheitern mit Warnstreiks, Urabstimmung, Arbeitskampf, Einigung, zweite Urabstimmung, neuer Tarifvertrag."),
        .order(id: "mit-o02", topic: .mitbestimmung,
               prompt: "Bringe den Ablauf bis zur Bildung eines neuen Betriebsrats in die richtige Reihenfolge.",
               steps: ["Ein Wahlvorstand wird bestellt",
                       "Der Wahlvorstand erstellt die Wählerliste und ruft zur Wahl auf",
                       "Wahlberechtigte Arbeitnehmer wählen die Betriebsratsmitglieder",
                       "Der Wahlvorstand stellt das Wahlergebnis fest und gibt es bekannt",
                       "Der neu gewählte Betriebsrat konstituiert sich und wählt einen Vorsitzenden"],
               explanation: "Eine Betriebsratswahl beginnt mit der Bestellung des Wahlvorstands und endet mit der Konstituierung des neuen Gremiums."),

        // Gap
        .gap(id: "mit-g01", topic: .mitbestimmung, title: "Mitbestimmung im Betrieb",
             sentences: [("Ein Betriebsrat kann in Betrieben mit mindestens ___ wahlberechtigten Arbeitnehmern gewählt werden.", "5"),
                         ("Bei sozialen Angelegenheiten nach § 87 BetrVG hat der Betriebsrat ein zwingendes ___.", "Mitbestimmungsrecht"),
                         ("Vereinbarungen zwischen Arbeitgeber und Betriebsrat heißen ___.", "Betriebsvereinbarungen"),
                         ("Bei einer Betriebsänderung mit wirtschaftlichen Nachteilen verhandeln Arbeitgeber und Betriebsrat einen ___.", "Sozialplan")],
             extra: ["Tarifvertrag", "Arbeitsvertrag"],
             explanation: "Die Begriffe stammen aus dem Betriebsverfassungsgesetz und beschreiben die zentralen Beteiligungsformen im Betrieb."),
        .gap(id: "mit-g02", topic: .mitbestimmung, title: "Tarifrecht",
             sentences: [("Die eigenständige Regelung der Arbeitsbedingungen durch Gewerkschaften und Arbeitgeberverbände heißt ___.", "Tarifautonomie"),
                         ("Während der Laufzeit eines Tarifvertrags gilt für die geregelten Inhalte grundsätzlich die ___.", "Friedenspflicht"),
                         ("Vor einem Streik stimmen die Gewerkschaftsmitglieder in einer ___ ab.", "Urabstimmung"),
                         ("Das Kampfmittel der Arbeitgeberseite im Arbeitskampf heißt ___.", "Aussperrung")],
             extra: ["Betriebsversammlung", "Wirtschaftsausschuss"],
             explanation: "Diese Begriffe beschreiben den rechtlichen Rahmen und den Ablauf von Tarifverhandlungen und Arbeitskämpfen."),

        // Facts
        .fact(id: "mit-f01", topic: .mitbestimmung, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Mitglieder hat der Betriebsrat in einem Betrieb mit 30 wahlberechtigten Arbeitnehmern?",
              answer: "3",
              explanation: "Bei 21 bis 50 wahlberechtigten Arbeitnehmern hat der Betriebsrat 3 Mitglieder (§ 9 BetrVG)."),
        .fact(id: "mit-f02", topic: .mitbestimmung, group: ExamCatalog.Group.anzahl,
              question: "Wie viele ständige wahlberechtigte Arbeitnehmer braucht ein Betrieb mindestens, um einen Betriebsrat zu bilden?",
              answer: "5",
              explanation: "§ 1 BetrVG verlangt mindestens 5 ständige wahlberechtigte Arbeitnehmer."),
        .fact(id: "mit-f03", topic: .mitbestimmung, group: ExamCatalog.Group.anzahl,
              question: "Ab wie vielen Arbeitnehmern im Unternehmen muss ein Wirtschaftsausschuss gebildet werden (mehr als)?",
              answer: "100",
              explanation: "In Unternehmen mit mehr als 100 Arbeitnehmern ist ein Wirtschaftsausschuss zu bilden (§ 106 BetrVG)."),
        .fact(id: "mit-f04", topic: .mitbestimmung, group: ExamCatalog.Group.alter,
              question: "Ab welchem Alter sind Arbeitnehmer bei der Betriebsratswahl wahlberechtigt?",
              answer: "16 Jahre",
              explanation: "§ 7 BetrVG senkte das Wahlrecht seit 2021 auf 16 Jahre."),
        .fact(id: "mit-f05", topic: .mitbestimmung, group: ExamCatalog.Group.alter,
              question: "Ab welchem Alter sind Arbeitnehmer bei der Betriebsratswahl wählbar?",
              answer: "18 Jahre",
              explanation: "Wählbar sind volljährige Wahlberechtigte mit mindestens 6 Monaten Betriebszugehörigkeit."),
        .fact(id: "mit-f09", topic: .mitbestimmung, group: ExamCatalog.Group.alter,
              question: "Beschäftigte unter welchem Alter sind in die Jugend- und Auszubildendenvertretung wählbar?",
              answer: "25 Jahre",
              explanation: "In die JAV wählbar sind Arbeitnehmer, die das 25. Lebensjahr noch nicht vollendet haben (§ 61 BetrVG)."),
        .fact(id: "mit-f06", topic: .mitbestimmung, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange dauert die regelmäßige Amtszeit des Betriebsrats?",
              answer: "4 Jahre",
              explanation: "§ 21 BetrVG sieht regelmäßige Wahlen alle 4 Jahre vor."),
        .fact(id: "mit-f07", topic: .mitbestimmung, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange dauert die Amtszeit der Jugend- und Auszubildendenvertretung (JAV)?",
              answer: "2 Jahre",
              explanation: "Die JAV wird für eine kürzere Amtszeit als der Betriebsrat gewählt."),
        .fact(id: "mit-f08", topic: .mitbestimmung, group: ExamCatalog.Group.stelle,
              question: "Welche Stelle erklärt einen Tarifvertrag für allgemeinverbindlich?",
              answer: "Bundesministerium für Arbeit und Soziales",
              explanation: "Die Allgemeinverbindlicherklärung erfolgt mit Zustimmung des Tarifausschusses."),
    ]

    // MARK: - Sozialversicherung & Steuern

    static let sozial: [ExamCard] = [
        // Choice
        .choice(id: "soz-c01", topic: .sozial,
                prompt: "Wie viele Zweige hat die gesetzliche Sozialversicherung in Deutschland?",
                options: ["5", "3", "4", "6", "7"],
                explanation: "Kranken-, Pflege-, Renten-, Arbeitslosen- und Unfallversicherung bilden die fünf Zweige."),
        .choice(id: "soz-c02", topic: .sozial,
                prompt: "Welcher Träger ist für die gesetzliche Rentenversicherung zuständig?",
                options: ["Deutsche Rentenversicherung", "Bundesagentur für Arbeit", "Berufsgenossenschaft", "Krankenkasse", "Sozialamt"],
                explanation: "Die Deutsche Rentenversicherung ist Trägerin der gesetzlichen Rentenversicherung."),
        .choice(id: "soz-c03", topic: .sozial,
                prompt: "Wer trägt die Beiträge zur gesetzlichen Unfallversicherung?",
                options: ["Der Arbeitgeber allein", "Arbeitgeber und Arbeitnehmer je zur Hälfte", "Der Arbeitnehmer allein", "Der Staat allein", "Arbeitgeber und Staat je zur Hälfte"],
                explanation: "Die Unfallversicherung ist der einzige Zweig, dessen Beiträge allein vom Arbeitgeber getragen werden."),
        .choice(id: "soz-c04", topic: .sozial,
                prompt: "Wie werden die Beiträge zur Kranken-, Pflege-, Renten- und Arbeitslosenversicherung grundsätzlich aufgeteilt?",
                options: ["Arbeitgeber und Arbeitnehmer tragen sie grundsätzlich je zur Hälfte",
                          "Allein der Arbeitgeber trägt sie",
                          "Allein der Arbeitnehmer trägt sie",
                          "Der Staat übernimmt sie vollständig",
                          "Sie werden frei im Arbeitsvertrag vereinbart"],
                explanation: "Grundsätzlich gilt die hälftige Beitragsteilung; Ausnahmen gibt es u. a. beim Pflegeversicherungs-Kinderlosenzuschlag."),
        .choice(id: "soz-c05", topic: .sozial,
                prompt: "Welches Prinzip beschreibt, dass Beiträge nach der Leistungsfähigkeit und Leistungen nach dem Bedarf gezahlt werden?",
                options: ["Solidaritätsprinzip", "Äquivalenzprinzip", "Subsidiaritätsprinzip", "Versicherungsprinzip", "Kausalprinzip"],
                explanation: "Das Solidaritätsprinzip prägt die gesetzliche Sozialversicherung: die Gemeinschaft trägt das Risiko des Einzelnen."),
        .choice(id: "soz-c06", topic: .sozial,
                prompt: "Was beschreibt das Äquivalenzprinzip der privaten Versicherung?",
                options: ["Die Prämie richtet sich nach dem individuellen Risiko der versicherten Person",
                          "Der Beitrag richtet sich nach dem Einkommen",
                          "Alle Versicherten zahlen den gleichen Beitrag unabhängig vom Risiko",
                          "Der Staat übernimmt die Prämie",
                          "Die Leistung richtet sich nach der Anzahl der Kinder"],
                explanation: "Anders als bei der gesetzlichen Sozialversicherung bemisst sich der Beitrag der Individualversicherung am Risiko der versicherten Person."),
        .choice(id: "soz-c07", topic: .sozial,
                prompt: "Wie finanziert sich die gesetzliche Rentenversicherung überwiegend?",
                options: ["Im Umlageverfahren: Die Beiträge der aktuell Erwerbstätigen finanzieren die laufenden Renten",
                          "Im Kapitaldeckungsverfahren wie eine private Lebensversicherung",
                          "Ausschließlich aus Steuermitteln",
                          "Durch Beiträge der Rentnerinnen und Rentner selbst",
                          "Durch Erträge aus Börsengeschäften der Rentenversicherung"],
                explanation: "Das Umlageverfahren wird auch Generationenvertrag genannt: die Erwerbstätigen finanzieren die laufenden Renten."),
        .choice(id: "soz-c08", topic: .sozial,
                prompt: "Herr Dolinski ist als Angestellter gesetzlich krankenversichert und schließt zusätzlich eine private Berufsunfähigkeitsversicherung ab. Wie nennt man diese zusätzliche Versicherung?",
                options: ["Individualversicherung", "Pflichtversicherung", "Familienversicherung", "Sozialversicherung", "Zusatzbeitrag"],
                explanation: "Eine freiwillig abgeschlossene Versicherung mit risikoabhängiger Prämie ist eine Individualversicherung."),
        .choice(id: "soz-c09", topic: .sozial,
                prompt: "Was besagt das Drei-Säulen-Modell der Altersvorsorge?",
                options: ["Altersvorsorge setzt sich aus gesetzlicher, betrieblicher und privater Vorsorge zusammen",
                          "Es beschreibt die drei Träger der Sozialversicherung",
                          "Es beschreibt drei Beitragsstufen der Rentenversicherung",
                          "Es beschreibt drei Arten von Krankenkassen",
                          "Es beschreibt die drei Zweige der Arbeitslosenversicherung"],
                explanation: "Die drei Säulen sind gesetzliche Rentenversicherung, betriebliche Altersvorsorge und private Vorsorge."),
        .choice(id: "soz-c10", topic: .sozial,
                prompt: "Was passiert mit dem Einkommen oberhalb der Beitragsbemessungsgrenze?",
                options: ["Es bleibt bei der Berechnung der Sozialversicherungsbeiträge unberücksichtigt",
                          "Es wird doppelt verbeitragt",
                          "Es senkt den Beitragssatz für alle Versicherten",
                          "Es wird nur in der Krankenversicherung berücksichtigt",
                          "Es erhöht automatisch die Rente um den vollen Betrag"],
                explanation: "Oberhalb der Beitragsbemessungsgrenze werden keine weiteren Sozialversicherungsbeiträge fällig."),
        .choice(id: "soz-c11", topic: .sozial,
                prompt: "Welche Leistung zahlt die Krankenkasse, wenn die 6 Wochen Entgeltfortzahlung durch den Arbeitgeber vorbei sind?",
                options: ["Krankengeld", "Arbeitslosengeld", "Verletztengeld", "Übergangsgeld", "Pflegegeld"],
                explanation: "Nach Ablauf der Entgeltfortzahlung zahlt die Krankenkasse Krankengeld."),
        .choice(id: "soz-c12", topic: .sozial,
                prompt: "Welche Leistung erbringt die gesetzliche Unfallversicherung?",
                options: ["Heilbehandlung und Verletztenrente nach einem Arbeitsunfall",
                          "Arbeitslosengeld bei Jobverlust",
                          "Krankengeld bei privater Erkrankung",
                          "Altersrente nach 45 Beitragsjahren",
                          "Kurzarbeitergeld"],
                explanation: "Die Unfallversicherung leistet u. a. Heilbehandlung, Verletztengeld und Verletztenrente nach Arbeits- und Wegeunfällen."),
        .choice(id: "soz-c13", topic: .sozial,
                prompt: "Welche Leistung zahlt die Arbeitslosenversicherung neben dem Arbeitslosengeld auch?",
                options: ["Kurzarbeitergeld", "Krankengeld", "Pflegegeld", "Verletztenrente", "Mutterschaftsgeld"],
                explanation: "Die Bundesagentur für Arbeit zahlt neben Arbeitslosengeld auch Kurzarbeitergeld und Insolvenzgeld."),
        .choice(id: "soz-c14", topic: .sozial,
                prompt: "Welche Leistung erbringt die Pflegeversicherung?",
                options: ["Pflegegeld und Pflegesachleistungen je nach Pflegegrad",
                          "Krankengeld bei Arbeitsunfähigkeit",
                          "Erwerbsminderungsrente",
                          "Arbeitslosengeld",
                          "Verletztenrente nach einem Arbeitsunfall"],
                explanation: "Die Leistungen der Pflegeversicherung richten sich nach dem festgestellten Pflegegrad."),
        .choice(id: "soz-c15", topic: .sozial,
                prompt: "Welches Gericht ist zuständig, wenn ein Versicherter gegen die Ablehnung eines Rentenantrags klagt?",
                options: ["Das Sozialgericht", "Das Arbeitsgericht", "Das Amtsgericht", "Das Verwaltungsgericht", "Das Finanzgericht"],
                explanation: "Streitigkeiten mit Sozialversicherungsträgern werden nach dem Widerspruchsverfahren vor dem Sozialgericht verhandelt."),
        .choice(id: "soz-c16", topic: .sozial,
                prompt: "Frau Yılmaz ist alleinerziehend und erwerbstätig. Welche Steuerklasse trifft in der Regel auf sie zu?",
                options: ["Steuerklasse II", "Steuerklasse I", "Steuerklasse III", "Steuerklasse V", "Steuerklasse VI"],
                explanation: "Steuerklasse II gilt für Alleinerziehende und berücksichtigt den Entlastungsbetrag."),
        .choice(id: "soz-c17", topic: .sozial,
                prompt: "Welche Steuerklasse gilt typischerweise für einen zweiten, weiteren Job neben der Hauptbeschäftigung?",
                options: ["Steuerklasse VI", "Steuerklasse I", "Steuerklasse II", "Steuerklasse IV", "Steuerklasse V"],
                explanation: "Für Nebenbeschäftigungen wird in der Regel Steuerklasse VI angewendet."),
        .choice(id: "soz-c18", topic: .sozial,
                prompt: "Was ist die Lohnsteuer?",
                options: ["Eine monatliche Vorauszahlung auf die Einkommensteuer, die der Arbeitgeber einbehält und abführt",
                          "Eine eigenständige Steuer neben der Einkommensteuer",
                          "Eine freiwillige Zahlung des Arbeitnehmers",
                          "Eine Steuer, die nur Selbstständige zahlen",
                          "Ein Teil der Sozialversicherungsbeiträge"],
                explanation: "Die Lohnsteuer wird mit der jährlichen Einkommensteuer verrechnet, sie ist keine eigenständige Steuerart."),
        .choice(id: "soz-c19", topic: .sozial,
                prompt: "Was versteht man unter Werbungskosten?",
                options: ["Aufwendungen zur Erwerbung, Sicherung und Erhaltung der Einnahmen, z. B. Fahrtkosten zur Arbeit",
                          "Ausgaben für private Werbung eines Unternehmens",
                          "Kosten der privaten Altersvorsorge",
                          "Spenden an gemeinnützige Organisationen",
                          "Die Beiträge zur Krankenversicherung"],
                explanation: "Werbungskosten wie die Entfernungspauschale oder Fachliteratur mindern das zu versteuernde Einkommen."),
        .choice(id: "soz-c20", topic: .sozial,
                prompt: "Wie ist die deutsche Einkommensteuer grundsätzlich ausgestaltet?",
                options: ["Progressiv: Mit steigendem Einkommen steigt der Steuersatz, bis zum Grundfreibetrag bleibt das Einkommen steuerfrei",
                          "Degressiv: Mit steigendem Einkommen sinkt der Steuersatz",
                          "Als fester Prozentsatz unabhängig von der Einkommenshöhe",
                          "Nur für Selbstständige, nicht für Arbeitnehmer",
                          "Ausschließlich als Pauschale pro Kopf"],
                explanation: "Die Einkommensteuer ist progressiv gestaffelt; unterhalb des Grundfreibetrags fällt keine Steuer an."),
        .choice(id: "soz-c21", topic: .sozial,
                prompt: "Welche Steuer zählt zu den indirekten Steuern?",
                options: ["Die Umsatzsteuer", "Die Einkommensteuer", "Die Lohnsteuer", "Die Kirchensteuer", "Der Solidaritätszuschlag"],
                explanation: "Bei der Umsatzsteuer sind Steuerschuldner (Unternehmen) und wirtschaftlich Belasteter (Endverbraucher) nicht identisch."),
        .choice(id: "soz-c22", topic: .sozial,
                prompt: "Was unterscheidet direkte von indirekten Steuern?",
                options: ["Bei direkten Steuern sind Steuerschuldner und wirtschaftlich Belasteter identisch, bei indirekten Steuern nicht",
                          "Direkte Steuern zahlen nur Unternehmen",
                          "Indirekte Steuern gibt es nur auf Importe",
                          "Direkte Steuern werden monatlich, indirekte jährlich erhoben",
                          "Indirekte Steuern zahlen nur Selbstständige"],
                explanation: "Bei indirekten Steuern wie der Umsatzsteuer wird die Steuerlast über den Preis an andere weitergegeben."),
        .choice(id: "soz-c23", topic: .sozial,
                prompt: "Was wird bei der Lohnabrechnung vom Bruttoentgelt zuerst abgezogen, um zum Nettoentgelt zu kommen?",
                options: ["Lohnsteuer und die Arbeitnehmeranteile zur Sozialversicherung",
                          "Nur die vermögenswirksamen Leistungen",
                          "Nur der Vorschuss des Vormonats",
                          "Nur die Kirchensteuer",
                          "Nur der Solidaritätszuschlag"],
                explanation: "Vom Bruttoentgelt werden Lohnsteuer, ggf. Solidaritätszuschlag und Kirchensteuer sowie die Arbeitnehmeranteile zur Sozialversicherung abgezogen."),
        .choice(id: "soz-c24", topic: .sozial,
                prompt: "Auszubildender Kevin bekommt in einem Monat einen Gehaltsvorschuss ausgezahlt. Wie wirkt sich das auf seine Lohnabrechnung aus?",
                options: ["Der Vorschuss wird vom Nettoentgelt abgezogen, um den Auszahlungsbetrag zu ermitteln",
                          "Der Vorschuss erhöht das Bruttoentgelt",
                          "Der Vorschuss senkt die Lohnsteuer",
                          "Der Vorschuss wird der Sozialversicherung gemeldet",
                          "Der Vorschuss wird von der Krankenkasse erstattet"],
                explanation: "Vorschüsse werden erst ausgezahlt und im Folgemonat vom Nettoentgelt abgezogen, um den Auszahlungsbetrag zu ermitteln."),

        // Statements
        .statement(id: "soz-s01", topic: .sozial,
                   text: "Die gesetzliche Sozialversicherung besteht aus fünf Zweigen.",
                   isTrue: true,
                   explanation: "Kranken-, Pflege-, Renten-, Arbeitslosen- und Unfallversicherung."),
        .statement(id: "soz-s02", topic: .sozial,
                   text: "Die Beiträge zur Unfallversicherung werden von Arbeitgeber und Arbeitnehmer je zur Hälfte getragen.",
                   isTrue: false,
                   explanation: "Die Unfallversicherung trägt allein der Arbeitgeber."),
        .statement(id: "soz-s03", topic: .sozial,
                   text: "Das Solidaritätsprinzip bedeutet, dass die Gemeinschaft der Versicherten das Risiko des Einzelnen mitträgt.",
                   isTrue: true,
                   explanation: "Beitrag nach Leistungsfähigkeit, Leistung nach Bedarf – die Grundidee der Solidargemeinschaft."),
        .statement(id: "soz-s04", topic: .sozial,
                   text: "Bei einer privaten Versicherung richtet sich der Beitrag nach dem individuellen Risiko (Äquivalenzprinzip).",
                   isTrue: true,
                   explanation: "Das unterscheidet die Individualversicherung von der gesetzlichen Sozialversicherung."),
        .statement(id: "soz-s05", topic: .sozial,
                   text: "Die gesetzliche Rentenversicherung ist kapitalgedeckt wie eine private Rentenversicherung.",
                   isTrue: false,
                   explanation: "Sie finanziert sich im Umlageverfahren: die aktuell Erwerbstätigen finanzieren die laufenden Renten."),
        .statement(id: "soz-s06", topic: .sozial,
                   text: "Einkommen oberhalb der Beitragsbemessungsgrenze ist von weiteren Sozialversicherungsbeiträgen befreit.",
                   isTrue: true,
                   explanation: "Oberhalb dieser Grenze werden keine zusätzlichen Beiträge mehr fällig."),
        .statement(id: "soz-s07", topic: .sozial,
                   text: "Krankengeld wird von der Krankenkasse gezahlt, nachdem die Entgeltfortzahlung des Arbeitgebers endet.",
                   isTrue: true,
                   explanation: "Nach den 6 Wochen Entgeltfortzahlung übernimmt die Krankenkasse mit dem Krankengeld."),
        .statement(id: "soz-s08", topic: .sozial,
                   text: "Arbeitslosengeld wird von der Krankenkasse ausgezahlt.",
                   isTrue: false,
                   explanation: "Arbeitslosengeld zahlt die Bundesagentur für Arbeit."),
        .statement(id: "soz-s09", topic: .sozial,
                   text: "Kurzarbeitergeld ist eine Leistung der Arbeitslosenversicherung.",
                   isTrue: true,
                   explanation: "Kurzarbeitergeld wird von der Bundesagentur für Arbeit aus Mitteln der Arbeitslosenversicherung gezahlt."),
        .statement(id: "soz-s10", topic: .sozial,
                   text: "Streitigkeiten mit der eigenen Krankenkasse werden vor dem Arbeitsgericht verhandelt.",
                   isTrue: false,
                   explanation: "Für Streitigkeiten mit Sozialversicherungsträgern ist das Sozialgericht zuständig."),
        .statement(id: "soz-s11", topic: .sozial,
                   text: "Steuerklasse VI gilt typischerweise für ein zweites Arbeitsverhältnis.",
                   isTrue: true,
                   explanation: "Nebenbeschäftigungen werden in der Regel mit Steuerklasse VI abgerechnet."),
        .statement(id: "soz-s12", topic: .sozial,
                   text: "Die Lohnsteuer ist eine eigenständige Steuerart, unabhängig von der Einkommensteuer.",
                   isTrue: false,
                   explanation: "Die Lohnsteuer ist eine Vorauszahlung auf die Einkommensteuer, keine eigene Steuerart."),
        .statement(id: "soz-s13", topic: .sozial,
                   text: "Fahrtkosten zur Arbeit können in der Steuererklärung als Werbungskosten geltend gemacht werden.",
                   isTrue: true,
                   explanation: "Über die Entfernungspauschale mindern Fahrtkosten das zu versteuernde Einkommen."),
        .statement(id: "soz-s14", topic: .sozial,
                   text: "Die Umsatzsteuer zählt zu den direkten Steuern.",
                   isTrue: false,
                   explanation: "Die Umsatzsteuer ist eine indirekte Steuer, da sie über den Preis auf den Endverbraucher abgewälzt wird."),
        .statement(id: "soz-s15", topic: .sozial,
                   text: "Beim Drei-Säulen-Modell der Altersvorsorge zählt auch die betriebliche Altersvorsorge dazu.",
                   isTrue: true,
                   explanation: "Die drei Säulen sind gesetzliche, betriebliche und private Altersvorsorge."),

        // Multiple
        .multiple(id: "soz-m01", topic: .sozial,
                  prompt: "Wähle alle fünf Zweige der gesetzlichen Sozialversicherung aus.",
                  correct: ["Krankenversicherung", "Pflegeversicherung", "Rentenversicherung", "Arbeitslosenversicherung", "Unfallversicherung"],
                  wrong: ["Lebensversicherung", "Hausratversicherung"],
                  explanation: "Lebens- und Hausratversicherung sind private Individualversicherungen, keine Zweige der gesetzlichen Sozialversicherung."),
        .multiple(id: "soz-m02", topic: .sozial,
                  prompt: "Wähle alle Leistungen aus, die von der gesetzlichen Krankenversicherung erbracht werden.",
                  correct: ["Krankengeld", "Übernahme von Arztkosten", "Mutterschaftsgeld", "Kinderkrankengeld"],
                  wrong: ["Arbeitslosengeld", "Verletztenrente", "Pflegegeld"],
                  explanation: "Arbeitslosengeld, Verletztenrente und Pflegegeld werden von anderen Versicherungszweigen erbracht."),
        .multiple(id: "soz-m03", topic: .sozial,
                  prompt: "Wähle alle Aussagen aus, die für die Lohnabrechnung zutreffen.",
                  correct: ["Die Lohnsteuer wird vom Arbeitgeber einbehalten und abgeführt",
                            "Die Arbeitnehmeranteile zur Sozialversicherung mindern das Nettoentgelt",
                            "Der Solidaritätszuschlag wird nur bei hohen Einkommen fällig"],
                  wrong: ["Die Umsatzsteuer wird vom Bruttoentgelt abgezogen",
                          "Die Kirchensteuer wird unabhängig von der Religionszugehörigkeit erhoben",
                          "Vermögenswirksame Leistungen erhöhen automatisch das Bruttoentgelt"],
                  explanation: "Die Umsatzsteuer und die Kirchensteuer-Aussage sind falsch, ebenso die Aussage zu vermögenswirksamen Leistungen: sie werden vom Nettoentgelt abgezweigt."),
        .multiple(id: "soz-m04", topic: .sozial,
                  prompt: "Wähle alle Beispiele für Werbungskosten aus.",
                  correct: ["Fahrtkosten zur Arbeitsstätte (Entfernungspauschale)", "Fachliteratur für den Beruf", "Notwendige Arbeitsmittel"],
                  wrong: ["Private Urlaubsreise", "Lebensmitteleinkäufe", "Miete der privaten Wohnung"],
                  explanation: "Werbungskosten müssen beruflich veranlasst sein; private Ausgaben zählen nicht dazu."),

        // Match
        .match(id: "soz-p01", topic: .sozial,
               prompt: "Ordne die Leistung dem zuständigen Versicherungszweig zu.",
               pairs: [("Krankengeld bei Arbeitsunfähigkeit", "Krankenversicherung"),
                       ("Pflegegeld bei häuslicher Pflege", "Pflegeversicherung"),
                       ("Altersrente nach Erreichen der Regelaltersgrenze", "Rentenversicherung"),
                       ("Kurzarbeitergeld", "Arbeitslosenversicherung"),
                       ("Verletztenrente nach einem Arbeitsunfall", "Unfallversicherung")],
               extra: ["Sozialhilfe"],
               explanation: "Jeder Versicherungszweig deckt ein eigenes Lebensrisiko mit eigenen Leistungen ab."),
        .match(id: "soz-p02", topic: .sozial,
               prompt: "Ordne die Institution ihrer Zuständigkeit zu.",
               pairs: [("Deutsche Rentenversicherung", "Trägerin der gesetzlichen Rentenversicherung"),
                       ("Bundesagentur für Arbeit", "Trägerin der Arbeitslosenversicherung"),
                       ("Berufsgenossenschaft", "Trägerin der Unfallversicherung"),
                       ("Krankenkasse", "Trägerin der Kranken- und Pflegeversicherung")],
               extra: ["Finanzamt"],
               explanation: "Jeder Zweig der Sozialversicherung hat einen eigenen Träger."),
        .match(id: "soz-p03", topic: .sozial,
               prompt: "Ordne die Regelung der passenden Ebene zu.",
               pairs: [("Sozialversicherungspflicht und Leistungsansprüche", "Gesetz"),
                       ("Höhe der Ausbildungsvergütung einer Branche", "Tarifvertrag"),
                       ("Konkrete Homeoffice-Tage in einem Betrieb", "Betriebsvereinbarung"),
                       ("Individuelle Gehaltshöhe eines einzelnen Arbeitnehmers", "Arbeitsvertrag")],
               extra: [],
               explanation: "Von der gesetzlichen Grundlage bis zur individuellen Vereinbarung gibt es eine klare Regelungsebene."),
        .match(id: "soz-p04", topic: .sozial,
               prompt: "Ordne den Begriff dem passenden Prinzip der Sozialversicherung zu.",
               pairs: [("Beitrag nach Einkommen, Leistung nach Bedarf", "Solidaritätsprinzip"),
                       ("Beitrag richtet sich nach dem individuellen Risiko", "Äquivalenzprinzip"),
                       ("Erwerbstätige finanzieren die laufenden Renten der Älteren", "Umlageverfahren / Generationenvertrag"),
                       ("Eigenverantwortung geht staatlicher Hilfe vor", "Subsidiaritätsprinzip")],
               extra: ["Kausalprinzip"],
               explanation: "Diese vier Prinzipien prägen das deutsche Sozialversicherungs- und Vorsorgesystem."),
        .match(id: "soz-p05", topic: .sozial,
               prompt: "Ordne die Steuer der passenden Kategorie zu.",
               pairs: [("Einkommensteuer", "Direkte Steuer"),
                       ("Lohnsteuer", "Direkte Steuer"),
                       ("Umsatzsteuer", "Indirekte Steuer"),
                       ("Kirchensteuer", "Direkte Steuer")],
               extra: ["Gebühr"],
               explanation: "Bei direkten Steuern sind Steuerschuldner und wirtschaftlich Belasteter identisch, bei der Umsatzsteuer als indirekter Steuer nicht."),

        // Order
        .order(id: "soz-o01", topic: .sozial,
               prompt: "Bringe die Abzüge bei der Lohnabrechnung vom Bruttoentgelt bis zum Auszahlungsbetrag in die richtige Reihenfolge.",
               steps: ["Bruttoentgelt",
                       "Abzug von Lohnsteuer, Solidaritätszuschlag und ggf. Kirchensteuer",
                       "Abzug der Arbeitnehmeranteile zur Sozialversicherung",
                       "Nettoentgelt",
                       "Abzug von Vorschüssen und vermögenswirksamen Leistungen",
                       "Auszahlungsbetrag"],
               explanation: "Vom Bruttoentgelt werden zuerst Steuern und Sozialversicherungsbeiträge abgezogen, danach ggf. Vorschüsse, bis der Auszahlungsbetrag feststeht."),
        .order(id: "soz-o02", topic: .sozial,
               prompt: "Bringe den Ablauf von der Erkrankung eines Arbeitnehmers bis zum Bezug von Krankengeld in die richtige Reihenfolge.",
               steps: ["Der Arbeitnehmer meldet sich krank und legt eine Arbeitsunfähigkeitsbescheinigung vor",
                       "Der Arbeitgeber zahlt bis zu 6 Wochen das Entgelt fort",
                       "Nach Ablauf der 6 Wochen tritt die Krankenkasse ein",
                       "Die Krankenkasse zahlt Krankengeld, längstens bis zu 78 Wochen"],
               explanation: "Erst zahlt der Arbeitgeber im Rahmen der Entgeltfortzahlung, danach übernimmt die Krankenkasse mit dem Krankengeld."),

        // Gap
        .gap(id: "soz-g01", topic: .sozial, title: "Sozialversicherung",
             sentences: [("Die gesetzliche Sozialversicherung gliedert sich in fünf ___.", "Zweige"),
                         ("Die Beiträge zur Kranken-, Pflege-, Renten- und Arbeitslosenversicherung tragen Arbeitgeber und Arbeitnehmer grundsätzlich zu gleichen ___.", "Teilen"),
                         ("Die Beiträge zur Unfallversicherung trägt allein der ___.", "Arbeitgeber"),
                         ("Einkommen oberhalb der ___ bleibt bei den Sozialversicherungsbeiträgen unberücksichtigt.", "Beitragsbemessungsgrenze")],
             extra: ["Einkommensteuer", "Lohnsteuer"],
             explanation: "Die Begriffe beschreiben die Struktur und Finanzierung der gesetzlichen Sozialversicherung."),
        .gap(id: "soz-g02", topic: .sozial, title: "Lohn und Steuern",
             sentences: [("Die Lohnsteuer ist eine monatliche Vorauszahlung auf die ___.", "Einkommensteuer"),
                         ("Aufwendungen zur Erwerbung und Erhaltung der Einnahmen heißen ___.", "Werbungskosten"),
                         ("Für Alleinerziehende gibt es die Steuerklasse ___.", "II"),
                         ("Die Umsatzsteuer zählt zu den ___ Steuern.", "indirekten")],
             extra: ["direkten", "Werbungspflicht"],
             explanation: "Die Begriffe beschreiben die wichtigsten Grundlagen von Lohnabrechnung und Besteuerung."),

        // Facts
        .fact(id: "soz-f01", topic: .sozial, group: ExamCatalog.Group.prozent,
              question: "Wie hoch ist der Beitragssatz der Rentenversicherung (Stand 2026)?",
              answer: "18,6 %",
              explanation: "Beitragssatz zum Rechnen und Merken, Stand 2026: 18,6 %."),
        .fact(id: "soz-f02", topic: .sozial, group: ExamCatalog.Group.prozent,
              question: "Wie hoch ist der Beitragssatz der Arbeitslosenversicherung (Stand 2026)?",
              answer: "2,6 %",
              explanation: "Beitragssatz zum Rechnen und Merken, Stand 2026: 2,6 %."),
        .fact(id: "soz-f03", topic: .sozial, group: ExamCatalog.Group.prozent,
              question: "Wie hoch ist der allgemeine Beitragssatz der Krankenversicherung ohne Zusatzbeitrag (Stand 2026)?",
              answer: "14,6 %",
              explanation: "Beitragssatz zum Rechnen und Merken, Stand 2026: 14,6 % zuzüglich individuellem Zusatzbeitrag."),
        .fact(id: "soz-f04", topic: .sozial, group: ExamCatalog.Group.prozent,
              question: "Wie hoch ist der Beitragssatz der Pflegeversicherung für Eltern (Stand 2026)?",
              answer: "3,6 %",
              explanation: "Beitragssatz zum Rechnen und Merken, Stand 2026: 3,6 %, für Kinderlose zuzüglich 0,6 %."),
        .fact(id: "soz-f05", topic: .sozial, group: ExamCatalog.Group.anzahl,
              question: "Aus wie vielen Zweigen besteht die gesetzliche Sozialversicherung?",
              answer: "5",
              explanation: "Kranken-, Pflege-, Renten-, Arbeitslosen- und Unfallversicherung."),
        .fact(id: "soz-f06", topic: .sozial, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange zahlt der Arbeitgeber im Krankheitsfall das Entgelt fort?",
              answer: "6 Wochen",
              explanation: "Nach dem Entgeltfortzahlungsgesetz besteht der Anspruch für bis zu 6 Wochen."),
        .fact(id: "soz-f07", topic: .sozial, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange kann Krankengeld längstens bezogen werden?",
              answer: "78 Wochen",
              explanation: "Krankengeld wird wegen derselben Krankheit für längstens 78 Wochen innerhalb von 3 Jahren gezahlt."),
        .fact(id: "soz-f08", topic: .sozial, group: ExamCatalog.Group.stelle,
              question: "Welches Gericht ist bei einem Streit mit der Krankenkasse zuständig?",
              answer: "Sozialgericht",
              explanation: "Streitigkeiten mit Sozialversicherungsträgern werden vor dem Sozialgericht verhandelt."),
    ]
}
