// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Lino Laske

import Foundation

extension ExamCatalog {
    static let unternehmen: [ExamCard] = [
        // MARK: Choice
        .choice(id: "unt-c01", topic: .unternehmen,
                prompt: "Aylin möchte allein ein kleines Café eröffnen und selbst alle Entscheidungen treffen. Für die volle Kontrolle nimmt sie in Kauf, mit ihrem gesamten Privatvermögen zu haften. Welche Rechtsform passt am besten?",
                options: ["Einzelunternehmen", "GmbH", "AG", "eG", "GmbH & Co. KG"],
                explanation: "Beim Einzelunternehmen entscheidet der Inhaber allein und haftet unbeschränkt mit seinem Privat- und Betriebsvermögen."),
        .choice(id: "unt-c02", topic: .unternehmen,
                prompt: "Was gilt seit der Reform durch das MoPeG (2024) für die Gesellschaft bürgerlichen Rechts (GbR)?",
                options: ["Sie ist rechtsfähig und kann als eGbR ins Gesellschaftsregister eingetragen werden.", "Sie darf keine eigenen Verträge mehr abschließen.", "Sie wird automatisch zur OHG.", "Sie muss zwingend ins Handelsregister eingetragen werden.", "Sie verliert ihre Rechtsfähigkeit bei mehr als zwei Gesellschaftern."],
                explanation: "Seit dem MoPeG 2024 ist die GbR rechtsfähig; eine Eintragung als eGbR ins Gesellschaftsregister ist freiwillig, aber Voraussetzung für bestimmte Geschäfte."),
        .choice(id: "unt-c03", topic: .unternehmen,
                prompt: "Jonas und Mira betreiben gemeinsam eine offene Handelsgesellschaft (OHG). Wie haften sie für die Schulden des Unternehmens?",
                options: ["Beide haften unbeschränkt, unmittelbar und gesamtschuldnerisch mit ihrem Privatvermögen.", "Nur Jonas haftet, weil er der ältere Gesellschafter ist.", "Beide haften nur mit ihrer Einlage.", "Die OHG haftet allein als juristische Person, die Gesellschafter nicht.", "Sie haften nur, wenn ein Gericht dies ausdrücklich anordnet."],
                explanation: "Bei der OHG haften alle Gesellschafter unbeschränkt, unmittelbar und gesamtschuldnerisch (§ 128 HGB)."),
        .choice(id: "unt-c04", topic: .unternehmen,
                prompt: "In einer KG ist Herr Beck Kommanditist mit einer Einlage von 10.000 €. Wie haftet er für Schulden der Gesellschaft?",
                options: ["Nur bis zur Höhe seiner Einlage von 10.000 €.", "Unbeschränkt mit seinem gesamten Privatvermögen.", "Gar nicht, da Kommanditisten nie haften.", "Wie ein Komplementär, also unbeschränkt und unmittelbar.", "Nur, wenn die Gesellschaft insolvent wird und er ausdrücklich zustimmt."],
                explanation: "Der Kommanditist haftet nur bis zur Höhe seiner im Handelsregister eingetragenen Einlage."),
        .choice(id: "unt-c05", topic: .unternehmen,
                prompt: "Welche Aussage über die Rechte eines Kommanditisten in der KG trifft zu?",
                options: ["Er ist nicht zur Geschäftsführung befugt, hat aber ein Widerspruchsrecht bei außergewöhnlichen Geschäften.", "Er führt die laufenden Geschäfte allein.", "Er darf jederzeit Prokura erteilen.", "Er haftet unbeschränkt, entscheidet aber nicht mit.", "Er hat kein Mitspracherecht bei irgendwelchen Entscheidungen."],
                explanation: "Der Kommanditist ist von der Geschäftsführung ausgeschlossen, kann aber außergewöhnlichen Geschäften widersprechen."),
        .choice(id: "unt-c06", topic: .unternehmen,
                prompt: "Was unterscheidet die GmbH rechtlich von einem Einzelunternehmen?",
                options: ["Die GmbH ist eine juristische Person und haftet mit dem Gesellschaftsvermögen.", "Die GmbH hat keinen eigenen Namen.", "Die GmbH braucht kein Stammkapital.", "Die GmbH kann nicht ins Handelsregister eingetragen werden.", "Die GmbH darf nur von einer einzigen Person gegründet werden."],
                explanation: "Die GmbH ist eine juristische Person; für ihre Verbindlichkeiten haftet grundsätzlich nur das Gesellschaftsvermögen, nicht die Gesellschafter privat."),
        .choice(id: "unt-c07", topic: .unternehmen,
                prompt: "Wann entsteht eine GmbH rechtlich?",
                options: ["Mit der Eintragung ins Handelsregister, Abteilung B.", "Mit Unterzeichnung des Gesellschaftsvertrags.", "Mit der Gewerbeanmeldung beim Gewerbeamt.", "Mit der ersten Rechnung an einen Kunden.", "Mit der Anmeldung beim Finanzamt."],
                explanation: "Die GmbH entsteht erst mit der konstitutiven Eintragung ins Handelsregister, Abteilung B."),
        .choice(id: "unt-c08", topic: .unternehmen,
                prompt: "Welche Formvorschrift gilt für den Gesellschaftsvertrag einer GmbH?",
                options: ["Er muss notariell beurkundet werden.", "Er kann formfrei mündlich geschlossen werden.", "Er braucht nur die Textform (z. B. E-Mail).", "Er muss beim Finanzamt hinterlegt werden.", "Er muss von der IHK genehmigt werden."],
                explanation: "Der Gesellschaftsvertrag einer GmbH bedarf der notariellen Beurkundung."),
        .choice(id: "unt-c09", topic: .unternehmen,
                prompt: "Wie sind die Organe einer Aktiengesellschaft aufgeteilt?",
                options: ["Vorstand leitet, Aufsichtsrat überwacht und bestellt den Vorstand, Hauptversammlung entscheidet über Grundlagenfragen.", "Es gibt nur einen Geschäftsführer und sonst keine Organe.", "Die Aktionäre führen die Geschäfte direkt.", "Der Aufsichtsrat leitet das Tagesgeschäft, der Vorstand überwacht ihn.", "Die Hauptversammlung führt die laufenden Geschäfte."],
                explanation: "Bei der AG leitet der Vorstand, der Aufsichtsrat überwacht und bestellt den Vorstand, und die Hauptversammlung entscheidet u. a. über Satzungsänderungen und Gewinnverwendung."),
        .choice(id: "unt-c10", topic: .unternehmen,
                prompt: "Wie haften die Aktionäre einer AG für Verbindlichkeiten des Unternehmens?",
                options: ["Sie haften nicht persönlich, nur das Gesellschaftsvermögen haftet.", "Sie haften unbeschränkt mit ihrem Privatvermögen.", "Sie haften nur, wenn sie im Vorstand sitzen.", "Sie haften gesamtschuldnerisch wie bei einer OHG.", "Sie haften mit dem Doppelten ihres Aktienwerts."],
                explanation: "Aktionäre haften nicht persönlich; für Verbindlichkeiten der AG haftet nur das Gesellschaftsvermögen."),
        .choice(id: "unt-c11", topic: .unternehmen,
                prompt: "Was ist das Besondere an einer GmbH & Co. KG?",
                options: ["Der persönlich haftende Komplementär ist selbst eine GmbH.", "Es gibt keinen Komplementär.", "Alle Gesellschafter haften unbeschränkt.", "Sie ist keine Personengesellschaft.", "Sie braucht kein Stammkapital."],
                explanation: "Bei der GmbH & Co. KG übernimmt eine GmbH die Rolle des unbeschränkt haftenden Komplementärs, sodass keine natürliche Person unbeschränkt haftet."),
        .choice(id: "unt-c12", topic: .unternehmen,
                prompt: "Was ist der Hauptzweck einer eingetragenen Genossenschaft (eG)?",
                options: ["Die Förderung ihrer Mitglieder.", "Ausschließlich die Gewinnmaximierung für externe Investoren.", "Der Verkauf von Aktien an der Börse.", "Die Vermeidung jeglicher Mitgliederbeteiligung.", "Die Bündelung von Kapital ohne Mitspracherecht der Mitglieder."],
                explanation: "Zweck der Genossenschaft ist die Förderung ihrer Mitglieder; jedes Mitglied hat unabhängig von seiner Kapitalbeteiligung eine Stimme."),
        .choice(id: "unt-c13", topic: .unternehmen,
                prompt: "In welcher Abteilung des Handelsregisters werden Einzelkaufleute und Personengesellschaften eingetragen?",
                options: ["Abteilung A.", "Abteilung B.", "Abteilung C.", "Sie werden gar nicht eingetragen.", "Nur im Gesellschaftsregister."],
                explanation: "Abteilung A erfasst Einzelkaufleute und Personengesellschaften, Abteilung B Kapitalgesellschaften."),
        .choice(id: "unt-c14", topic: .unternehmen,
                prompt: "Wer führt das Handelsregister?",
                options: ["Das Amtsgericht (Registergericht).", "Die IHK.", "Das Finanzamt.", "Das Gewerbeamt.", "Das Bundeskartellamt."],
                explanation: "Das Handelsregister wird elektronisch beim zuständigen Amtsgericht als Registergericht geführt."),
        .choice(id: "unt-c15", topic: .unternehmen,
                prompt: "Woran erkennt man in einer Unterschrift die Prokura?",
                options: ["An dem Zusatz „ppa.“ vor dem Namen.", "An dem Zusatz „i. V.“ vor dem Namen.", "An dem Zusatz „i. A.“ vor dem Namen.", "An einer gesonderten notariellen Urkunde bei jeder Unterschrift.", "Prokura wird nie in der Unterschrift kenntlich gemacht."],
                explanation: "Prokuristen zeichnen mit dem Zusatz „ppa.“ (per procura); i. V. und i. A. kennzeichnen dagegen die Handlungsvollmacht."),
        .choice(id: "unt-c16", topic: .unternehmen,
                prompt: "Welches Geschäft darf ein Prokurist NICHT ohne besondere Befugnis vornehmen?",
                options: ["Ein Grundstück des Unternehmens veräußern.", "Waren im normalen Geschäftsbetrieb einkaufen.", "Verträge mit Lieferanten abschließen.", "Rechnungen im Tagesgeschäft unterschreiben.", "Kunden Rabatte im üblichen Rahmen gewähren."],
                explanation: "Die Prokura umfasst alle gerichtlichen und außergerichtlichen Geschäfte eines Handelsgewerbes, aber Grundstücksgeschäfte sind ohne ausdrückliche besondere Befugnis ausgenommen."),
        .choice(id: "unt-c17", topic: .unternehmen,
                prompt: "Mit welchem Zusatz zeichnet ein Mitarbeiter typischerweise mit allgemeiner Handlungsvollmacht nach § 54 HGB?",
                options: ["„i. V.“ (in Vertretung).", "„ppa.“ (per procura).", "Ausschließlich „i. A.“ (im Auftrag).", "Ohne jeden Zusatz.", "Mit dem Firmenstempel allein."],
                explanation: "Die allgemeine Handlungsvollmacht wird typischerweise mit „i. V.“ gezeichnet, Art- und Einzelvollmachten eher mit „i. A.“."),
        .choice(id: "unt-c18", topic: .unternehmen,
                prompt: "Ein Landwirtschaftsbetrieb, der Getreide anbaut, gehört zu welchem Wirtschaftssektor?",
                options: ["Primärer Sektor.", "Sekundärer Sektor.", "Tertiärer Sektor.", "Quartärer Sektor.", "Er gehört keinem Sektor an."],
                explanation: "Der primäre Sektor umfasst die Urproduktion wie Land- und Forstwirtschaft, Fischerei und Bergbau."),
        .choice(id: "unt-c19", topic: .unternehmen,
                prompt: "Ein Unternehmen investiert in Umweltschutz, was kurzfristig den Gewinn senkt. Welche Zielbeziehung liegt hier vor?",
                options: ["Konkurrierende Zielbeziehung.", "Komplementäre Zielbeziehung.", "Indifferente Zielbeziehung.", "Es gibt keine Zielbeziehung.", "Neutrale Zielbeziehung ohne jede Wirkung."],
                explanation: "Umweltschutz und kurzfristige Gewinnmaximierung beeinträchtigen sich hier gegenseitig – das ist eine konkurrierende Zielbeziehung."),
        .choice(id: "unt-c20", topic: .unternehmen,
                prompt: "Wie wird die Kennzahl Wirtschaftlichkeit berechnet?",
                options: ["Ertrag geteilt durch Aufwand.", "Gewinn mal 100 geteilt durch Umsatz.", "Ausbringungsmenge geteilt durch Einsatzmenge.", "Gewinn mal 100 geteilt durch Eigenkapital.", "Umsatz geteilt durch Gewinn."],
                explanation: "Wirtschaftlichkeit = Ertrag / Aufwand; ein Wert über 1 zeigt wirtschaftliches Handeln an."),
        .choice(id: "unt-c21", topic: .unternehmen,
                prompt: "Zwei IT-Systemhäuser aus derselben Branche und Wirtschaftsstufe schließen sich zusammen. Um welche Art des Zusammenschlusses handelt es sich?",
                options: ["Horizontal.", "Vertikal.", "Diagonal.", "Ein Konglomerat auf verschiedenen Stufen.", "Es handelt sich um keinen Zusammenschluss."],
                explanation: "Ein Zusammenschluss von Unternehmen derselben Branche und Wirtschaftsstufe ist horizontal."),
        .choice(id: "unt-c22", topic: .unternehmen,
                prompt: "Zwei Unternehmen vereinbaren, in einer Region einheitliche Preise zu verlangen. Wie wird diese Absprache rechtlich bewertet?",
                options: ["Sie ist ein Kartell und grundsätzlich nach dem GWB verboten.", "Sie ist eine zulässige Arbeitsgemeinschaft (ARGE).", "Sie ist ein normaler Fusionsvorgang.", "Sie ist steuerlich begünstigt.", "Sie ist nur bei Kapitalgesellschaften verboten."],
                explanation: "Preisabsprachen sind Kartellabsprachen und nach dem Gesetz gegen Wettbewerbsbeschränkungen (GWB) grundsätzlich verboten; das Bundeskartellamt überwacht dies."),
        .choice(id: "unt-c23", topic: .unternehmen,
                prompt: "Welche Aufgabe hat ein Stab im Stabliniensystem?",
                options: ["Er berät die Linie, hat aber keine Weisungsbefugnis.", "Er trifft alle operativen Entscheidungen selbst.", "Er ersetzt die Geschäftsführung.", "Er ist der obersten Instanz gegenüber weisungsbefugt.", "Er führt eigene Abteilungen mit Personalverantwortung."],
                explanation: "Ein Stab unterstützt und berät die Linieninstanz, hat aber selbst keine Weisungsbefugnis gegenüber anderen Stellen."),
        .choice(id: "unt-c24", topic: .unternehmen,
                prompt: "Wo meldet ein Gründer sein neues Unternehmen zuerst an?",
                options: ["Beim Gewerbeamt.", "Bei der Agentur für Arbeit.", "Beim Bundeskartellamt.", "Beim Statistischen Bundesamt.", "Beim Betriebsrat."],
                explanation: "Eine Gewerbeanmeldung erfolgt beim örtlichen Gewerbeamt; IHK und Finanzamt werden daraufhin automatisch informiert."),

        // MARK: Statement
        .statement(id: "unt-s01", topic: .unternehmen,
                   text: "Beim Einzelunternehmen haftet der Inhaber unbeschränkt mit seinem gesamten Vermögen.",
                   isTrue: true,
                   explanation: "Der Einzelunternehmer trägt das volle unternehmerische Risiko und haftet mit Privat- und Betriebsvermögen."),
        .statement(id: "unt-s02", topic: .unternehmen,
                   text: "Bei der GmbH haften die Gesellschafter immer auch mit ihrem Privatvermögen.",
                   isTrue: false,
                   explanation: "Für Verbindlichkeiten der GmbH haftet grundsätzlich nur das Gesellschaftsvermögen, nicht das Privatvermögen der Gesellschafter."),
        .statement(id: "unt-s03", topic: .unternehmen,
                   text: "Die OHG kann nur von Kaufleuten gegründet werden, die gemeinsam ein Handelsgewerbe betreiben.",
                   isTrue: true,
                   explanation: "Die OHG ist eine Personengesellschaft von Kaufleuten, die unter gemeinsamer Firma ein Handelsgewerbe betreiben."),
        .statement(id: "unt-s04", topic: .unternehmen,
                   text: "Ein Kommanditist darf die laufenden Geschäfte der KG führen.",
                   isTrue: false,
                   explanation: "Der Kommanditist ist von der Geschäftsführung ausgeschlossen; diese obliegt dem Komplementär."),
        .statement(id: "unt-s05", topic: .unternehmen,
                   text: "Das Mindeststammkapital einer GmbH beträgt 25.000 €, wovon bei der Gründung mindestens 12.500 € eingezahlt sein müssen.",
                   isTrue: true,
                   explanation: "Das GmbH-Stammkapital muss mindestens 25.000 € betragen, bei Gründung sind mindestens 12.500 € einzuzahlen."),
        .statement(id: "unt-s06", topic: .unternehmen,
                   text: "Eine UG (haftungsbeschränkt) kann bereits mit einem Stammkapital von 1 € gegründet werden, muss aber Gewinne unbegrenzt zurücklegen.",
                   isTrue: false,
                   explanation: "Die UG muss nur so lange 25 % ihres Jahresüberschusses in die Rücklage einstellen, bis das GmbH-Mindeststammkapital von 25.000 € erreicht ist – nicht unbegrenzt."),
        .statement(id: "unt-s07", topic: .unternehmen,
                   text: "Bei der Aktiengesellschaft bestellt der Aufsichtsrat den Vorstand und überwacht ihn.",
                   isTrue: true,
                   explanation: "Der Aufsichtsrat bestellt und kontrolliert den Vorstand; der Vorstand leitet das operative Geschäft."),
        .statement(id: "unt-s08", topic: .unternehmen,
                   text: "Das Handelsregister ist nicht öffentlich einsehbar und dient nur internen Zwecken der Kaufleute.",
                   isTrue: false,
                   explanation: "Das Handelsregister ist ein öffentliches Verzeichnis, in das jeder Einsicht nehmen kann, z. B. über handelsregister.de."),
        .statement(id: "unt-s09", topic: .unternehmen,
                   text: "Die Eintragung einer GmbH ins Handelsregister wirkt konstitutiv, das heißt, die GmbH entsteht erst durch die Eintragung.",
                   isTrue: true,
                   explanation: "Bei Kapitalgesellschaften wie der GmbH ist die Handelsregistereintragung konstitutiv; die Gesellschaft entsteht erst dadurch."),
        .statement(id: "unt-s10", topic: .unternehmen,
                   text: "Prokura kann von jedem beliebigen Mitarbeiter erteilt werden.",
                   isTrue: false,
                   explanation: "Prokura kann nur vom Kaufmann selbst oder seinem gesetzlichen Vertreter ausdrücklich erteilt werden."),
        .statement(id: "unt-s11", topic: .unternehmen,
                   text: "Eine Handlungsvollmacht muss nicht ins Handelsregister eingetragen werden.",
                   isTrue: true,
                   explanation: "Im Gegensatz zur Prokura ist die Handlungsvollmacht formfrei und wird nicht im Handelsregister eingetragen."),
        .statement(id: "unt-s12", topic: .unternehmen,
                   text: "Der tertiäre Sektor umfasst vor allem die Landwirtschaft und den Bergbau.",
                   isTrue: false,
                   explanation: "Landwirtschaft und Bergbau gehören zum primären Sektor; der tertiäre Sektor umfasst Dienstleistungen."),
        .statement(id: "unt-s13", topic: .unternehmen,
                   text: "Ein horizontaler Zusammenschluss verbindet Unternehmen derselben Branche und Wirtschaftsstufe.",
                   isTrue: true,
                   explanation: "Horizontale Zusammenschlüsse verbinden Unternehmen der gleichen Branche und Wirtschaftsstufe, z. B. zwei Wettbewerber."),
        .statement(id: "unt-s14", topic: .unternehmen,
                   text: "Bei einer Fusion bleiben immer alle beteiligten Unternehmen rechtlich vollständig selbstständig.",
                   isTrue: false,
                   explanation: "Bei einer Fusion (Verschmelzung) verliert mindestens ein beteiligtes Unternehmen seine rechtliche Selbstständigkeit."),
        .statement(id: "unt-s15", topic: .unternehmen,
                   text: "Die IHK ist für Gewerbetreibende eine Pflichtmitgliedschaft, für Handwerksbetriebe ist dagegen die Handwerkskammer zuständig.",
                   isTrue: true,
                   explanation: "Gewerbetreibende sind grundsätzlich Pflichtmitglied der IHK, Handwerksbetriebe der Handwerkskammer (HWK)."),

        // MARK: Multiple
        .multiple(id: "unt-m01", topic: .unternehmen,
                  prompt: "Wähle alle zutreffenden Aussagen zur GmbH aus.",
                  correct: ["Sie ist eine juristische Person.", "Ihr Gesellschaftsvertrag muss notariell beurkundet werden.", "Sie entsteht mit der Eintragung ins Handelsregister."],
                  wrong: ["Die Gesellschafter haften immer unbeschränkt mit ihrem Privatvermögen.", "Ein Mindeststammkapital ist nicht erforderlich.", "Sie kann formfrei mündlich gegründet werden."],
                  explanation: "Die GmbH ist eine juristische Person mit notariellem Gesellschaftsvertrag, die erst mit der Handelsregistereintragung entsteht; die Haftung ist auf das Gesellschaftsvermögen beschränkt."),
        .multiple(id: "unt-m02", topic: .unternehmen,
                  prompt: "Wähle alle Merkmale aus, die auf die Prokura zutreffen.",
                  correct: ["Sie kann nur von einem Kaufmann oder dessen gesetzlichem Vertreter erteilt werden.", "Sie wird ins Handelsregister eingetragen.", "Sie umfasst grundsätzlich alle Geschäfte eines Handelsgewerbes.", "Sie wird mit dem Zusatz „ppa.“ gezeichnet."],
                  wrong: ["Sie erlaubt ohne Weiteres den Verkauf von Grundstücken.", "Sie erlaubt, selbst weitere Prokura zu erteilen.", "Sie muss nicht ins Handelsregister eingetragen werden."],
                  explanation: "Prokura wird nur vom Kaufmann oder seinem gesetzlichen Vertreter erteilt, ins Handelsregister eingetragen, mit „ppa.“ gezeichnet und umfasst grundsätzlich alle Geschäfte des Betriebs – außer bestimmten Ausnahmen wie Grundstücksgeschäften."),
        .multiple(id: "unt-m03", topic: .unternehmen,
                  prompt: "Welche Rechtsformen sind Kapitalgesellschaften (juristische Personen)? Wähle alle zutreffenden aus.",
                  correct: ["GmbH", "AG", "UG (haftungsbeschränkt)"],
                  wrong: ["Einzelunternehmen", "OHG", "GbR", "KG"],
                  explanation: "GmbH, AG und UG (haftungsbeschränkt) sind Kapitalgesellschaften und damit juristische Personen; Einzelunternehmen, OHG, GbR und KG sind Personen(gesellschaften)."),
        .multiple(id: "unt-m04", topic: .unternehmen,
                  prompt: "Wähle alle Merkmale aus, die einen Kartell-Zusammenschluss (Kooperation) kennzeichnen.",
                  correct: ["Die beteiligten Unternehmen bleiben rechtlich und wirtschaftlich weitgehend selbstständig.", "Preis- oder Gebietsabsprachen sind grundsätzlich verboten.", "Das Bundeskartellamt überwacht solche Absprachen."],
                  wrong: ["Mindestens ein Unternehmen verliert seine rechtliche Selbstständigkeit.", "Es entsteht automatisch ein Konzern.", "Solche Absprachen sind immer erlaubt, wenn sie schriftlich fixiert sind."],
                  explanation: "Ein Kartell ist eine Kooperationsform, bei der die Beteiligten selbstständig bleiben; Preis- und Gebietsabsprachen sind nach dem GWB grundsätzlich verboten und werden vom Bundeskartellamt überwacht."),

        // MARK: Match
        .match(id: "unt-p01", topic: .unternehmen,
               prompt: "Ordne den Fall der passenden Zusammenschlussform zu.",
               pairs: [
                ("Zwei Bäckereiketten aus derselben Region schließen sich zusammen.", "Horizontaler Zusammenschluss"),
                ("Ein Möbelhersteller übernimmt seinen Holzlieferanten.", "Vertikaler Zusammenschluss"),
                ("Ein Lebensmittelkonzern kauft eine Softwarefirma.", "Diagonaler Zusammenschluss"),
                ("Mehrere Baufirmen bilden für ein gemeinsames Bauprojekt ein befristetes Bündnis.", "Arbeitsgemeinschaft (ARGE)"),
                ("Ein Unternehmen übernimmt ein anderes vollständig, das dadurch seine Rechtsfähigkeit verliert.", "Fusion")
               ],
               extra: ["Kartell", "Joint Venture"],
               explanation: "Horizontal = gleiche Branche/Stufe, vertikal = vor-/nachgelagerte Stufe, diagonal = branchenfremd; die ARGE ist eine befristete Projektkooperation, die Fusion eine Verschmelzung mit Verlust der Rechtsfähigkeit."),
        .match(id: "unt-p02", topic: .unternehmen,
               prompt: "Ordne das Unternehmen dem passenden Wirtschaftssektor zu.",
               pairs: [
                ("Ein Fischereibetrieb an der Nordsee.", "Primärer Sektor"),
                ("Eine Möbelfabrik.", "Sekundärer Sektor"),
                ("Eine Versicherungsgesellschaft.", "Tertiärer Sektor"),
                ("Ein Bauunternehmen.", "Sekundärer Sektor"),
                ("Ein IT-Dienstleister für Kundensupport.", "Tertiärer Sektor")
               ],
               extra: ["Quartärer Sektor"],
               explanation: "Primär = Urproduktion, sekundär = Weiterverarbeitung/Industrie/Bau, tertiär = Dienstleistungen."),
        .match(id: "unt-p03", topic: .unternehmen,
               prompt: "Ordne die Rechtsform der passenden Haftungsregel zu.",
               pairs: [
                ("Einzelunternehmen", "Inhaber haftet unbeschränkt mit dem Privatvermögen"),
                ("GmbH", "Haftung beschränkt auf das Gesellschaftsvermögen"),
                ("OHG", "Alle Gesellschafter haften unbeschränkt und gesamtschuldnerisch"),
                ("KG (Kommanditist)", "Haftung nur bis zur Höhe der Einlage"),
                ("AG", "Aktionäre haften nicht persönlich")
               ],
               extra: ["Haftung ausschließlich der Geschäftsführung"],
               explanation: "Die Haftung unterscheidet sich stark nach Rechtsform: von unbeschränkter persönlicher Haftung bis zur reinen Kapitalhaftung."),
        .match(id: "unt-p04", topic: .unternehmen,
               prompt: "Ordne den Vollmachtstyp der passenden Zeichnung zu.",
               pairs: [
                ("Prokura", "ppa."),
                ("Allgemeine Handlungsvollmacht", "i. V."),
                ("Art- oder Einzelvollmacht", "i. A.")
               ],
               extra: ["ohne besonderen Zusatz", "notariell beglaubigt"],
               explanation: "Prokuristen zeichnen mit „ppa.“, allgemeine Handlungsvollmacht typischerweise mit „i. V.“, Art- und Einzelvollmacht mit „i. A.“."),
        .match(id: "unt-p05", topic: .unternehmen,
               prompt: "Ordne die Abteilung des Unternehmens der passenden Aufgabe zu.",
               pairs: [
                ("Beschaffung", "Einkauf von Rohstoffen und Waren"),
                ("Produktion", "Herstellung der Güter inklusive Qualitätssicherung"),
                ("Absatz/Vertrieb", "Verkauf der Produkte an Kunden"),
                ("Verwaltung", "Personal- und Rechnungswesen"),
                ("Logistik", "Planung und Steuerung von Material- und Informationsfluss")
               ],
               extra: ["Forschung und Entwicklung"],
               explanation: "Diese Kernabteilungen bilden die typische Aufbauorganisation eines Unternehmens; Logistik verbindet den Material- und Informationsfluss von der Beschaffung bis zur Auslieferung."),

        // MARK: Order
        .order(id: "unt-o01", topic: .unternehmen,
               prompt: "Bringe die Schritte einer typischen GmbH-Gründung in die richtige Reihenfolge.",
               steps: [
                "Geschäftsidee entwickeln und Gesellschaftsvertrag entwerfen",
                "Gesellschaftsvertrag notariell beurkunden lassen",
                "Stammkapital auf ein Geschäftskonto einzahlen",
                "Eintragung ins Handelsregister beantragen",
                "Gewerbe beim Gewerbeamt anmelden"
               ],
               explanation: "Erst wird der Vertrag notariell beurkundet, dann das Kapital eingezahlt und die Eintragung ins Handelsregister beantragt; erst danach folgt die Gewerbeanmeldung der GmbH."),
        .order(id: "unt-o02", topic: .unternehmen,
               prompt: "Bringe den Ablauf eines Unternehmenszusammenschlusses durch Fusion in die richtige Reihenfolge.",
               steps: [
                "Beide Unternehmen prüfen strategische Gründe für einen Zusammenschluss",
                "Verhandlungen über die Bedingungen der Fusion",
                "Anmeldung der Fusion beim Bundeskartellamt zur Fusionskontrolle",
                "Freigabe durch das Bundeskartellamt",
                "Eintragung der Verschmelzung ins Handelsregister"
               ],
               explanation: "Vor der eigentlichen Verschmelzung muss die Fusion beim Bundeskartellamt angemeldet und freigegeben werden; erst danach wird sie ins Handelsregister eingetragen."),

        // MARK: Gap
        .gap(id: "unt-g01", topic: .unternehmen, title: "Rechtsformen",
             sentences: [
                ("Beim Einzelunternehmen haftet der Inhaber ___ mit seinem gesamten Vermögen.", "unbeschränkt"),
                ("Die GmbH ist eine ___ Person und haftet mit dem Gesellschaftsvermögen.", "juristische"),
                ("Der Kommanditist einer KG haftet nur bis zur Höhe seiner ___.", "Einlage"),
                ("Bei der AG bestellt der ___ den Vorstand und überwacht ihn.", "Aufsichtsrat")
             ],
             extra: ["beschränkt", "natürliche"],
             explanation: "Die Sätze fassen die wichtigsten Haftungs- und Organisationsmerkmale der behandelten Rechtsformen zusammen."),
        .gap(id: "unt-g02", topic: .unternehmen, title: "Vollmachten und Handelsregister",
             sentences: [
                ("Ein Prokurist zeichnet mit dem Zusatz „___“.", "ppa."),
                ("Die Prokura wird im ___ eingetragen.", "Handelsregister"),
                ("Die Handlungsvollmacht ist im Gegensatz zur Prokura ___.", "formfrei"),
                ("Grundstücksgeschäfte darf ein Prokurist ohne besondere Befugnis nicht ___.", "vornehmen")
             ],
             extra: ["i. V.", "notariell"],
             explanation: "Prokura ist an das Handelsregister gebunden und mit „ppa.“ gekennzeichnet; die Handlungsvollmacht ist formfrei und wird dort nicht eingetragen."),

        // MARK: Fact
        .fact(id: "unt-f01", topic: .unternehmen, group: ExamCatalog.Group.betrag,
              question: "Wie hoch ist das gesetzliche Mindeststammkapital einer GmbH?",
              answer: "25.000 €",
              explanation: "Das GmbH-Gesetz schreibt ein Mindeststammkapital von 25.000 € vor."),
        .fact(id: "unt-f02", topic: .unternehmen, group: ExamCatalog.Group.betrag,
              question: "Welcher Betrag des GmbH-Stammkapitals muss bei der Gründung mindestens eingezahlt sein?",
              answer: "12.500 €",
              explanation: "Bei der Gründung müssen mindestens 12.500 € des Stammkapitals eingezahlt sein, also die Hälfte der 25.000 €."),
        .fact(id: "unt-f03", topic: .unternehmen, group: ExamCatalog.Group.betrag,
              question: "Wie hoch ist das Mindestgrundkapital einer Aktiengesellschaft?",
              answer: "50.000 €",
              explanation: "Das Aktiengesetz verlangt ein Grundkapital von mindestens 50.000 €."),
        .fact(id: "unt-f04", topic: .unternehmen, group: ExamCatalog.Group.betrag,
              question: "Ab welchem Stammkapital kann eine UG (haftungsbeschränkt) gegründet werden?",
              answer: "1 €",
              explanation: "Die UG (haftungsbeschränkt) kann bereits mit einem symbolischen Stammkapital von 1 € gegründet werden."),
        .fact(id: "unt-f05", topic: .unternehmen, group: ExamCatalog.Group.prozent,
              question: "Welchen Anteil ihres Jahresüberschusses muss eine UG (haftungsbeschränkt) in die gesetzliche Rücklage einstellen, bis 25.000 € erreicht sind?",
              answer: "25 %",
              explanation: "Die UG muss 25 % ihres Jahresüberschusses zurücklegen, bis das GmbH-Mindeststammkapital von 25.000 € erreicht ist."),
        .fact(id: "unt-f06", topic: .unternehmen, group: ExamCatalog.Group.zeitraum,
              question: "Für wie viele Monate zahlt die Agentur für Arbeit bei Insolvenz des Arbeitgebers rückständigen Lohn als Insolvenzgeld?",
              answer: "3 Monate",
              explanation: "Das Insolvenzgeld deckt bis zu 3 Monate rückständigen Lohn vor der Eröffnung des Insolvenzverfahrens ab."),
        .fact(id: "unt-f07", topic: .unternehmen, group: ExamCatalog.Group.stelle,
              question: "Welches Gericht führt das Handelsregister?",
              answer: "Amtsgericht",
              explanation: "Das Handelsregister wird elektronisch beim zuständigen Amtsgericht (Registergericht) geführt."),
        .fact(id: "unt-f08", topic: .unternehmen, group: ExamCatalog.Group.stelle,
              question: "Welche Behörde kontrolliert Unternehmenszusammenschlüsse in Deutschland (Fusionskontrolle)?",
              answer: "Bundeskartellamt",
              explanation: "Das Bundeskartellamt prüft Fusionen und größere Zusammenschlüsse, ggf. gemeinsam mit der EU-Kommission."),
        .fact(id: "unt-f09", topic: .unternehmen, group: ExamCatalog.Group.anzahl,
              question: "In wie viele Hauptsektoren wird die Wirtschaft üblicherweise eingeteilt (primär, sekundär, tertiär)?",
              answer: "3",
              explanation: "Die klassische Einteilung unterscheidet primären, sekundären und tertiären Sektor – also 3 Sektoren.")
    ]

    static let recht: [ExamCard] = [
        // MARK: Choice
        .choice(id: "rec-c01", topic: .recht,
                prompt: "Jan wird geboren. Ab wann ist er rechtsfähig?",
                options: ["Mit der Vollendung der Geburt.", "Erst mit Vollendung des 7. Lebensjahres.", "Erst mit der Einschulung.", "Erst mit Vollendung des 18. Lebensjahres.", "Erst mit der Meldung beim Standesamt."],
                explanation: "Natürliche Personen sind rechtsfähig mit der Vollendung der Geburt (§ 1 BGB)."),
        .choice(id: "rec-c02", topic: .recht,
                prompt: "Die sechsjährige Lina kauft im Supermarkt allein einen Schokoriegel. Wie ist ihre Willenserklärung einzuordnen?",
                options: ["Nichtig, weil Lina geschäftsunfähig ist.", "Wirksam, weil sie eigenes Taschengeld verwendet.", "Schwebend unwirksam bis zur Genehmigung der Eltern.", "Wirksam, weil es sich um ein Geschäft des täglichen Lebens handelt.", "Anfechtbar wegen Irrtums."],
                explanation: "Kinder unter 7 Jahren sind geschäftsunfähig; ihre Willenserklärungen sind nichtig (§ 104, § 105 BGB)."),
        .choice(id: "rec-c03", topic: .recht,
                prompt: "Der 14-jährige Timo kauft sich von seinem gesparten Taschengeld sofort ein Videospiel im Laden. Wie ist der Kauf zu bewerten?",
                options: ["Wirksam nach dem Taschengeldparagrafen (§ 110 BGB), da er mit eigenen Mitteln sofort bezahlt hat.", "Schwebend unwirksam, weil Minderjährige nie allein kaufen dürfen.", "Nichtig, weil Timo geschäftsunfähig ist.", "Nur wirksam, wenn seine Eltern daneben stehen.", "Wirksam nur bei Ratenzahlung."],
                explanation: "Der Taschengeldparagraf macht Verträge Minderjähriger wirksam, wenn diese mit eigenen, ihnen überlassenen Mitteln sofort erfüllt werden – Ratenkäufe fallen nicht darunter."),
        .choice(id: "rec-c04", topic: .recht,
                prompt: "Die 16-jährige Sema schließt ohne Zustimmung ihrer Eltern einen Handyvertrag mit monatlicher Zahlungspflicht ab. Wie ist dieser Vertrag einzuordnen?",
                options: ["Schwebend unwirksam, bis die Eltern zustimmen oder genehmigen.", "Sofort wirksam, weil Sema schon 16 ist.", "Nichtig, weil Sema geschäftsunfähig ist.", "Wirksam nach dem Taschengeldparagrafen, da es sich um eine laufende Zahlung handelt.", "Unwirksam ohne jede Möglichkeit der Genehmigung."],
                explanation: "Beschränkt Geschäftsfähige (7 bis unter 18 Jahre) benötigen für nicht lediglich rechtlich vorteilhafte Verträge die Einwilligung oder Genehmigung des gesetzlichen Vertreters; bis dahin ist der Vertrag schwebend unwirksam."),
        .choice(id: "rec-c05", topic: .recht,
                prompt: "Wie viel Zeit hat der gesetzliche Vertreter nach Aufforderung durch den Vertragspartner, einen schwebend unwirksamen Vertrag zu genehmigen?",
                options: ["2 Wochen.", "1 Woche.", "1 Monat.", "6 Monate.", "3 Tage."],
                explanation: "Nach Aufforderung hat der gesetzliche Vertreter 2 Wochen Zeit zur Genehmigung; Schweigen gilt als Verweigerung."),
        .choice(id: "rec-c06", topic: .recht,
                prompt: "Was passiert, wenn der gesetzliche Vertreter innerhalb der Frist nicht reagiert?",
                options: ["Die Genehmigung gilt als verweigert.", "Die Genehmigung gilt automatisch als erteilt.", "Der Vertrag wird ohne Weiteres von Anfang an nichtig.", "Die Frist verlängert sich automatisch um weitere 2 Wochen.", "Der Minderjährige muss selbst vor Gericht entscheiden."],
                explanation: "Schweigen des gesetzlichen Vertreters nach Aufforderung gilt als Verweigerung der Genehmigung."),
        .choice(id: "rec-c07", topic: .recht,
                prompt: "Welche Willenserklärung ist grundsätzlich nicht empfangsbedürftig?",
                options: ["Ein Testament.", "Ein Angebot zum Vertragsschluss.", "Eine Kündigung.", "Eine Anfechtungserklärung.", "Ein Rücktritt vom Vertrag."],
                explanation: "Das Testament ist eine nicht empfangsbedürftige Willenserklärung; Angebot, Kündigung, Anfechtung und Rücktritt sind dagegen empfangsbedürftig."),
        .choice(id: "rec-c08", topic: .recht,
                prompt: "Welches der folgenden ist ein einseitiges Rechtsgeschäft?",
                options: ["Die Kündigung eines Vertrags.", "Der Abschluss eines Kaufvertrags.", "Der Abschluss eines Mietvertrags.", "Der Abschluss eines Arbeitsvertrags.", "Der Abschluss eines Leasingvertrags."],
                explanation: "Die Kündigung ist ein einseitiges Rechtsgeschäft; Verträge wie Kauf-, Miet-, Arbeits- oder Leasingverträge sind mehrseitige Rechtsgeschäfte."),
        .choice(id: "rec-c09", topic: .recht,
                prompt: "Ein Onlineshop zeigt ein Produkt mit Preis auf seiner Webseite an. Wie ist diese Darstellung rechtlich einzuordnen?",
                options: ["Als Aufforderung zur Abgabe eines Angebots, nicht als Angebot selbst.", "Als bindendes Angebot, das der Kunde sofort annehmen kann.", "Als Vertrag, der mit dem Ansehen der Seite zustande kommt.", "Als Kündigung eines bestehenden Vertrags.", "Als notariell zu beurkundende Erklärung."],
                explanation: "Die Darstellung von Waren im Schaufenster, Katalog oder Webshop ist rechtlich eine Aufforderung zur Abgabe eines Angebots; das Angebot gibt erst der Kunde mit seiner Bestellung ab."),
        .choice(id: "rec-c10", topic: .recht,
                prompt: "Welcher der folgenden Fälle führt zur Nichtigkeit eines Rechtsgeschäfts von Anfang an?",
                options: ["Geschäftsunfähigkeit eines Vertragspartners.", "Ein Irrtum über den Inhalt der Erklärung.", "Arglistige Täuschung durch den Verkäufer.", "Eine widerrechtliche Drohung.", "Ein einfacher Rechenfehler beim Preis."],
                explanation: "Geschäftsunfähigkeit führt zur Nichtigkeit von Anfang an; Irrtum, Täuschung und Drohung machen ein Rechtsgeschäft dagegen nur anfechtbar."),
        .choice(id: "rec-c11", topic: .recht,
                prompt: "Kevin unterschreibt einen Kaufvertrag nur zum Spaß, ohne dass er ihn ernst meint, und der Verkäufer merkt das auch. Wie ist der Vertrag zu bewerten?",
                options: ["Nichtig als Scherzgeschäft.", "Wirksam, da unterschrieben wurde.", "Anfechtbar wegen Irrtums.", "Schwebend unwirksam bis zur Genehmigung.", "Wirksam, aber Kevin muss nicht zahlen."],
                explanation: "Ein erkennbares Scherzgeschäft ist von Anfang an nichtig (§ 118 BGB)."),
        .choice(id: "rec-c12", topic: .recht,
                prompt: "Innerhalb welcher Frist muss die Anfechtung wegen eines Irrtums grundsätzlich erklärt werden?",
                options: ["Unverzüglich, nachdem der Irrtum entdeckt wurde.", "Innerhalb von 3 Jahren.", "Innerhalb von 6 Monaten.", "Innerhalb von 24 Stunden.", "Es gibt keine Frist."],
                explanation: "Die Anfechtung wegen Irrtums muss unverzüglich, also ohne schuldhaftes Zögern, nach Kenntnis des Anfechtungsgrundes erfolgen (§ 121 BGB)."),
        .choice(id: "rec-c13", topic: .recht,
                prompt: "Ein Käufer wird vom Verkäufer bewusst über einen Mangel der Sache belogen, um den Verkauf zu ermöglichen. Welches Recht hat der Käufer?",
                options: ["Er kann den Vertrag wegen arglistiger Täuschung anfechten.", "Der Vertrag ist ohne sein Zutun automatisch nichtig.", "Er hat gar keine Möglichkeit, sich zu wehren.", "Er kann nur den Preis mindern, aber nicht anfechten.", "Er muss den Kauf trotzdem erfüllen."],
                explanation: "Arglistige Täuschung berechtigt zur Anfechtung des Rechtsgeschäfts (§ 123 BGB)."),
        .choice(id: "rec-c14", topic: .recht,
                prompt: "Welche Form ist für die Kündigung eines Arbeitsvertrags zwingend vorgeschrieben?",
                options: ["Schriftform mit eigenhändiger Unterschrift.", "Textform, z. B. per E-Mail.", "Eine mündliche Erklärung genügt.", "Notarielle Beurkundung.", "Öffentliche Beglaubigung."],
                explanation: "Die Kündigung eines Arbeitsverhältnisses erfordert Schriftform; die elektronische Form ist ausdrücklich ausgeschlossen (§ 623 BGB)."),
        .choice(id: "rec-c15", topic: .recht,
                prompt: "Für welches Rechtsgeschäft ist eine notarielle Beurkundung vorgeschrieben?",
                options: ["Der Kauf eines Grundstücks.", "Der Kauf eines Gebrauchtwagens.", "Ein Mietvertrag über eine Wohnung.", "Ein Kaufvertrag im Onlineshop.", "Eine Bürgschaft eines Kaufmanns."],
                explanation: "Grundstückskaufverträge müssen notariell beurkundet werden, ebenso z. B. GmbH-Gesellschaftsverträge oder Schenkungsversprechen."),
        .choice(id: "rec-c16", topic: .recht,
                prompt: "Marc least ein Auto und fährt regelmäßig damit. Ist er Besitzer, Eigentümer oder beides?",
                options: ["Nur Besitzer, denn das Eigentum bleibt beim Leasinggeber.", "Nur Eigentümer, denn er nutzt das Auto.", "Besitzer und Eigentümer zugleich.", "Weder Besitzer noch Eigentümer.", "Er wird erst nach einem Jahr zum Besitzer."],
                explanation: "Leasingnehmer sind Besitzer, aber nicht Eigentümer der geleasten Sache; das Eigentum verbleibt beim Leasinggeber."),
        .choice(id: "rec-c17", topic: .recht,
                prompt: "Ein Dieb entwendet ein Fahrrad und verkauft es an einen gutgläubigen Käufer weiter. Wird der Käufer Eigentümer?",
                options: ["Nein, an gestohlenen Sachen ist ein gutgläubiger Erwerb ausgeschlossen.", "Ja, weil er gutgläubig war und dafür bezahlt hat.", "Ja, aber erst nach einem Jahr Besitzzeit.", "Nein, aber immerhin nach 5 Jahren Besitz.", "Ja, sobald er das Fahrrad ein Jahr besitzt."],
                explanation: "Bei abhandengekommenen (z. B. gestohlenen) Sachen ist ein gutgläubiger Eigentumserwerb grundsätzlich ausgeschlossen (§ 935 BGB)."),
        .choice(id: "rec-c18", topic: .recht,
                prompt: "Wie wird das Eigentum an einer beweglichen Sache, z. B. einem Laptop, übertragen?",
                options: ["Durch Einigung und Übergabe.", "Allein durch Zahlung des Kaufpreises.", "Allein durch mündliche Zusage.", "Durch Grundbucheintrag.", "Durch notarielle Beurkundung."],
                explanation: "Bei beweglichen Sachen erfolgt die Eigentumsübertragung durch Einigung und Übergabe (§ 929 BGB); bei Grundstücken durch Auflassung und Grundbucheintrag."),
        .choice(id: "rec-c19", topic: .recht,
                prompt: "Ein Kunde kauft einen Fernseher auf Raten. Der Händler behält sich das Eigentum bis zur vollständigen Zahlung vor. Was bedeutet das?",
                options: ["Der Kunde wird sofort Besitzer, Eigentümer wird er erst nach vollständiger Zahlung.", "Der Kunde wird nie Besitzer.", "Der Kunde wird sofort Eigentümer.", "Der Händler bleibt für immer Besitzer.", "Der Eigentumsvorbehalt ist unwirksam."],
                explanation: "Beim Eigentumsvorbehalt wird der Käufer sofort Besitzer, das Eigentum geht aber erst mit vollständiger Zahlung über."),
        .choice(id: "rec-c20", topic: .recht,
                prompt: "Welcher Vertragstyp liegt vor, wenn ein Programmierer beauftragt wird, eine funktionsfähige App zu erstellen, und der Erfolg (die fertige App) geschuldet ist?",
                options: ["Werkvertrag.", "Dienstvertrag.", "Mietvertrag.", "Leihvertrag.", "Pachtvertrag."],
                explanation: "Beim Werkvertrag wird ein Erfolg geschuldet, z. B. die Erstellung einer funktionsfähigen App oder eine Reparatur."),
        .choice(id: "rec-c21", topic: .recht,
                prompt: "Ein Kunde kauft ein neues Notebook und entdeckt nach drei Monaten einen Sachmangel. Was muss er zuerst verlangen?",
                options: ["Nacherfüllung (Nachbesserung oder Ersatzlieferung nach seiner Wahl).", "Sofortigen Rücktritt vom Vertrag.", "Sofortige Minderung des Kaufpreises.", "Sofort Schadensersatz.", "Er hat keine Rechte mehr, weil die Frist verpasst wurde."],
                explanation: "Bei einem Sachmangel steht dem Käufer zunächst das Recht auf Nacherfüllung zu; er kann zwischen Nachbesserung und Ersatzlieferung wählen."),
        .choice(id: "rec-c22", topic: .recht,
                prompt: "Wie lange gilt die gesetzliche Gewährleistungsfrist beim Kauf einer neuen Sache durch einen Verbraucher?",
                options: ["2 Jahre.", "6 Monate.", "1 Jahr.", "3 Jahre.", "5 Jahre."],
                explanation: "Die gesetzliche Gewährleistungsfrist beim Verbrauchsgüterkauf beträgt 2 Jahre; bei gebrauchten Sachen kann sie vertraglich auf 1 Jahr verkürzt werden."),
        .choice(id: "rec-c23", topic: .recht,
                prompt: "Worin unterscheidet sich eine Garantie von der gesetzlichen Gewährleistung?",
                options: ["Die Garantie ist eine freiwillige zusätzliche Zusage des Herstellers oder Händlers.", "Die Garantie ist gesetzlich zwingend vorgeschrieben wie die Gewährleistung.", "Die Garantie ersetzt automatisch die Gewährleistung.", "Die Garantie gilt immer kürzer als die Gewährleistung.", "Es gibt rechtlich keinen Unterschied."],
                explanation: "Die Garantie ist eine freiwillige, zusätzliche Zusage; die gesetzliche Gewährleistung besteht unabhängig davon."),
        .choice(id: "rec-c24", topic: .recht,
                prompt: "Innerhalb welcher Frist kann ein Verbraucher einen im Internet geschlossenen Kaufvertrag ohne Angabe von Gründen widerrufen?",
                options: ["14 Tage.", "7 Tage.", "4 Wochen.", "30 Tage.", "3 Jahre."],
                explanation: "Bei Fernabsatzverträgen (z. B. Onlinekauf) hat der Verbraucher ein 14-tägiges Widerrufsrecht ohne Angabe von Gründen."),

        // MARK: Statement
        .statement(id: "rec-s01", topic: .recht,
                   text: "Natürliche Personen sind mit der Vollendung ihrer Geburt rechtsfähig.",
                   isTrue: true,
                   explanation: "Die Rechtsfähigkeit natürlicher Personen beginnt mit der Vollendung der Geburt (§ 1 BGB)."),
        .statement(id: "rec-s02", topic: .recht,
                   text: "Kinder unter 7 Jahren können wirksame Verträge abschließen, wenn ihre Eltern nachträglich zustimmen.",
                   isTrue: false,
                   explanation: "Kinder unter 7 Jahren sind geschäftsunfähig; ihre Willenserklärungen sind nichtig und können nicht durch Zustimmung geheilt werden."),
        .statement(id: "rec-s03", topic: .recht,
                   text: "Verträge beschränkt Geschäftsfähiger, die ihnen lediglich einen rechtlichen Vorteil bringen, sind auch ohne Zustimmung der Eltern wirksam.",
                   isTrue: true,
                   explanation: "Geschäfte, die für Minderjährige lediglich rechtlich vorteilhaft sind, sind ohne Zustimmung des gesetzlichen Vertreters wirksam."),
        .statement(id: "rec-s04", topic: .recht,
                   text: "Der Taschengeldparagraf gilt auch für Ratenkäufe Minderjähriger.",
                   isTrue: false,
                   explanation: "§ 110 BGB gilt nur, wenn die Leistung sofort mit eigenen, überlassenen Mitteln bewirkt wird; Ratenkäufe sind ausgeschlossen."),
        .statement(id: "rec-s05", topic: .recht,
                   text: "Ein Motivirrtum berechtigt nicht zur Anfechtung eines Vertrags.",
                   isTrue: true,
                   explanation: "Ein Irrtum über bloße Beweggründe (Motivirrtum) ist rechtlich unbeachtlich und berechtigt nicht zur Anfechtung."),
        .statement(id: "rec-s06", topic: .recht,
                   text: "Ein Vertrag, der durch arglistige Täuschung zustande gekommen ist, ist automatisch von Anfang an nichtig.",
                   isTrue: false,
                   explanation: "Arglistige Täuschung macht ein Rechtsgeschäft nur anfechtbar; es ist wirksam, bis die Anfechtung erklärt wird."),
        .statement(id: "rec-s07", topic: .recht,
                   text: "Die Darstellung von Waren in einem Onlineshop ist rechtlich eine Aufforderung zur Abgabe eines Angebots, kein bindendes Angebot.",
                   isTrue: true,
                   explanation: "Die Warenpräsentation im Webshop ist eine invitatio ad offerendum; das eigentliche Angebot gibt der Kunde mit der Bestellung ab."),
        .statement(id: "rec-s08", topic: .recht,
                   text: "Ein Testament ist eine empfangsbedürftige Willenserklärung.",
                   isTrue: false,
                   explanation: "Das Testament ist eine nicht empfangsbedürftige Willenserklärung, da kein bestimmter Empfänger nötig ist."),
        .statement(id: "rec-s09", topic: .recht,
                   text: "Für einen Grundstückskaufvertrag ist die notarielle Beurkundung gesetzlich vorgeschrieben.",
                   isTrue: true,
                   explanation: "Grundstückskaufverträge bedürfen zwingend der notariellen Beurkundung."),
        .statement(id: "rec-s10", topic: .recht,
                   text: "Mietverträge müssen grundsätzlich immer notariell beurkundet werden.",
                   isTrue: false,
                   explanation: "Mietverträge sind grundsätzlich formfrei; nur bei einer Laufzeit von mehr als einem Jahr ist Schriftform erforderlich, keine notarielle Beurkundung."),
        .statement(id: "rec-s11", topic: .recht,
                   text: "Ein Mieter ist Besitzer, aber nicht Eigentümer der gemieteten Wohnung.",
                   isTrue: true,
                   explanation: "Der Mieter übt nur die tatsächliche Herrschaft (Besitz) aus, das Eigentum verbleibt beim Vermieter."),
        .statement(id: "rec-s12", topic: .recht,
                   text: "Ein gutgläubiger Käufer kann auch an einer gestohlenen Sache Eigentum erwerben.",
                   isTrue: false,
                   explanation: "An abhandengekommenen Sachen wie gestohlenen Gegenständen ist ein gutgläubiger Erwerb ausgeschlossen (§ 935 BGB)."),
        .statement(id: "rec-s13", topic: .recht,
                   text: "Bei einem Sachmangel hat der Käufer zunächst Anspruch auf Nacherfüllung, bevor er zurücktreten oder mindern kann.",
                   isTrue: true,
                   explanation: "Das Recht auf Nacherfüllung steht vor Rücktritt, Minderung oder Schadensersatz (Vorrang der Nacherfüllung)."),
        .statement(id: "rec-s14", topic: .recht,
                   text: "Die gesetzliche Gewährleistungsfrist bei neuen Sachen beträgt grundsätzlich 1 Jahr.",
                   isTrue: false,
                   explanation: "Bei neuen Sachen beträgt die gesetzliche Gewährleistungsfrist grundsätzlich 2 Jahre; nur bei Gebrauchtwaren kann sie auf 1 Jahr verkürzt werden."),
        .statement(id: "rec-s15", topic: .recht,
                   text: "Das Widerrufsrecht bei Fernabsatzverträgen gilt nicht für den Kauf im Ladengeschäft.",
                   isTrue: true,
                   explanation: "Das 14-tägige Widerrufsrecht gilt nur für Fernabsatz- und Haustürgeschäfte, nicht für den klassischen Ladenkauf."),

        // MARK: Multiple
        .multiple(id: "rec-m01", topic: .recht,
                  prompt: "Wähle alle zutreffenden Aussagen zur Geschäftsfähigkeit aus.",
                  correct: ["Kinder unter 7 Jahren sind geschäftsunfähig.", "Personen zwischen 7 und unter 18 Jahren sind beschränkt geschäftsfähig.", "Ab 18 Jahren besteht volle Geschäftsfähigkeit."],
                  wrong: ["Beschränkt Geschäftsfähige können jeden Vertrag ohne Zustimmung wirksam abschließen.", "Geschäftsunfähigkeit endet automatisch mit dem 14. Geburtstag.", "Geschäftsfähigkeit und Rechtsfähigkeit bedeuten dasselbe."],
                  explanation: "Geschäftsunfähigkeit gilt unter 7 Jahren, beschränkte Geschäftsfähigkeit von 7 bis unter 18 Jahren, ab 18 volle Geschäftsfähigkeit – unabhängig von der Rechtsfähigkeit, die bereits mit der Geburt beginnt."),
        .multiple(id: "rec-m02", topic: .recht,
                  prompt: "Wähle alle Rechtsgeschäfte aus, die einseitig sind.",
                  correct: ["Kündigung", "Testament", "Rücktritt vom Vertrag", "Anfechtung"],
                  wrong: ["Kaufvertrag", "Mietvertrag", "Arbeitsvertrag"],
                  explanation: "Kündigung, Testament, Rücktritt und Anfechtung sind einseitige Rechtsgeschäfte; Kauf-, Miet- und Arbeitsvertrag sind mehrseitige Rechtsgeschäfte."),
        .multiple(id: "rec-m03", topic: .recht,
                  prompt: "Wähle alle Gründe aus, die ein Rechtsgeschäft von Anfang an nichtig machen.",
                  correct: ["Geschäftsunfähigkeit eines Beteiligten.", "Ein Scheingeschäft.", "Ein Verstoß gegen ein gesetzliches Verbot.", "Sittenwidrigkeit (z. B. Wucher)."],
                  wrong: ["Ein Irrtum über den Inhalt der Erklärung.", "Arglistige Täuschung.", "Eine widerrechtliche Drohung."],
                  explanation: "Geschäftsunfähigkeit, Schein- und Scherzgeschäft, gesetzliche Verbote und Sittenwidrigkeit führen zur Nichtigkeit; Irrtum, Täuschung und Drohung machen ein Geschäft dagegen nur anfechtbar."),
        .multiple(id: "rec-m04", topic: .recht,
                  prompt: "Wähle alle Rechte aus, die einem Käufer bei einem Sachmangel grundsätzlich zustehen können.",
                  correct: ["Nacherfüllung durch Nachbesserung oder Ersatzlieferung.", "Rücktritt vom Vertrag.", "Minderung des Kaufpreises.", "Schadensersatz unter bestimmten Voraussetzungen."],
                  wrong: ["Sofortige fristlose Kündigung des Kaufvertrags.", "Automatische Verdoppelung der Garantiezeit.", "Ein Recht auf kostenlosen Ersatzkauf bei jedem beliebigen Händler."],
                  explanation: "Bei einem Sachmangel stehen dem Käufer der Reihe nach Nacherfüllung, dann Rücktritt oder Minderung sowie ggf. Schadensersatz zu."),

        // MARK: Match
        .match(id: "rec-p01", topic: .recht,
               prompt: "Ordne die Situation der passenden Vertragsart zu.",
               pairs: [
                ("Frau Roth kauft sich ein neues Fahrrad im Laden.", "Kaufvertrag"),
                ("Herr Cengiz wohnt zur Miete in einer Wohnung.", "Mietvertrag"),
                ("Ein Landwirt bewirtschaftet ein gepachtetes Feld und behält die Ernte.", "Pachtvertrag"),
                ("Ein Freund leiht sich kostenlos eine Bohrmaschine aus.", "Leihvertrag"),
                ("Ein Unternehmen beauftragt eine Agentur mit der Programmierung einer neuen App.", "Werkvertrag")
               ],
               extra: ["Dienstvertrag", "Schenkung"],
               explanation: "Kauf-, Miet-, Pacht- und Leihvertrag unterscheiden sich in Entgeltlichkeit und Nutzungsart; beim Werkvertrag wird ein Erfolg geschuldet."),
        .match(id: "rec-p02", topic: .recht,
               prompt: "Ordne die Person der Frage zu, ob sie Besitzer, Eigentümer oder beides ist.",
               pairs: [
                ("Ein Mieter in seiner Wohnung.", "Nur Besitzer"),
                ("Ein Käufer, der die Sache bezahlt und übergeben bekommen hat.", "Besitzer und Eigentümer"),
                ("Ein Dieb mit der gestohlenen Sache.", "Nur Besitzer (unrechtmäßig)"),
                ("Ein Käufer unter Eigentumsvorbehalt vor vollständiger Zahlung.", "Nur Besitzer"),
                ("Ein Vermieter, dessen Wohnung vermietet ist.", "Nur Eigentümer")
               ],
               extra: ["Weder Besitzer noch Eigentümer"],
               explanation: "Besitz ist die tatsächliche, Eigentum die rechtliche Herrschaft über eine Sache; beides kann, muss aber nicht zusammenfallen."),
        .match(id: "rec-p03", topic: .recht,
               prompt: "Ordne das Rechtsgeschäft der passenden Formvorschrift zu.",
               pairs: [
                ("Kündigung eines Arbeitsvertrags.", "Schriftform"),
                ("Kauf eines Grundstücks.", "Notarielle Beurkundung"),
                ("Anmeldung ins Handelsregister.", "Öffentliche Beglaubigung"),
                ("Widerrufsbelehrung per E-Mail.", "Textform"),
                ("Kauf eines Buches im Laden.", "Formfrei")
               ],
               extra: ["Mündliche Zeugenaussage"],
               explanation: "Das deutsche Recht kennt gestufte Formvorschriften von Formfreiheit über Text- und Schriftform bis zur notariellen Beurkundung."),
        .match(id: "rec-p04", topic: .recht,
               prompt: "Ordne den Fehler beim Vertragsschluss der passenden Rechtsfolge zu.",
               pairs: [
                ("Geschäftsunfähigkeit eines Vertragspartners.", "Nichtig"),
                ("Ein Irrtum über den Inhalt der Erklärung.", "Anfechtbar"),
                ("Arglistige Täuschung.", "Anfechtbar"),
                ("Ein Scherzgeschäft, das der andere erkennt.", "Nichtig")
               ],
               extra: ["Wirksam ohne Einschränkung", "Schwebend unwirksam"],
               explanation: "Nichtige Rechtsgeschäfte sind von Anfang an unwirksam, anfechtbare erst nach erklärter Anfechtung."),
        .match(id: "rec-p05", topic: .recht,
               prompt: "Ordne den Mangel/Fall der passenden Käuferreaktion nach dem Kaufrecht zu.",
               pairs: [
                ("Ein Sachmangel wird direkt nach dem Kauf entdeckt.", "Zuerst Nacherfüllung verlangen"),
                ("Die Nacherfüllung schlägt fehl oder ist unzumutbar.", "Rücktritt oder Minderung"),
                ("Der Kunde möchte den Mangel behalten, aber weniger zahlen.", "Minderung des Kaufpreises"),
                ("Zusätzlich zum Mangel ist dem Kunden ein Schaden entstanden.", "Schadensersatz")
               ],
               extra: ["Sofortige fristlose Kündigung"],
               explanation: "Das Gewährleistungsrecht sieht eine feste Rangfolge vor: zuerst Nacherfüllung, danach Rücktritt/Minderung, ggf. zusätzlich Schadensersatz."),

        // MARK: Order
        .order(id: "rec-o01", topic: .recht,
               prompt: "Bringe den Ablauf eines Kaufvertrags vom Angebot bis zur Zahlung in die richtige Reihenfolge.",
               steps: [
                "Der Verkäufer stellt Waren im Schaufenster oder Onlineshop aus (Aufforderung zur Angebotsabgabe)",
                "Der Kunde gibt ein verbindliches Angebot ab, z. B. durch die Bestellung",
                "Der Verkäufer nimmt das Angebot an, der Kaufvertrag kommt zustande",
                "Der Verkäufer übergibt die Ware und überträgt das Eigentum (Erfüllungsgeschäft)",
                "Der Kunde zahlt den vereinbarten Kaufpreis"
               ],
               explanation: "Auf die Aufforderung zur Angebotsabgabe folgen Angebot und Annahme (Verpflichtungsgeschäft), danach die Übergabe und die Zahlung (Erfüllungsgeschäfte)."),
        .order(id: "rec-o02", topic: .recht,
               prompt: "Bringe die Rechte eines Käufers bei einem Sachmangel in die richtige Reihenfolge, wie sie geltend gemacht werden.",
               steps: [
                "Käufer entdeckt den Sachmangel und zeigt ihn dem Verkäufer an",
                "Käufer verlangt Nacherfüllung: Nachbesserung oder Ersatzlieferung nach seiner Wahl",
                "Verkäufer versucht die Nacherfüllung innerhalb einer angemessenen Frist",
                "Schlägt die Nacherfüllung fehl, erklärt der Käufer Rücktritt oder Minderung",
                "Bestand zusätzlich ein Schaden, macht der Käufer Schadensersatz geltend"
               ],
               explanation: "Das Gewährleistungsrecht gibt der Nacherfüllung Vorrang vor Rücktritt oder Minderung; Schadensersatz kann zusätzlich verlangt werden."),

        // MARK: Gap
        .gap(id: "rec-g01", topic: .recht, title: "Geschäftsfähigkeit",
             sentences: [
                ("Kinder unter 7 Jahren sind ___.", "geschäftsunfähig"),
                ("Verträge beschränkt Geschäftsfähiger sind bis zur Zustimmung des gesetzlichen Vertreters schwebend ___.", "unwirksam"),
                ("Nach dem Taschengeldparagrafen § 110 BGB ist ein Vertrag wirksam, wenn der Minderjährige mit eigenen Mitteln ___ bezahlt.", "sofort"),
                ("Ab Vollendung des 18. Lebensjahres ist eine Person ___ geschäftsfähig.", "voll")
             ],
             extra: ["nichtig", "beschränkt"],
             explanation: "Die Sätze fassen die drei Stufen der Geschäftsfähigkeit und den Taschengeldparagrafen zusammen."),
        .gap(id: "rec-g02", topic: .recht, title: "Rechtsgeschäfte und Nichtigkeit",
             sentences: [
                ("Ein erkennbares Scherzgeschäft ist von Anfang an ___.", "nichtig"),
                ("Ein Vertrag, der durch arglistige Täuschung zustande kam, ist ___, muss also erst angefochten werden.", "anfechtbar"),
                ("Die Darstellung eines Produkts im Onlineshop ist rechtlich nur eine Aufforderung zur Abgabe eines ___.", "Angebots"),
                ("Ein Irrtum über bloße Beweggründe berechtigt nicht zur ___.", "Anfechtung")
             ],
             extra: ["wirksam", "Rücktritt"],
             explanation: "Nichtigkeit wirkt von Anfang an, Anfechtbarkeit erst durch die Anfechtungserklärung; ein Motivirrtum berechtigt nicht zur Anfechtung."),

        // MARK: Fact
        .fact(id: "rec-f01", topic: .recht, group: ExamCatalog.Group.alter,
              question: "Ab welchem Alter beginnt die beschränkte Geschäftsfähigkeit (bis dahin: Geschäftsunfähigkeit)?",
              answer: "7 Jahre",
              explanation: "Bis zur Vollendung des 7. Lebensjahres ist eine Person geschäftsunfähig; danach beginnt die beschränkte Geschäftsfähigkeit."),
        .fact(id: "rec-f02", topic: .recht, group: ExamCatalog.Group.alter,
              question: "Ab welchem Alter besteht volle Geschäftsfähigkeit?",
              answer: "18 Jahre",
              explanation: "Mit Vollendung des 18. Lebensjahres endet die beschränkte Geschäftsfähigkeit und die volle Geschäftsfähigkeit beginnt."),
        .fact(id: "rec-f03", topic: .recht, group: ExamCatalog.Group.zeitraum,
              question: "Wie viel Zeit hat der gesetzliche Vertreter nach Aufforderung, einen schwebend unwirksamen Vertrag zu genehmigen?",
              answer: "2 Wochen",
              explanation: "Nach Aufforderung durch den Vertragspartner hat der gesetzliche Vertreter 2 Wochen Zeit zur Genehmigung."),
        .fact(id: "rec-f04", topic: .recht, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange gilt die gesetzliche Gewährleistungsfrist beim Kauf einer neuen Sache?",
              answer: "2 Jahre",
              explanation: "Die gesetzliche Gewährleistungsfrist beim Verbrauchsgüterkauf beträgt grundsätzlich 2 Jahre."),
        .fact(id: "rec-f05", topic: .recht, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange gilt beim Verbrauchsgüterkauf die Beweislastumkehr zugunsten des Käufers?",
              answer: "1 Jahr",
              explanation: "Innerhalb des ersten Jahres nach Übergabe wird vermutet, dass ein Mangel bereits bei Übergabe vorlag (Beweislastumkehr)."),
        .fact(id: "rec-f06", topic: .recht, group: ExamCatalog.Group.zeitraum,
              question: "Innerhalb welcher Frist kann ein Verbraucher einen Fernabsatzvertrag ohne Angabe von Gründen widerrufen?",
              answer: "14 Tage",
              explanation: "Das Widerrufsrecht bei Fernabsatz- und Haustürgeschäften beträgt 14 Tage."),
        .fact(id: "rec-f07", topic: .recht, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange beträgt die regelmäßige Verjährungsfrist für Ansprüche nach dem BGB?",
              answer: "3 Jahre",
              explanation: "Die regelmäßige Verjährungsfrist beträgt 3 Jahre ab dem Ende des Jahres, in dem der Anspruch entstanden ist."),
        .fact(id: "rec-f08", topic: .recht, group: ExamCatalog.Group.anzahl,
              question: "Zwischen wie vielen Arten der Nacherfüllung kann der Käufer bei einem Sachmangel wählen?",
              answer: "2",
              explanation: "Der Käufer kann zwischen Nachbesserung und Ersatzlieferung wählen – also zwischen 2 Arten der Nacherfüllung."),
        .fact(id: "rec-f09", topic: .recht, group: ExamCatalog.Group.stelle,
              question: "Wer beurkundet einen Grundstückskaufvertrag?",
              answer: "Notar",
              explanation: "Grundstückskaufverträge müssen von einem Notar beurkundet werden.")
    ]
}
