// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Lino Laske

import Foundation

/// Original practice material for die Themen Ausbildung, Arbeitsrecht und Arbeits-/Jugendschutz.
extension ExamCatalog {
    static let ausbildung: [ExamCard] = [
        .choice(id: "aus-c01", topic: .ausbildung,
                prompt: "Aus welchen beiden Lernorten besteht das duale System der Berufsausbildung?",
                options: ["Ausbildungsbetrieb und Berufsschule", "Berufsschule und Volkshochschule",
                          "Ausbildungsbetrieb und IHK-Prüfstelle", "Betrieb und Universität",
                          "Berufsschule und Arbeitsagentur"],
                explanation: "Die duale Ausbildung findet im Betrieb (praktisch, nach Ausbildungsrahmenplan) und in der Berufsschule (theoretisch, nach Rahmenlehrplan) statt."),
        .choice(id: "aus-c02", topic: .ausbildung,
                prompt: "Welche Institution ist für die meisten IT-Ausbildungsberufe die zuständige Stelle nach dem BBiG?",
                options: ["Die Industrie- und Handelskammer (IHK)", "Die Handwerkskammer",
                          "Die Bundesagentur für Arbeit", "Das zuständige Arbeitsgericht",
                          "Die Kultusministerkonferenz"],
                explanation: "Für kaufmännische und IT-Berufe ist die IHK zuständige Stelle nach dem BBiG; für Handwerksberufe ist es die Handwerkskammer."),
        .choice(id: "aus-c03", topic: .ausbildung,
                prompt: "Welche Aufgabe gehört zu den Pflichten der IHK als zuständige Stelle?",
                options: ["Sie führt das Verzeichnis der Berufsausbildungsverhältnisse.",
                          "Sie erstellt den Rahmenlehrplan der Berufsschule.",
                          "Sie zahlt die Ausbildungsvergütung aus.",
                          "Sie stellt den Arbeitsvertrag der Auszubildenden aus.",
                          "Sie vertritt den Betrieb vor dem Arbeitsgericht."],
                explanation: "Die IHK führt u. a. das Verzeichnis der Berufsausbildungsverhältnisse, überwacht die Ausbildung, berät durch Ausbildungsberater und nimmt die Prüfungen ab."),
        .choice(id: "aus-c04", topic: .ausbildung,
                prompt: "Wer legt den Rahmenlehrplan für die Berufsschule fest?",
                options: ["Die Kultusministerkonferenz (KMK)", "Die IHK", "Der Ausbildungsbetrieb",
                          "Der Prüfungsausschuss", "Die Handwerkskammer"],
                explanation: "Der Rahmenlehrplan für den Berufsschulunterricht wird von der Kultusministerkonferenz erstellt, während der Ausbildungsrahmenplan den betrieblichen Teil regelt."),
        .choice(id: "aus-c05", topic: .ausbildung,
                prompt: "Wer ist die zuständige Stelle für Ausbildungsberufe im Handwerk?",
                options: ["Die Handwerkskammer", "Die IHK", "Die Berufsschule",
                          "Das Gewerbeamt", "Die Bundesagentur für Arbeit"],
                explanation: "Während die IHK für kaufmännische und IT-Berufe zuständig ist, übernimmt die Handwerkskammer diese Rolle für Handwerksberufe."),
        .choice(id: "aus-c06", topic: .ausbildung,
                prompt: "Wann muss die Niederschrift der wesentlichen Vertragsinhalte des Ausbildungsvertrags nach § 11 BBiG spätestens vorliegen?",
                options: ["Vor Beginn der Ausbildung", "Erst nach Ende der Probezeit",
                          "Erst zur Zwischenprüfung", "Innerhalb eines Jahres nach Ausbildungsbeginn",
                          "Erst bei der Anmeldung zur Abschlussprüfung"],
                explanation: "Die Niederschrift muss unverzüglich nach Vertragsabschluss, spätestens vor Beginn der Ausbildung, vorliegen (§ 11 BBiG)."),
        .choice(id: "aus-c07", topic: .ausbildung,
                prompt: "Wer muss den Ausbildungsvertrag unterschreiben, wenn der Auszubildende noch minderjährig ist?",
                options: ["Zusätzlich der gesetzliche Vertreter", "Nur der Auszubildende allein",
                          "Nur der Ausbildungsbetrieb", "Die Berufsschule als Zeuge",
                          "Die IHK als Vertragspartei"],
                explanation: "Minderjährige sind beschränkt geschäftsfähig; der Ausbildungsvertrag muss deshalb zusätzlich vom gesetzlichen Vertreter unterschrieben werden."),
        .choice(id: "aus-c08", topic: .ausbildung,
                prompt: "Wie lange darf die Probezeit in der Berufsausbildung nach § 20 BBiG höchstens dauern?",
                options: ["4 Monate", "1 Monat", "6 Monate", "2 Monate", "12 Monate"],
                explanation: "Die Probezeit beträgt mindestens einen und höchstens vier Monate (§ 20 BBiG)."),
        .choice(id: "aus-c09", topic: .ausbildung,
                prompt: "Wie kann der Ausbildungsvertrag während der Probezeit gekündigt werden?",
                options: ["Jederzeit ohne Einhaltung einer Frist", "Nur zum Monatsende",
                          "Nur aus wichtigem Grund", "Nur mit Zustimmung der IHK",
                          "Frühestens nach vier Wochen"],
                explanation: "Während der Probezeit kann sowohl der Ausbildende als auch der Auszubildende jederzeit ohne Frist kündigen; die Kündigung muss schriftlich erfolgen."),
        .choice(id: "aus-c10", topic: .ausbildung,
                prompt: "Aus welchem Grund darf der Ausbildende nach Ablauf der Probezeit noch kündigen?",
                options: ["Nur fristlos aus wichtigem Grund", "Jederzeit mit zwei Wochen Frist",
                          "Jederzeit ohne Angabe von Gründen", "Nur zum Ende des Ausbildungsjahres",
                          "Nur bei Zustimmung der Berufsschule"],
                explanation: "Nach der Probezeit kann der Ausbildende nur noch fristlos aus wichtigem Grund kündigen (§ 22 BBiG)."),
        .choice(id: "aus-c11", topic: .ausbildung,
                prompt: "Mit welcher Frist kann ein Auszubildender nach der Probezeit kündigen, wenn er den Ausbildungsberuf wechseln möchte?",
                options: ["4 Wochen", "1 Woche", "2 Monate", "3 Tage", "6 Wochen"],
                explanation: "Nach der Probezeit kann der Auszubildende mit einer Frist von vier Wochen kündigen, wenn er die Ausbildung aufgeben oder den Beruf wechseln möchte (§ 22 BBiG)."),
        .choice(id: "aus-c12", topic: .ausbildung,
                prompt: "Wann endet das Ausbildungsverhältnis, wenn die Abschlussprüfung bestanden wurde?",
                options: ["Mit Bekanntgabe des Prüfungsergebnisses durch den Prüfungsausschuss",
                          "Immer erst mit Ablauf der vertraglich vereinbarten Ausbildungszeit",
                          "Erst mit dem nächsten Monatsende", "Mit dem letzten Berufsschultag",
                          "Erst nach schriftlicher Kündigung durch den Betrieb"],
                explanation: "Bei bestandener Prüfung endet das Ausbildungsverhältnis vorzeitig mit Bekanntgabe des Ergebnisses durch den Prüfungsausschuss, auch wenn die vereinbarte Zeit noch nicht abgelaufen ist."),
        .choice(id: "aus-c13", topic: .ausbildung,
                prompt: "Was gilt, wenn ein Auszubildender die Abschlussprüfung nicht besteht?",
                options: ["Das Ausbildungsverhältnis verlängert sich auf Verlangen bis zur nächsten Wiederholungsprüfung, höchstens um ein Jahr",
                          "Das Ausbildungsverhältnis endet sofort ohne Verlängerungsmöglichkeit",
                          "Der Auszubildende muss die gesamte Ausbildung von vorne beginnen",
                          "Die IHK verlängert automatisch um zwei Jahre",
                          "Der Betrieb ist verpflichtet, sofort unbefristet zu übernehmen"],
                explanation: "Bei Nichtbestehen verlängert sich das Ausbildungsverhältnis auf Verlangen des Auszubildenden bis zur nächsten möglichen Wiederholungsprüfung, höchstens um ein Jahr."),
        .choice(id: "aus-c14", topic: .ausbildung,
                prompt: "Wie oft darf die Abschlussprüfung höchstens wiederholt werden?",
                options: ["2-mal", "1-mal", "3-mal", "beliebig oft", "0-mal"],
                explanation: "Die Abschlussprüfung darf höchstens zweimal wiederholt werden."),
        .choice(id: "aus-c15", topic: .ausbildung,
                prompt: "Was gilt, wenn ein Auszubildender nach bestandener Prüfung ohne ausdrückliche Vereinbarung weiterbeschäftigt wird?",
                options: ["Es entsteht ein unbefristetes Arbeitsverhältnis",
                          "Das Ausbildungsverhältnis läuft automatisch weiter",
                          "Es entsteht ein auf ein Jahr befristetes Arbeitsverhältnis",
                          "Der Betrieb muss die Weiterbeschäftigung schriftlich widerrufen, sonst haftet die IHK",
                          "Es entsteht kein Arbeitsverhältnis, solange kein neuer Vertrag unterschrieben wird"],
                explanation: "Nach § 24 BBiG entsteht bei Weiterbeschäftigung ohne ausdrückliche Vereinbarung ein unbefristetes Arbeitsverhältnis."),
        .choice(id: "aus-c16", topic: .ausbildung,
                prompt: "Welche Pflicht hat der Ausbildungsbetrieb gegenüber dem Auszubildenden?",
                options: ["Ausbildungsmittel kostenlos zur Verfügung zu stellen",
                          "Die Kosten für die Berufsschulfahrten zu erstatten",
                          "Dem Auszubildenden ein eigenes Dienstfahrzeug zu stellen",
                          "Dem Auszubildenden freie Wahl der Arbeitszeiten zu lassen",
                          "Dem Auszubildenden die IHK-Prüfungsgebühr zu erlassen"],
                explanation: "Der Ausbildende muss Ausbildungsmittel wie Werkzeuge oder Materialien kostenlos zur Verfügung stellen und für Berufsschule und Prüfungen freistellen."),
        .choice(id: "aus-c17", topic: .ausbildung,
                prompt: "Welche Pflicht hat der Auszubildende während der Ausbildung?",
                options: ["Den Ausbildungsnachweis zu führen", "Die eigene Vergütung selbst festzulegen",
                          "Die Ausbildungsordnung selbst zu erstellen",
                          "Die Berufsschule nur bei Bedarf zu besuchen",
                          "Andere Auszubildende zu beaufsichtigen"],
                explanation: "Zu den Pflichten des Auszubildenden gehören u. a. Lernpflicht, Befolgen von Weisungen, Berufsschulbesuch und das Führen des Ausbildungsnachweises."),
        .choice(id: "aus-c18", topic: .ausbildung,
                prompt: "In welchem Fall ist eine Verkürzung der Ausbildungszeit möglich?",
                options: ["Auf Antrag, z. B. bei guten schulischen Leistungen oder Abitur",
                          "Nur wenn der Betrieb Insolvenz anmeldet",
                          "Nur bei einem Wechsel des Ausbildungsbetriebs",
                          "Nur wenn die Berufsschule dies verlangt",
                          "Grundsätzlich nie, die Ausbildungszeit ist immer fest"],
                explanation: "Eine Verkürzung ist auf Antrag möglich, z. B. bei guten Leistungen, Abitur oder anrechenbarer Vorbildung; auch eine vorzeitige Zulassung zur Prüfung ist möglich."),
        .choice(id: "aus-c19", topic: .ausbildung,
                prompt: "Wann findet Teil 1 der gestreckten Abschlussprüfung in IT-Ausbildungsberufen statt?",
                options: ["Etwa zur Mitte der Ausbildungszeit", "Erst im letzten Ausbildungsmonat",
                          "Bereits in den ersten vier Wochen der Ausbildung",
                          "Erst nach der Wiederholungsprüfung", "Gleichzeitig mit Teil 2"],
                explanation: "Teil 1 der gestreckten Abschlussprüfung findet etwa zur Mitte der Ausbildung statt und fließt mit 20 % in das Gesamtergebnis ein."),
        .choice(id: "aus-c20", topic: .ausbildung,
                prompt: "Mit welchem Anteil fließt Teil 1 der gestreckten Abschlussprüfung in das Gesamtergebnis ein?",
                options: ["20 %", "50 %", "10 %", "75 %", "0 %"],
                explanation: "Teil 1 macht bei IT-Ausbildungsberufen in der Regel 20 % des Gesamtergebnisses aus, Teil 2 den Rest."),
        .choice(id: "aus-c21", topic: .ausbildung,
                prompt: "Welches Beispiel beschreibt eine berufliche Aufstiegsfortbildung?",
                options: ["Ein Fachinformatiker qualifiziert sich zum IT-Specialist weiter",
                          "Ein Fachinformatiker lernt eine neue Version der bereits genutzten Software kennen",
                          "Ein Bäcker lässt sich zum Fachinformatiker umschulen",
                          "Ein Auszubildender besucht regulär die Berufsschule",
                          "Ein Mitarbeiter nimmt an einer einmaligen Produktschulung teil"],
                explanation: "Aufstiegsfortbildung führt zu einer höheren Qualifikation, z. B. Fachwirt, Meister oder IT-Specialist. Reines Aktualisieren von Wissen ist Anpassungsfortbildung, ein Berufswechsel ist eine Umschulung."),
        .choice(id: "aus-c22", topic: .ausbildung,
                prompt: "Welche Dokumente gehören zum Europass?",
                options: ["Lebenslauf, Mobilitätsnachweis und Zeugniserläuterung",
                          "Arbeitszeugnis und Lohnsteuerbescheinigung",
                          "Ausbildungsvertrag und Ausbildungsnachweis",
                          "Handelsregisterauszug und Gesellschaftsvertrag",
                          "Kündigungsschreiben und Arbeitsbescheinigung"],
                explanation: "Der Europass umfasst u. a. den Europass-Lebenslauf, den Mobilitätsnachweis für Auslandsaufenthalte und die Zeugniserläuterung."),

        .statement(id: "aus-s01", topic: .ausbildung,
                   text: "Die Berufsschule erstellt die Ausbildungsordnung für den betrieblichen Teil der Ausbildung.",
                   isTrue: false,
                   explanation: "Die Ausbildungsordnung mit dem Ausbildungsrahmenplan wird bundeseinheitlich erlassen; die Berufsschule richtet sich nach dem separaten Rahmenlehrplan der KMK."),
        .statement(id: "aus-s02", topic: .ausbildung,
                   text: "Die Probezeit in der Ausbildung darf höchstens vier Monate betragen.",
                   isTrue: true,
                   explanation: "Nach § 20 BBiG dauert die Probezeit mindestens einen, höchstens vier Monate."),
        .statement(id: "aus-s03", topic: .ausbildung,
                   text: "Während der Probezeit kann der Ausbildungsvertrag nur aus wichtigem Grund gekündigt werden.",
                   isTrue: false,
                   explanation: "In der Probezeit kann jederzeit ohne Frist und ohne besonderen Grund schriftlich gekündigt werden."),
        .statement(id: "aus-s04", topic: .ausbildung,
                   text: "Nach der Probezeit kann der Ausbildungsbetrieb nur noch fristlos aus wichtigem Grund kündigen.",
                   isTrue: true,
                   explanation: "Nach Ablauf der Probezeit ist eine ordentliche Kündigung durch den Betrieb ausgeschlossen; es bleibt nur die fristlose Kündigung aus wichtigem Grund (§ 22 BBiG)."),
        .statement(id: "aus-s05", topic: .ausbildung,
                   text: "Ein Auszubildender, der nach der Probezeit den Beruf wechseln möchte, kann mit einer Frist von vier Wochen kündigen.",
                   isTrue: true,
                   explanation: "Für die Aufgabe der Berufsausbildung oder einen Berufswechsel gilt nach der Probezeit eine Kündigungsfrist von vier Wochen."),
        .statement(id: "aus-s06", topic: .ausbildung,
                   text: "Die Ausbildungsvergütung muss während der gesamten Ausbildungszeit gleich hoch bleiben.",
                   isTrue: false,
                   explanation: "Die Ausbildungsvergütung muss angemessen sein und jährlich ansteigen; zudem gilt die Mindestausbildungsvergütung."),
        .statement(id: "aus-s07", topic: .ausbildung,
                   text: "Besteht ein Auszubildender die Abschlussprüfung nicht, endet das Ausbildungsverhältnis sofort ohne jede Verlängerungsmöglichkeit.",
                   isTrue: false,
                   explanation: "Auf Verlangen verlängert sich das Ausbildungsverhältnis bis zur nächsten Wiederholungsprüfung, höchstens um ein Jahr."),
        .statement(id: "aus-s08", topic: .ausbildung,
                   text: "Die Abschlussprüfung darf höchstens zweimal wiederholt werden.",
                   isTrue: true,
                   explanation: "Es sind maximal zwei Wiederholungsversuche vorgesehen."),
        .statement(id: "aus-s09", topic: .ausbildung,
                   text: "Wird ein Auszubildender nach bestandener Prüfung ohne ausdrückliche Vereinbarung weiterbeschäftigt, entsteht automatisch ein unbefristetes Arbeitsverhältnis.",
                   isTrue: true,
                   explanation: "Das ergibt sich aus § 24 BBiG."),
        .statement(id: "aus-s10", topic: .ausbildung,
                   text: "Die IHK ist auch für die Ausbildung in Handwerksberufen zuständige Stelle.",
                   isTrue: false,
                   explanation: "Für Handwerksberufe ist die Handwerkskammer zuständig, nicht die IHK."),
        .statement(id: "aus-s11", topic: .ausbildung,
                   text: "Der Auszubildende muss den Ausbildungsnachweis selbst bezahlen, wenn der Betrieb ihn nicht kostenlos zur Verfügung stellt.",
                   isTrue: false,
                   explanation: "Der Ausbildende muss das Führen des Ausbildungsnachweises kostenlos ermöglichen und die Nachweise regelmäßig durchsehen."),
        .statement(id: "aus-s12", topic: .ausbildung,
                   text: "Minderjährige Auszubildende müssen den Ausbildungsvertrag durch ihren gesetzlichen Vertreter unterschreiben lassen.",
                   isTrue: true,
                   explanation: "Aufgrund der beschränkten Geschäftsfähigkeit Minderjähriger ist die Unterschrift des gesetzlichen Vertreters erforderlich."),
        .statement(id: "aus-s13", topic: .ausbildung,
                   text: "Eine Verkürzung der Ausbildungszeit ist z. B. bei guten schulischen Leistungen möglich.",
                   isTrue: true,
                   explanation: "Auf Antrag kann die Ausbildungszeit verkürzt werden, etwa bei Abitur oder guten Leistungen; auch eine vorzeitige Zulassung zur Prüfung ist möglich."),
        .statement(id: "aus-s14", topic: .ausbildung,
                   text: "Eine Umschulung bezeichnet das Auffrischen von bereits vorhandenem Fachwissen im gleichen Beruf.",
                   isTrue: false,
                   explanation: "Das Auffrischen von Wissen im gleichen Beruf ist Anpassungsfortbildung. Umschulung bedeutet das Erlernen eines neuen Berufs."),

        .multiple(id: "aus-m01", topic: .ausbildung,
                  prompt: "Wähle alle zutreffenden Aussagen zu den Pflichten der Ausbildenden.",
                  correct: ["Ausbildungsmittel kostenlos bereitstellen",
                            "Für Berufsschule und Prüfungen freistellen",
                            "Nur ausbildungsbezogene Aufgaben übertragen",
                            "Ein Zeugnis am Ende der Ausbildung ausstellen"],
                  wrong: ["Fahrtkosten zur Berufsschule in jedem Fall übernehmen",
                          "Private Botengänge zuweisen dürfen",
                          "Die Ausbildungsvergütung nach freiem Ermessen kürzen dürfen"],
                  explanation: "Ausbildende müssen Ausbildungsmittel kostenlos stellen, freistellen, nur ausbildungsbezogene Aufgaben übertragen und ein Zeugnis ausstellen. Fahrtkosten, private Botengänge und willkürliche Kürzungen gehören nicht dazu."),
        .multiple(id: "aus-m02", topic: .ausbildung,
                  prompt: "Wähle alle zutreffenden Aussagen zu den Pflichten der Auszubildenden.",
                  correct: ["Den Ausbildungsnachweis führen", "Weisungen befolgen",
                            "Die Berufsschule besuchen", "Die Betriebsordnung beachten"],
                  wrong: ["Die eigene Vergütung selbst festlegen dürfen",
                          "Den Ausbildungsvertrag jederzeit formlos widerrufen dürfen",
                          "Eine eigene Ausbildungsordnung erstellen"],
                  explanation: "Zu den Azubi-Pflichten zählen Lernpflicht, Befolgen von Weisungen, Berufsschulbesuch, Führen des Ausbildungsnachweises und Beachtung der Betriebsordnung."),
        .multiple(id: "aus-m03", topic: .ausbildung,
                  prompt: "Wähle alle zutreffenden Aussagen zur Rolle der IHK in der Berufsausbildung.",
                  correct: ["Sie führt das Verzeichnis der Berufsausbildungsverhältnisse.",
                            "Sie berät durch Ausbildungsberater bei Konflikten.",
                            "Sie prüft die Eignung von Ausbildungsstätten und Ausbildern.",
                            "Sie nimmt die Abschlussprüfung ab."],
                  wrong: ["Sie ist für Handwerksberufe zuständig.",
                          "Sie zahlt die Ausbildungsvergütung aus.",
                          "Sie erstellt den Rahmenlehrplan der Berufsschule."],
                  explanation: "Die IHK ist zuständige Stelle für kaufmännische und IT-Berufe. Handwerksberufe, Vergütungszahlung und der Rahmenlehrplan liegen nicht in ihrer Zuständigkeit."),
        .multiple(id: "aus-m04", topic: .ausbildung,
                  prompt: "Wähle alle zutreffenden Aussagen zur gestreckten Abschlussprüfung in IT-Ausbildungsberufen.",
                  correct: ["Sie besteht aus Teil 1 und Teil 2.",
                            "Teil 1 findet etwa zur Mitte der Ausbildung statt.",
                            "Teil 1 fließt mit einem Anteil von 20 % in das Gesamtergebnis ein."],
                  wrong: ["Teil 1 kann beliebig oft wiederholt werden.",
                          "Teil 2 findet vor Teil 1 statt.",
                          "Die Berufsschule vergibt die Abschlussnote."],
                  explanation: "Die gestreckte Abschlussprüfung besteht aus zwei zeitlich getrennten Teilen; Teil 1 liegt etwa in der Ausbildungsmitte und zählt 20 %, Teil 2 findet am Ende statt."),

        .match(id: "aus-p01", topic: .ausbildung,
               prompt: "Ordne die Fortbildungsart dem passenden Beispiel zu.",
               pairs: [("Fachinformatiker qualifiziert sich zum IT-Specialist", "Aufstiegsfortbildung"),
                       ("Fachinformatiker lernt eine neue Version der genutzten Software", "Anpassungsfortbildung"),
                       ("Bäcker lässt sich zum Fachinformatiker umschulen", "Umschulung"),
                       ("Verwaltungsfachangestellte besucht Zertifikatslehrgang zu aktueller Software", "Anpassungsfortbildung")],
               extra: ["Erstausbildung"],
               explanation: "Aufstiegsfortbildung führt zu höherer Qualifikation, Anpassungsfortbildung hält vorhandenes Wissen aktuell, Umschulung führt in einen neuen Beruf."),
        .match(id: "aus-p02", topic: .ausbildung,
               prompt: "Ordne der Situation die passende Kündigungsregel im Ausbildungsverhältnis zu.",
               pairs: [("Jonas bricht die Ausbildung in der zweiten Woche ab", "Kündigung ohne Frist in der Probezeit"),
                       ("Der Betrieb entlässt Aylin nach acht Monaten wegen Diebstahls", "Fristlose Kündigung aus wichtigem Grund"),
                       ("Noah möchte nach zehn Monaten den Ausbildungsberuf wechseln", "Kündigung mit vier Wochen Frist"),
                       ("Mia verpasst einmalig unentschuldigt die Berufsschule", "Keine Kündigung möglich, allenfalls Abmahnung")],
               extra: ["Ordentliche Kündigung mit gesetzlicher Frist"],
               explanation: "In der Probezeit ist eine fristlose Kündigung ohne Grund möglich, danach nur noch aus wichtigem Grund (Betrieb) oder mit vier Wochen Frist bei Berufsaufgabe/-wechsel (Azubi); eine einzelne Pflichtverletzung rechtfertigt allein keine Kündigung."),
        .match(id: "aus-p03", topic: .ausbildung,
               prompt: "Ordne der Institution die passende Aufgabe in der Berufsausbildung zu.",
               pairs: [("IHK", "Führt das Verzeichnis der Berufsausbildungsverhältnisse"),
                       ("Berufsschule", "Vermittelt Theorie nach dem Rahmenlehrplan"),
                       ("Prüfungsausschuss", "Nimmt die Abschlussprüfung ab"),
                       ("Ausbildungsberater der IHK", "Berät Betrieb und Auszubildenden bei Konflikten")],
               extra: ["Handwerkskammer"],
               explanation: "Jede Institution hat eine klar abgegrenzte Rolle im dualen System; die Handwerkskammer ist hier nicht zuständig, da es sich um IT-/kaufmännische Berufe handelt."),
        .match(id: "aus-p04", topic: .ausbildung,
               prompt: "Ordne dem Begriff die passende Beschreibung zu.",
               pairs: [("Ausbildungsrahmenplan", "Teil der Ausbildungsordnung, regelt die betrieblichen Inhalte"),
                       ("Rahmenlehrplan", "Regelt den Unterricht in der Berufsschule"),
                       ("Ausbildungsnachweis", "Dokumentiert die erlernten Tätigkeiten"),
                       ("Europass-Mobilitätsnachweis", "Bestätigt Auslandsaufenthalte während der Ausbildung")],
               extra: [],
               explanation: "Ausbildungsrahmenplan und Rahmenlehrplan regeln die zwei Lernorte, der Ausbildungsnachweis dokumentiert den Lernfortschritt, der Mobilitätsnachweis Auslandsaufenthalte."),

        .order(id: "aus-o01", topic: .ausbildung,
               prompt: "Bringe den Ablauf von der Einstellung bis zum Ende einer IT-Ausbildung in die richtige Reihenfolge.",
               steps: ["Bewerbung und Vorstellungsgespräch",
                       "Abschluss des Ausbildungsvertrags und Eintragung bei der IHK",
                       "Beginn der Probezeit im Betrieb",
                       "Gestreckte Abschlussprüfung, Teil 1",
                       "Weitere Ausbildung in Betrieb und Berufsschule",
                       "Abschlussprüfung, Teil 2 vor dem Prüfungsausschuss",
                       "Bekanntgabe des Prüfungsergebnisses und Ende der Ausbildung"],
               explanation: "Nach Vertragsschluss und Eintragung folgt die Probezeit, dann Teil 1 der gestreckten Prüfung zur Ausbildungsmitte, die weitere Ausbildung, Teil 2 und schließlich die Bekanntgabe des Ergebnisses."),
        .order(id: "aus-o02", topic: .ausbildung,
               prompt: "Bringe den Ablauf bei einer nicht bestandenen Abschlussprüfung in die richtige Reihenfolge.",
               steps: ["Der Prüfungsausschuss stellt das Nichtbestehen fest",
                       "Der Auszubildende verlangt die Verlängerung des Ausbildungsverhältnisses",
                       "Das Ausbildungsverhältnis verlängert sich bis zur nächsten Wiederholungsprüfung, höchstens um ein Jahr",
                       "Vorbereitung auf die Wiederholungsprüfung in Betrieb und Berufsschule",
                       "Ablegen der Wiederholungsprüfung"],
               explanation: "Die Verlängerung erfolgt nur auf Verlangen des Auszubildenden und ist auf höchstens ein Jahr begrenzt."),

        .gap(id: "aus-g01", topic: .ausbildung, title: "Duales System",
             sentences: [("Die praktische Ausbildung findet im ___ statt.", "Betrieb"),
                         ("Die theoretische Ausbildung findet in der ___ statt.", "Berufsschule"),
                         ("Zuständige Stelle für die meisten IT-Ausbildungsberufe ist die ___.", "IHK"),
                         ("Der Rahmenlehrplan für die Berufsschule wird von der ___ erstellt.", "KMK")],
             extra: ["Handwerkskammer", "Bundesagentur für Arbeit"],
             explanation: "Das duale System verbindet Betrieb und Berufsschule; zuständige Stelle für IT-Berufe ist die IHK, den Rahmenlehrplan erstellt die KMK."),
        .gap(id: "aus-g02", topic: .ausbildung, title: "Kündigungsschutz in der Ausbildung",
             sentences: [("Während der ___ kann der Ausbildungsvertrag jederzeit ohne Frist gekündigt werden.", "Probezeit"),
                         ("Nach der Probezeit kann der Ausbildende nur noch aus einem ___ Grund fristlos kündigen.", "wichtigen"),
                         ("Ein Auszubildender kann nach der Probezeit mit einer Frist von vier ___ kündigen, wenn er den Beruf aufgibt.", "Wochen"),
                         ("Die Probezeit dauert mindestens einen und höchstens vier ___.", "Monate")],
             extra: ["Tagen", "Jahren"],
             explanation: "Nach der Probezeit gilt für den Betrieb nur noch die fristlose Kündigung aus wichtigem Grund, für den Azubi die Vier-Wochen-Frist bei Berufsaufgabe."),

        .fact(id: "aus-f01", topic: .ausbildung, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange dauert die Probezeit in der Ausbildung höchstens?", answer: "4 Monate",
              explanation: "§ 20 BBiG erlaubt eine Probezeit von mindestens einem, höchstens vier Monaten."),
        .fact(id: "aus-f02", topic: .ausbildung, group: ExamCatalog.Group.zeitraum,
              question: "Um wie viel kann das Ausbildungsverhältnis bei Nichtbestehen der Prüfung höchstens verlängert werden?", answer: "1 Jahr",
              explanation: "Die Verlängerung erfolgt auf Verlangen bis zur nächsten Wiederholungsprüfung, höchstens um ein Jahr."),
        .fact(id: "aus-f03", topic: .ausbildung, group: ExamCatalog.Group.zeitraum,
              question: "Mit welcher Frist kann ein Azubi nach der Probezeit kündigen, wenn er den Beruf aufgibt?", answer: "4 Wochen",
              explanation: "Für die Aufgabe der Ausbildung oder einen Berufswechsel gilt nach der Probezeit eine Frist von vier Wochen."),
        .fact(id: "aus-f04", topic: .ausbildung, group: ExamCatalog.Group.anzahl,
              question: "Wie oft darf die Abschlussprüfung höchstens wiederholt werden?", answer: "2-mal",
              explanation: "Es sind maximal zwei Wiederholungsversuche vorgesehen."),
        .fact(id: "aus-f05", topic: .ausbildung, group: ExamCatalog.Group.anzahl,
              question: "Aus wie vielen Teilen besteht die gestreckte Abschlussprüfung in IT-Berufen?", answer: "2 Teilen",
              explanation: "Die gestreckte Abschlussprüfung besteht aus Teil 1 (zur Ausbildungsmitte) und Teil 2 (am Ende)."),
        .fact(id: "aus-f06", topic: .ausbildung, group: ExamCatalog.Group.prozent,
              question: "Mit welchem Anteil fließt Teil 1 der gestreckten Abschlussprüfung in das Gesamtergebnis ein?", answer: "20 %",
              explanation: "Teil 1 zählt in der Regel 20 % des Gesamtergebnisses, Teil 2 den Rest."),
        .fact(id: "aus-f07", topic: .ausbildung, group: ExamCatalog.Group.stelle,
              question: "Welche Institution ist für die meisten IT-Ausbildungsberufe die zuständige Stelle?", answer: "IHK",
              explanation: "Für kaufmännische und IT-Berufe ist die IHK zuständige Stelle nach dem BBiG."),
        .fact(id: "aus-f08", topic: .ausbildung, group: ExamCatalog.Group.stelle,
              question: "Welche Institution ist für Ausbildungsberufe im Handwerk zuständig?", answer: "Handwerkskammer",
              explanation: "Für Handwerksberufe übernimmt die Handwerkskammer die Rolle der zuständigen Stelle."),
    ]

    static let arbeitsrecht: [ExamCard] = [
        .choice(id: "arb-c01", topic: .arbeitsrecht,
                prompt: "Welche Form muss die Kündigung eines Arbeitsvertrags nach § 623 BGB haben?",
                options: ["Schriftform mit eigenhändiger Unterschrift, elektronische Form ist ausgeschlossen",
                          "Sie kann formlos mündlich erklärt werden",
                          "Sie kann wirksam per E-Mail erklärt werden",
                          "Sie muss notariell beurkundet werden",
                          "Sie kann per SMS erklärt werden, wenn der Empfang bestätigt wird"],
                explanation: "§ 623 BGB verlangt für Kündigungen die Schriftform mit eigenhändiger Unterschrift; die elektronische Form ist ausdrücklich ausgeschlossen."),
        .choice(id: "arb-c02", topic: .arbeitsrecht,
                prompt: "Was gilt, wenn der Betriebsrat vor einer Kündigung nicht angehört wurde?",
                options: ["Die Kündigung ist unwirksam", "Die Kündigung ist trotzdem wirksam",
                          "Die Kündigungsfrist verlängert sich automatisch",
                          "Der Arbeitnehmer erhält automatisch eine Abfindung",
                          "Die Kündigung wird nur befristet wirksam"],
                explanation: "Nach § 102 BetrVG ist eine Kündigung ohne vorherige Anhörung des Betriebsrats unwirksam."),
        .choice(id: "arb-c03", topic: .arbeitsrecht,
                prompt: "Wie lautet die gesetzliche Grundkündigungsfrist nach § 622 Abs. 1 BGB?",
                options: ["4 Wochen zum 15. oder zum Ende eines Kalendermonats",
                          "1 Woche zum Monatsende", "2 Monate zum Quartalsende",
                          "6 Wochen zum Jahresende", "3 Tage ohne festen Termin"],
                explanation: "Die Grundkündigungsfrist beträgt vier Wochen zum 15. oder zum Ende eines Kalendermonats."),
        .choice(id: "arb-c04", topic: .arbeitsrecht,
                prompt: "Wie lange beträgt die Kündigungsfrist üblicherweise während einer vereinbarten Probezeit von höchstens sechs Monaten?",
                options: ["2 Wochen", "4 Wochen", "1 Monat", "3 Monate", "6 Monate"],
                explanation: "Während der vereinbarten Probezeit (max. 6 Monate) beträgt die Kündigungsfrist zwei Wochen."),
        .choice(id: "arb-c05", topic: .arbeitsrecht,
                prompt: "Wie lang ist die vom Arbeitgeber einzuhaltende Kündigungsfrist nach acht Jahren Betriebszugehörigkeit?",
                options: ["3 Monate zum Monatsende", "1 Monat zum Monatsende",
                          "6 Monate zum Monatsende", "2 Wochen", "4 Monate zum Quartalsende"],
                explanation: "Nach § 622 Abs. 2 BGB gilt bei 8 Jahren Betriebszugehörigkeit eine Kündigungsfrist von 3 Monaten zum Monatsende für den Arbeitgeber."),
        .choice(id: "arb-c06", topic: .arbeitsrecht,
                prompt: "Innerhalb welcher Frist muss eine fristlose Kündigung aus wichtigem Grund nach § 626 BGB erklärt werden?",
                options: ["Innerhalb von 2 Wochen nach Kenntnis des Kündigungsgrundes",
                          "Innerhalb von 3 Monaten nach dem Vorfall", "Ohne Fristbindung, jederzeit möglich",
                          "Innerhalb von 4 Wochen nach Vertragsschluss", "Nur am letzten Arbeitstag des Monats"],
                explanation: "Die fristlose Kündigung muss innerhalb von zwei Wochen ab Kenntnis der Tatsachen erklärt werden, die sie rechtfertigen."),
        .choice(id: "arb-c07", topic: .arbeitsrecht,
                prompt: "Ab welchen Voraussetzungen findet das Kündigungsschutzgesetz (KSchG) Anwendung?",
                options: ["Mehr als 10 Arbeitnehmer im Betrieb und mehr als 6 Monate Betriebszugehörigkeit",
                          "Ab dem ersten Arbeitstag, unabhängig von der Betriebsgröße",
                          "Nur in Betrieben mit mehr als 200 Arbeitnehmern",
                          "Nur bei unbefristeten Verträgen ab 5 Jahren Betriebszugehörigkeit",
                          "Nur für Auszubildende nach der Probezeit"],
                explanation: "Das KSchG gilt in Betrieben mit mehr als 10 Arbeitnehmern, wenn das Arbeitsverhältnis länger als 6 Monate besteht."),
        .choice(id: "arb-c08", topic: .arbeitsrecht,
                prompt: "Welche drei Kündigungsgründe kennt das Kündigungsschutzgesetz?",
                options: ["Personen-, verhaltens- und betriebsbedingte Gründe",
                          "Wirtschaftliche, politische und private Gründe",
                          "Fristlose, ordentliche und außerordentliche Gründe",
                          "Vertragliche, gesetzliche und tarifliche Gründe",
                          "Freiwillige, unfreiwillige und einvernehmliche Gründe"],
                explanation: "Eine Kündigung muss sozial gerechtfertigt sein: personen-, verhaltens- oder betriebsbedingt."),
        .choice(id: "arb-c09", topic: .arbeitsrecht,
                prompt: "Was setzt eine verhaltensbedingte Kündigung in der Regel voraus?",
                options: ["Eine vorherige Abmahnung", "Eine Zustimmung der Krankenkasse",
                          "Eine Anzeige beim Sozialgericht", "Eine Freistellung von mindestens drei Monaten",
                          "Eine Zustimmung der Berufsgenossenschaft"],
                explanation: "Vor einer verhaltensbedingten Kündigung ist in der Regel eine Abmahnung erforderlich, damit der Arbeitnehmer sein Verhalten ändern kann."),
        .choice(id: "arb-c10", topic: .arbeitsrecht,
                prompt: "Innerhalb welcher Frist muss eine Kündigungsschutzklage erhoben werden?",
                options: ["3 Wochen nach Zugang der Kündigung", "6 Monate nach Zugang der Kündigung",
                          "1 Woche nach Zugang der Kündigung", "1 Jahr nach Zugang der Kündigung",
                          "Es gibt keine Frist"],
                explanation: "Eine Kündigungsschutzklage muss innerhalb von drei Wochen nach Zugang der Kündigung beim Arbeitsgericht erhoben werden."),
        .choice(id: "arb-c11", topic: .arbeitsrecht,
                prompt: "Wie lange genießen Schwangere und Mütter nach der Entbindung besonderen Kündigungsschutz nach dem MuSchG?",
                options: ["Bis 4 Monate nach der Entbindung", "Bis 6 Wochen nach der Entbindung",
                          "Bis 1 Jahr nach der Entbindung", "Nur während der Schwangerschaft, danach endet der Schutz sofort",
                          "Bis zum 3. Geburtstag des Kindes"],
                explanation: "Der besondere Kündigungsschutz nach dem MuSchG besteht während der Schwangerschaft und bis vier Monate nach der Entbindung."),
        .choice(id: "arb-c12", topic: .arbeitsrecht,
                prompt: "Wie lange darf ein Arbeitsvertrag ohne Sachgrund höchstens befristet werden?",
                options: ["2 Jahre, mit höchstens 3 Verlängerungen", "5 Jahre, ohne Verlängerungsmöglichkeit",
                          "6 Monate, mit beliebig vielen Verlängerungen", "1 Jahr, mit höchstens 5 Verlängerungen",
                          "Unbegrenzt, solange der Arbeitnehmer zustimmt"],
                explanation: "Nach § 14 TzBfG ist die sachgrundlose Befristung auf höchstens 2 Jahre begrenzt, innerhalb dieser Zeit sind höchstens 3 Verlängerungen möglich."),
        .choice(id: "arb-c13", topic: .arbeitsrecht,
                prompt: "Was gilt, wenn nach Ablauf eines befristeten Vertrags mit Wissen des Arbeitgebers weitergearbeitet wird?",
                options: ["Das Arbeitsverhältnis gilt als unbefristet fortgesetzt",
                          "Die Befristung verlängert sich automatisch um ein weiteres Jahr",
                          "Das Arbeitsverhältnis endet sofort ohne Vergütungsanspruch",
                          "Es entsteht automatisch ein Werkvertrag",
                          "Der Arbeitnehmer muss die geleisteten Stunden zurückzahlen"],
                explanation: "Wird nach Fristablauf mit Wissen des Arbeitgebers weitergearbeitet, gilt das Arbeitsverhältnis als auf unbestimmte Zeit verlängert."),
        .choice(id: "arb-c14", topic: .arbeitsrecht,
                prompt: "Was enthält ein qualifiziertes Arbeitszeugnis zusätzlich zu Art und Dauer der Tätigkeit?",
                options: ["Angaben zu Leistung und Verhalten", "Die private Wohnadresse des Arbeitnehmers",
                          "Die Höhe des zuletzt gezahlten Gehalts", "Angaben zur Konfession des Arbeitnehmers",
                          "Eine Bewertung der Kollegen"],
                explanation: "Das qualifizierte Zeugnis enthält zusätzlich zu Art und Dauer der Beschäftigung eine Bewertung von Leistung und Verhalten; es wird auf Verlangen erteilt (§ 109 GewO)."),
        .choice(id: "arb-c15", topic: .arbeitsrecht,
                prompt: "Wie lange dauert die Entgeltfortzahlung im Krankheitsfall (EFZG)?",
                options: ["6 Wochen", "2 Wochen", "3 Monate", "1 Jahr", "78 Wochen"],
                explanation: "Der Arbeitgeber zahlt bei Arbeitsunfähigkeit das Entgelt für 6 Wochen weiter; danach zahlt die Krankenkasse Krankengeld."),
        .choice(id: "arb-c16", topic: .arbeitsrecht,
                prompt: "Ab wann besteht ein Anspruch auf Entgeltfortzahlung im Krankheitsfall?",
                options: ["Nach 4 Wochen ununterbrochenem Arbeitsverhältnis", "Ab dem ersten Beschäftigungstag",
                          "Erst nach 6 Monaten Betriebszugehörigkeit", "Erst nach einem Jahr Betriebszugehörigkeit",
                          "Nur wenn der Betriebsrat zustimmt"],
                explanation: "Der Anspruch entsteht, wenn das Arbeitsverhältnis mindestens vier Wochen ununterbrochen bestanden hat."),
        .choice(id: "arb-c17", topic: .arbeitsrecht,
                prompt: "Spätestens wann muss eine Arbeitsunfähigkeitsbescheinigung vorgelegt werden, wenn der Arbeitgeber nichts anderes verlangt?",
                options: ["Am 4. Kalendertag der Erkrankung", "Am 1. Kalendertag der Erkrankung",
                          "Erst nach 6 Wochen", "Erst nach der Rückkehr an den Arbeitsplatz",
                          "Nur auf ausdrückliche Aufforderung, sonst nie"],
                explanation: "Grundsätzlich muss die AU-Bescheinigung spätestens am vierten Kalendertag vorliegen; der Arbeitgeber darf sie aber auch früher verlangen."),
        .choice(id: "arb-c18", topic: .arbeitsrecht,
                prompt: "Wie hoch ist der gesetzliche Mindesturlaub nach dem BUrlG bei einer 5-Tage-Woche?",
                options: ["20 Arbeitstage", "24 Arbeitstage", "30 Arbeitstage", "15 Arbeitstage", "10 Arbeitstage"],
                explanation: "24 Werktage (Mo–Sa) entsprechen bei einer 5-Tage-Woche 20 Arbeitstagen."),
        .choice(id: "arb-c19", topic: .arbeitsrecht,
                prompt: "Wann entsteht der volle Urlaubsanspruch nach dem BUrlG?",
                options: ["Nach sechs Monaten Wartezeit", "Sofort mit Beginn des Arbeitsverhältnisses",
                          "Erst nach einem Jahr Betriebszugehörigkeit", "Erst nach der Probezeit von vier Monaten",
                          "Nach zwei Jahren Betriebszugehörigkeit"],
                explanation: "Der volle Urlaubsanspruch entsteht erstmals nach sechs Monaten Wartezeit im Betrieb."),
        .choice(id: "arb-c20", topic: .arbeitsrecht,
                prompt: "Welches Merkmal zählt zu den im AGG geschützten Merkmalen?",
                options: ["Alter", "Kleidungsstil", "Wohnort", "Automarke", "Lieblingsfarbe"],
                explanation: "Das AGG schützt u. a. vor Diskriminierung wegen Alter, ethnischer Herkunft, Geschlecht, Religion, Behinderung und sexueller Identität."),
        .choice(id: "arb-c21", topic: .arbeitsrecht,
                prompt: "Wie lange vor der Entbindung beginnt die Mutterschutzfrist grundsätzlich?",
                options: ["6 Wochen vorher", "2 Wochen vorher", "3 Monate vorher",
                          "1 Woche vorher", "Erst mit der Geburt"],
                explanation: "Die Schutzfrist beginnt sechs Wochen vor dem errechneten Entbindungstermin; auf sie kann die Arbeitnehmerin freiwillig verzichten."),
        .choice(id: "arb-c22", topic: .arbeitsrecht,
                prompt: "Wie lange kann Elternzeit je Kind höchstens in Anspruch genommen werden?",
                options: ["Bis zu 3 Jahre je Kind, bis zum 8. Geburtstag", "Nur 6 Monate je Kind",
                          "Bis zu 10 Jahre je Kind", "Nur während der Schwangerschaft",
                          "Bis zu 1 Jahr, danach automatisches Ende des Arbeitsverhältnisses"],
                explanation: "Eltern haben Anspruch auf bis zu drei Jahre Elternzeit je Kind, die bis zum achten Geburtstag des Kindes genommen werden können."),

        .statement(id: "arb-s01", topic: .arbeitsrecht,
                   text: "Eine Kündigung des Arbeitsverhältnisses kann wirksam per E-Mail erklärt werden.",
                   isTrue: false,
                   explanation: "§ 623 BGB verlangt die Schriftform mit eigenhändiger Unterschrift; die elektronische Form ist ausgeschlossen."),
        .statement(id: "arb-s02", topic: .arbeitsrecht,
                   text: "Der Betriebsrat muss vor jeder Kündigung angehört werden, sonst ist sie unwirksam.",
                   isTrue: true,
                   explanation: "§ 102 BetrVG schreibt die vorherige Anhörung zwingend vor."),
        .statement(id: "arb-s03", topic: .arbeitsrecht,
                   text: "Die gesetzliche Grundkündigungsfrist beträgt vier Wochen zum 15. oder zum Ende eines Kalendermonats.",
                   isTrue: true,
                   explanation: "So bestimmt es § 622 Abs. 1 BGB."),
        .statement(id: "arb-s04", topic: .arbeitsrecht,
                   text: "Während einer vereinbarten Probezeit gilt automatisch eine Kündigungsfrist von vier Wochen.",
                   isTrue: false,
                   explanation: "Während der vereinbarten Probezeit (max. 6 Monate) beträgt die Kündigungsfrist zwei Wochen."),
        .statement(id: "arb-s05", topic: .arbeitsrecht,
                   text: "Das Kündigungsschutzgesetz gilt bereits ab dem ersten Tag der Beschäftigung.",
                   isTrue: false,
                   explanation: "Es gilt erst nach mehr als sechs Monaten Betriebszugehörigkeit in Betrieben mit mehr als 10 Arbeitnehmern."),
        .statement(id: "arb-s06", topic: .arbeitsrecht,
                   text: "Eine Kündigungsschutzklage muss innerhalb von drei Wochen erhoben werden.",
                   isTrue: true,
                   explanation: "Diese Frist beginnt mit Zugang der Kündigung."),
        .statement(id: "arb-s07", topic: .arbeitsrecht,
                   text: "Schwangere genießen bis vier Monate nach der Entbindung besonderen Kündigungsschutz.",
                   isTrue: true,
                   explanation: "Das ergibt sich aus dem Mutterschutzgesetz."),
        .statement(id: "arb-s08", topic: .arbeitsrecht,
                   text: "Ein befristeter Arbeitsvertrag ohne Sachgrund darf beliebig oft verlängert werden.",
                   isTrue: false,
                   explanation: "Nach § 14 TzBfG sind innerhalb von höchstens zwei Jahren nur bis zu drei Verlängerungen zulässig."),
        .statement(id: "arb-s09", topic: .arbeitsrecht,
                   text: "Ein einfaches Arbeitszeugnis enthält bereits Angaben zu Leistung und Verhalten.",
                   isTrue: false,
                   explanation: "Das einfache Zeugnis nennt nur Art und Dauer der Tätigkeit; Leistung und Verhalten stehen erst im qualifizierten Zeugnis."),
        .statement(id: "arb-s10", topic: .arbeitsrecht,
                   text: "Die Entgeltfortzahlung im Krankheitsfall beträgt sechs Wochen.",
                   isTrue: true,
                   explanation: "Nach dem EFZG zahlt der Arbeitgeber sechs Wochen lang das Entgelt fort."),
        .statement(id: "arb-s11", topic: .arbeitsrecht,
                   text: "Eine Arbeitsunfähigkeitsbescheinigung muss grundsätzlich schon am ersten Krankheitstag vorliegen, wenn der Arbeitgeber nichts anderes verlangt.",
                   isTrue: false,
                   explanation: "Ohne besondere Anordnung reicht die Vorlage spätestens am vierten Kalendertag."),
        .statement(id: "arb-s12", topic: .arbeitsrecht,
                   text: "Bei einer 5-Tage-Woche entspricht der gesetzliche Mindesturlaub 20 Arbeitstagen.",
                   isTrue: true,
                   explanation: "24 Werktage nach dem BUrlG entsprechen bei einer 5-Tage-Woche 20 Arbeitstagen."),
        .statement(id: "arb-s13", topic: .arbeitsrecht,
                   text: "Wird während des Urlaubs eine Krankheit ärztlich nachgewiesen, werden diese Tage nicht auf den Urlaub angerechnet.",
                   isTrue: true,
                   explanation: "Das regelt § 9 BUrlG."),
        .statement(id: "arb-s14", topic: .arbeitsrecht,
                   text: "Im Vorstellungsgespräch darf grundsätzlich nach einer bestehenden Schwangerschaft gefragt werden.",
                   isTrue: false,
                   explanation: "Die Frage nach einer Schwangerschaft ist grundsätzlich unzulässig."),

        .multiple(id: "arb-m01", topic: .arbeitsrecht,
                  prompt: "Wähle alle Personengruppen, die besonderen Kündigungsschutz genießen.",
                  correct: ["Schwangere und Mütter bis vier Monate nach der Entbindung",
                            "Beschäftigte in Elternzeit", "Mitglieder des Betriebsrats",
                            "Schwerbehinderte Menschen"],
                  wrong: ["Beschäftigte in der vereinbarten Probezeit",
                          "Befristet Beschäftigte ohne besonderen Status",
                          "Leitende Angestellte allgemein"],
                  explanation: "Besonderen Kündigungsschutz genießen u. a. Schwangere/Mütter, Beschäftigte in Elternzeit, Betriebsratsmitglieder und schwerbehinderte Menschen (mit Zustimmung des Integrationsamts)."),
        .multiple(id: "arb-m02", topic: .arbeitsrecht,
                  prompt: "Wähle alle zutreffenden Aussagen zur Kündigungsfrist nach § 622 BGB.",
                  correct: ["Die Grundfrist beträgt vier Wochen zum 15. oder zum Monatsende.",
                            "Die Frist verlängert sich mit der Dauer der Betriebszugehörigkeit.",
                            "Nach acht Jahren Betriebszugehörigkeit beträgt die Frist für den Arbeitgeber drei Monate.",
                            "Während einer vereinbarten Probezeit kann mit zwei Wochen Frist gekündigt werden."],
                  wrong: ["Der Arbeitnehmer hat immer dieselbe verlängerte Frist wie der Arbeitgeber.",
                          "Kündigungsfristen dürfen niemals vertraglich abweichend geregelt werden.",
                          "Die Kündigungsfrist beginnt immer am Tag der Vertragsunterschrift."],
                  explanation: "Die verlängerten Fristen gelten grundsätzlich nur für Kündigungen durch den Arbeitgeber; der Arbeitnehmer bleibt in der Regel bei der Grundfrist, sofern nichts anderes vereinbart ist."),
        .multiple(id: "arb-m03", topic: .arbeitsrecht,
                  prompt: "Wähle alle Arbeitspapiere, die bei Beendigung eines Arbeitsverhältnisses typischerweise ausgehändigt werden.",
                  correct: ["Arbeitszeugnis", "Arbeitsbescheinigung für die Agentur für Arbeit",
                            "Lohnsteuerbescheinigung", "Urlaubsbescheinigung"],
                  wrong: ["Ausbildungsnachweis", "Gesellschaftsvertrag", "Mietvertrag"],
                  explanation: "Beim Ausscheiden erhält der Arbeitnehmer u. a. Arbeitszeugnis, Arbeitsbescheinigung, Lohnsteuerbescheinigung und Urlaubsbescheinigung."),
        .multiple(id: "arb-m04", topic: .arbeitsrecht,
                  prompt: "Wähle alle zutreffenden Aussagen zum gesetzlichen Urlaubsanspruch (BUrlG).",
                  correct: ["Der Mindesturlaub beträgt 24 Werktage.", "Werktage sind Montag bis Samstag.",
                            "Der volle Anspruch entsteht nach sechs Monaten Wartezeit.",
                            "Ärztlich nachgewiesene Krankheitstage im Urlaub werden nicht angerechnet."],
                  wrong: ["Urlaub verfällt immer zum 31. Dezember ohne jede Ausnahme.",
                          "Krankheitstage im Urlaub werden grundsätzlich trotzdem angerechnet.",
                          "Der Urlaubsanspruch entsteht erst nach zwei Jahren Betriebszugehörigkeit."],
                  explanation: "Der gesetzliche Mindesturlaub beträgt 24 Werktage, der volle Anspruch entsteht nach sechs Monaten; nachgewiesene Krankheitstage zählen nicht als Urlaub, und eine Übertragung ist bei dringenden Gründen bis 31. März möglich."),

        .match(id: "arb-p01", topic: .arbeitsrecht,
               prompt: "Ordne die Kündigungsart der passenden Beschreibung zu.",
               pairs: [("Ordentliche Kündigung", "Kündigung unter Einhaltung der gesetzlichen oder vertraglichen Frist"),
                       ("Außerordentliche Kündigung", "Fristlose Kündigung aus wichtigem Grund"),
                       ("Verhaltensbedingte Kündigung", "Setzt in der Regel eine vorherige Abmahnung voraus"),
                       ("Betriebsbedingte Kündigung", "Wegfall des Arbeitsplatzes aus dringenden betrieblichen Gründen")],
               extra: ["Kündigung zur Unzeit"],
               explanation: "Die Kündigungsarten unterscheiden sich nach Frist und Grund."),
        .match(id: "arb-p02", topic: .arbeitsrecht,
               prompt: "Ordne dem Fall den passenden besonderen Kündigungsschutz zu.",
               pairs: [("Aylin ist im siebten Monat schwanger", "Mutterschutz"),
                       ("Jonas ist Mitglied des Betriebsrats", "Kündigungsschutz nach dem BetrVG"),
                       ("Noah befindet sich in Elternzeit", "Kündigungsschutz während der Elternzeit"),
                       ("Mia ist als schwerbehindert anerkannt", "Zustimmung des Integrationsamts erforderlich")],
               extra: [],
               explanation: "Jede Gruppe ist durch ein eigenes Gesetz besonders vor Kündigung geschützt."),
        .match(id: "arb-p03", topic: .arbeitsrecht,
               prompt: "Ordne dem Arbeitspapier die passende Beschreibung zu.",
               pairs: [("Einfaches Arbeitszeugnis", "Enthält Art und Dauer der Tätigkeit"),
                       ("Qualifiziertes Arbeitszeugnis", "Enthält zusätzlich Leistung und Verhalten"),
                       ("Arbeitsbescheinigung", "Wird für die Agentur für Arbeit benötigt"),
                       ("Lohnsteuerbescheinigung", "Wird für die Einkommensteuererklärung benötigt")],
               extra: ["Ausbildungsnachweis"],
               explanation: "Jedes Dokument erfüllt einen eigenen Zweck beim Ausscheiden aus dem Arbeitsverhältnis."),
        .match(id: "arb-p04", topic: .arbeitsrecht,
               prompt: "Ordne dem Zeitraum die passende Regelung im Arbeitsrecht zu.",
               pairs: [("2 Wochen", "Frist für die fristlose Kündigung ab Kenntnis des Grundes"),
                       ("4 Wochen", "Voraussetzung für den Beginn der Entgeltfortzahlung"),
                       ("6 Wochen", "Dauer der Entgeltfortzahlung im Krankheitsfall"),
                       ("3 Wochen", "Frist für die Kündigungsschutzklage")],
               extra: ["6 Monate"],
               explanation: "Die Fristen betreffen unterschiedliche Regelungsbereiche des Arbeitsrechts."),

        .order(id: "arb-o01", topic: .arbeitsrecht,
               prompt: "Bringe den Ablauf von der Kündigung bis zur Klage vor dem Arbeitsgericht in die richtige Reihenfolge.",
               steps: ["Anhörung des Betriebsrats durch den Arbeitgeber",
                       "Zugang der schriftlichen Kündigung beim Arbeitnehmer",
                       "Prüfung, ob das Kündigungsschutzgesetz anwendbar ist",
                       "Erhebung der Kündigungsschutzklage innerhalb von drei Wochen",
                       "Güteverhandlung vor dem Arbeitsgericht",
                       "Kammertermin, falls keine Einigung erzielt wird"],
               explanation: "Vor der Kündigung steht die Anhörung des Betriebsrats, danach der Zugang der Kündigung, die Fristprüfung, die Klageerhebung und das gerichtliche Verfahren."),
        .order(id: "arb-o02", topic: .arbeitsrecht,
               prompt: "Bringe den Ablauf bei einer krankheitsbedingten Arbeitsunfähigkeit in die richtige Reihenfolge.",
               steps: ["Krankmeldung beim Arbeitgeber am ersten Krankheitstag",
                       "Arztbesuch und Ausstellung der Arbeitsunfähigkeitsbescheinigung",
                       "Vorlage der Bescheinigung spätestens am vierten Kalendertag",
                       "Entgeltfortzahlung durch den Arbeitgeber für sechs Wochen",
                       "Bei fortdauernder Krankheit: Krankengeld durch die Krankenkasse"],
               explanation: "Nach der Krankmeldung folgen Arztbesuch, Vorlage der Bescheinigung, Entgeltfortzahlung und schließlich das Krankengeld."),

        .gap(id: "arb-g01", topic: .arbeitsrecht, title: "Kündigungsschutz",
             sentences: [("Das Kündigungsschutzgesetz gilt in Betrieben mit mehr als ___ Arbeitnehmern.", "10"),
                         ("Der Arbeitnehmer muss länger als sechs ___ im Betrieb beschäftigt sein.", "Monate"),
                         ("Eine Kündigungsschutzklage muss innerhalb von drei ___ erhoben werden.", "Wochen"),
                         ("Eine verhaltensbedingte Kündigung setzt in der Regel eine vorherige ___ voraus.", "Abmahnung")],
             extra: ["Tagen", "Jahren"],
             explanation: "Das KSchG gilt ab 10 Arbeitnehmern und 6 Monaten Betriebszugehörigkeit; die Klagefrist beträgt drei Wochen, eine verhaltensbedingte Kündigung setzt meist eine Abmahnung voraus."),
        .gap(id: "arb-g02", topic: .arbeitsrecht, title: "Entgeltfortzahlung und Urlaub",
             sentences: [("Die Entgeltfortzahlung im Krankheitsfall dauert sechs ___.", "Wochen"),
                         ("Der Anspruch entsteht nach vier Wochen ununterbrochenem ___.", "Arbeitsverhältnis"),
                         ("Der gesetzliche Mindesturlaub beträgt 24 ___.", "Werktage"),
                         ("Der volle Urlaubsanspruch entsteht nach sechs Monaten ___.", "Wartezeit")],
             extra: ["Kalendertagen", "Jahren"],
             explanation: "Entgeltfortzahlung und Urlaubsanspruch sind gesetzlich klar geregelte Mindestansprüche."),

        .fact(id: "arb-f01", topic: .arbeitsrecht, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange dauert die gesetzliche Entgeltfortzahlung im Krankheitsfall?", answer: "6 Wochen",
              explanation: "Nach dem EFZG zahlt der Arbeitgeber sechs Wochen lang das Entgelt fort."),
        .fact(id: "arb-f02", topic: .arbeitsrecht, group: ExamCatalog.Group.zeitraum,
              question: "Innerhalb welcher Frist muss eine Kündigungsschutzklage erhoben werden?", answer: "3 Wochen",
              explanation: "Die Klagefrist beginnt mit Zugang der Kündigung und beträgt drei Wochen."),
        .fact(id: "arb-f03", topic: .arbeitsrecht, group: ExamCatalog.Group.zeitraum,
              question: "Innerhalb welcher Frist muss eine fristlose Kündigung nach Kenntnis des Grundes ausgesprochen werden?", answer: "2 Wochen",
              explanation: "§ 626 BGB verlangt die fristlose Kündigung innerhalb von zwei Wochen ab Kenntnis."),
        .fact(id: "arb-f04", topic: .arbeitsrecht, group: ExamCatalog.Group.zeitraum,
              question: "Welche Kündigungsfrist gilt für den Arbeitgeber nach acht Jahren Betriebszugehörigkeit?", answer: "3 Monate",
              explanation: "Nach § 622 Abs. 2 BGB beträgt die Frist bei acht Jahren Betriebszugehörigkeit drei Monate zum Monatsende."),
        .fact(id: "arb-f05", topic: .arbeitsrecht, group: ExamCatalog.Group.anzahl,
              question: "Ab wie vielen Arbeitnehmern im Betrieb gilt das Kündigungsschutzgesetz?", answer: "mehr als 10",
              explanation: "Das KSchG gilt in Betrieben mit mehr als 10 Arbeitnehmern."),
        .fact(id: "arb-f06", topic: .arbeitsrecht, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange darf ein Arbeitsvertrag ohne Sachgrund höchstens befristet werden?", answer: "2 Jahre",
              explanation: "§ 14 TzBfG begrenzt die sachgrundlose Befristung auf höchstens zwei Jahre."),
        .fact(id: "arb-f07", topic: .arbeitsrecht, group: ExamCatalog.Group.stelle,
              question: "Bei welchem Gericht wird eine Kündigungsschutzklage erhoben?", answer: "Arbeitsgericht",
              explanation: "Streitigkeiten aus dem Arbeitsverhältnis werden vor dem Arbeitsgericht verhandelt."),
        .fact(id: "arb-f08", topic: .arbeitsrecht, group: ExamCatalog.Group.stelle,
              question: "Wessen Zustimmung ist für die Kündigung eines schwerbehinderten Menschen notwendig?", answer: "Integrationsamt",
              explanation: "Ohne Zustimmung des Integrationsamts ist die Kündigung unwirksam."),
    ]

    static let schutz: [ExamCard] = [
        .choice(id: "sch-c01", topic: .schutz,
                prompt: "Wie viele Stunden täglich dürfen Jugendliche nach dem JArbSchG höchstens beschäftigt werden?",
                options: ["8 Stunden", "6 Stunden", "10 Stunden", "5 Stunden", "12 Stunden"],
                explanation: "Das Jugendarbeitsschutzgesetz begrenzt die tägliche Arbeitszeit Jugendlicher grundsätzlich auf 8 Stunden."),
        .choice(id: "sch-c02", topic: .schutz,
                prompt: "Wie viele Stunden pro Woche dürfen Jugendliche nach dem JArbSchG höchstens beschäftigt werden?",
                options: ["40 Stunden", "48 Stunden", "35 Stunden", "45 Stunden", "50 Stunden"],
                explanation: "Die wöchentliche Arbeitszeit Jugendlicher ist grundsätzlich auf 40 Stunden bei einer 5-Tage-Woche begrenzt."),
        .choice(id: "sch-c03", topic: .schutz,
                prompt: "Wie lange muss die Pause für Jugendliche bei einer Arbeitszeit von mehr als 6 Stunden mindestens sein?",
                options: ["60 Minuten", "30 Minuten", "15 Minuten", "90 Minuten", "45 Minuten"],
                explanation: "Bei mehr als 6 Stunden Arbeitszeit sind für Jugendliche mindestens 60 Minuten Pause vorgeschrieben."),
        .choice(id: "sch-c04", topic: .schutz,
                prompt: "Wie lange muss die Pause für Jugendliche bei einer Arbeitszeit von mehr als 4,5 bis 6 Stunden mindestens sein?",
                options: ["30 Minuten", "60 Minuten", "10 Minuten", "90 Minuten", "20 Minuten"],
                explanation: "Bei mehr als 4,5 bis 6 Stunden Arbeitszeit sind mindestens 30 Minuten Pause vorgeschrieben."),
        .choice(id: "sch-c05", topic: .schutz,
                prompt: "Wie lang muss ein einzelner Pausenblock für Jugendliche mindestens sein, um angerechnet zu werden?",
                options: ["15 Minuten", "5 Minuten", "45 Minuten", "60 Minuten", "2 Minuten"],
                explanation: "Eine Pause muss mindestens 15 Minuten am Stück dauern, damit sie angerechnet werden kann."),
        .choice(id: "sch-c06", topic: .schutz,
                prompt: "Wie viele Stunden Freizeit müssen zwischen zwei Arbeitstagen von Jugendlichen mindestens liegen?",
                options: ["12 Stunden", "8 Stunden", "10 Stunden", "6 Stunden", "14 Stunden"],
                explanation: "Zwischen zwei Beschäftigungstagen müssen Jugendliche mindestens 12 Stunden ununterbrochene Freizeit haben."),
        .choice(id: "sch-c07", topic: .schutz,
                prompt: "In welchem Zeitraum gilt für Jugendliche grundsätzlich die Nachtruhe?",
                options: ["20 bis 6 Uhr", "22 bis 6 Uhr", "18 bis 8 Uhr", "23 bis 5 Uhr", "21 bis 7 Uhr"],
                explanation: "Die Nachtruhe für Jugendliche gilt grundsätzlich von 20 bis 6 Uhr, es gibt branchenspezifische Ausnahmen."),
        .choice(id: "sch-c08", topic: .schutz,
                prompt: "Wie viele Werktage Mindesturlaub stehen Jugendlichen zu, die zu Beginn des Kalenderjahres noch nicht 16 Jahre alt sind?",
                options: ["30 Werktage", "27 Werktage", "25 Werktage", "24 Werktage", "20 Werktage"],
                explanation: "Für unter 16-Jährige gelten 30 Werktage Mindesturlaub nach dem JArbSchG."),
        .choice(id: "sch-c09", topic: .schutz,
                prompt: "Wie viele Werktage Mindesturlaub stehen Jugendlichen zu, die zu Beginn des Kalenderjahres noch nicht 17 Jahre alt sind?",
                options: ["27 Werktage", "30 Werktage", "25 Werktage", "24 Werktage", "22 Werktage"],
                explanation: "Für unter 17-Jährige gelten 27 Werktage Mindesturlaub nach dem JArbSchG."),
        .choice(id: "sch-c10", topic: .schutz,
                prompt: "Wie viele Werktage Mindesturlaub stehen Jugendlichen zu, die zu Beginn des Kalenderjahres noch nicht 18 Jahre alt sind?",
                options: ["25 Werktage", "30 Werktage", "27 Werktage", "24 Werktage", "20 Werktage"],
                explanation: "Für unter 18-Jährige gelten 25 Werktage Mindesturlaub nach dem JArbSchG."),
        .choice(id: "sch-c11", topic: .schutz,
                prompt: "Wie alt darf die ärztliche Erstuntersuchung höchstens sein, bevor ein Jugendlicher beschäftigt werden darf?",
                options: ["14 Monate", "6 Monate", "24 Monate", "3 Monate", "36 Monate"],
                explanation: "Vor Beginn der Beschäftigung darf die Erstuntersuchung nicht älter als 14 Monate sein."),
        .choice(id: "sch-c12", topic: .schutz,
                prompt: "Wann muss bei jugendlichen Beschäftigten die ärztliche Nachuntersuchung erfolgen?",
                options: ["Nach 1 Jahr Beschäftigung", "Nach 6 Monaten Beschäftigung",
                          "Nach 3 Jahren Beschäftigung", "Erst bei Beendigung der Ausbildung",
                          "Nur auf ausdrücklichen Wunsch des Jugendlichen"],
                explanation: "Die Nachuntersuchung ist nach einem Jahr Beschäftigung vorgeschrieben."),
        .choice(id: "sch-c13", topic: .schutz,
                prompt: "Wie viele Stunden werktäglich dürfen Erwachsene nach dem Arbeitszeitgesetz (ArbZG) grundsätzlich arbeiten?",
                options: ["8 Stunden, mit Verlängerung auf bis zu 10 Stunden möglich", "6 Stunden ohne Ausnahme",
                          "12 Stunden ohne Ausgleichspflicht", "10 Stunden als feste Obergrenze ohne Ausgleich",
                          "4 Stunden bei Vollzeit"],
                explanation: "Grundsätzlich gelten 8 Stunden werktäglich; eine Verlängerung auf bis zu 10 Stunden ist möglich, wenn im Schnitt von 6 Monaten 8 Stunden eingehalten werden."),
        .choice(id: "sch-c14", topic: .schutz,
                prompt: "Über welchen Zeitraum wird die Einhaltung der durchschnittlichen 8-Stunden-Grenze bei Erwachsenen nach dem ArbZG ausgeglichen?",
                options: ["6 Monate bzw. 24 Wochen", "1 Monat", "1 Jahr", "3 Monate", "12 Wochen"],
                explanation: "Der Ausgleichszeitraum beträgt 6 Monate oder 24 Wochen."),
        .choice(id: "sch-c15", topic: .schutz,
                prompt: "Wie lange muss die Pause für Erwachsene bei einer Arbeitszeit von mehr als 6 Stunden mindestens sein?",
                options: ["30 Minuten", "60 Minuten", "15 Minuten", "45 Minuten", "10 Minuten"],
                explanation: "Bei mehr als 6 Stunden Arbeitszeit sind für Erwachsene mindestens 30 Minuten Pause vorgeschrieben."),
        .choice(id: "sch-c16", topic: .schutz,
                prompt: "Wie lange muss die Pause für Erwachsene bei einer Arbeitszeit von mehr als 9 Stunden mindestens sein?",
                options: ["45 Minuten", "30 Minuten", "60 Minuten", "15 Minuten", "90 Minuten"],
                explanation: "Bei mehr als 9 Stunden Arbeitszeit sind mindestens 45 Minuten Pause vorgeschrieben."),
        .choice(id: "sch-c17", topic: .schutz,
                prompt: "Wie lang ist die gesetzliche Ruhezeit zwischen zwei Arbeitstagen für Erwachsene?",
                options: ["11 Stunden", "8 Stunden", "6 Stunden", "14 Stunden", "9 Stunden"],
                explanation: "Zwischen zwei Arbeitstagen müssen Erwachsene mindestens 11 Stunden ununterbrochene Ruhezeit haben."),
        .choice(id: "sch-c18", topic: .schutz,
                prompt: "Wer ist nach dem Arbeitsschutzgesetz (ArbSchG) für die Sicherheit im Betrieb in erster Linie verantwortlich?",
                options: ["Der Arbeitgeber", "Ausschließlich die Berufsgenossenschaft",
                          "Ausschließlich die Gewerbeaufsicht", "Ausschließlich der Betriebsrat",
                          "Ausschließlich jeder einzelne Beschäftigte"],
                explanation: "Der Arbeitgeber trägt die Verantwortung für den Arbeitsschutz, u. a. durch die Gefährdungsbeurteilung."),
        .choice(id: "sch-c19", topic: .schutz,
                prompt: "Wie oft müssen Beschäftigte mindestens im Arbeitsschutz unterwiesen werden?",
                options: ["Mindestens jährlich", "Nur einmalig bei Einstellung", "Nur bei einem Unfall",
                          "Alle 5 Jahre", "Nur auf Anforderung der Berufsgenossenschaft"],
                explanation: "Die Unterweisung der Beschäftigten muss mindestens jährlich erfolgen, durchgeführt vom Arbeitgeber oder den Vorgesetzten."),
        .choice(id: "sch-c20", topic: .schutz,
                prompt: "Ab wann ist ein Arbeitsunfall meldepflichtig?",
                options: ["Bei mehr als 3 Kalendertagen Arbeitsunfähigkeit oder bei Tod",
                          "Erst ab mehr als 4 Wochen Arbeitsunfähigkeit",
                          "Nur bei tödlichem Ausgang", "Bei jeder noch so kleinen Verletzung",
                          "Erst nach schriftlicher Aufforderung durch die Krankenkasse"],
                explanation: "Ein Arbeitsunfall ist meldepflichtig, wenn er zu mehr als drei Kalendertagen Arbeitsunfähigkeit führt oder tödlich verläuft; die Meldung erfolgt an die Berufsgenossenschaft."),
        .choice(id: "sch-c21", topic: .schutz,
                prompt: "Ab wie vielen Beschäftigten sind Sicherheitsbeauftragte und ein Arbeitsschutzausschuss vorgeschrieben?",
                options: ["Mehr als 20 Beschäftigten", "Mehr als 5 Beschäftigten",
                          "Mehr als 100 Beschäftigten", "Mehr als 500 Beschäftigten",
                          "Ab jedem Betrieb, unabhängig von der Größe"],
                explanation: "Sicherheitsbeauftragte und der Arbeitsschutzausschuss sind ab mehr als 20 Beschäftigten vorgeschrieben."),
        .choice(id: "sch-c22", topic: .schutz,
                prompt: "Wie sind Verbotszeichen nach ASR A1.3 gestaltet?",
                options: ["Rund, rot umrandet mit Querbalken", "Gelbes Dreieck mit schwarzem Rand",
                          "Rund und blau", "Grün und rechteckig", "Rot und rechteckig"],
                explanation: "Verbotszeichen sind rund, rot umrandet und mit einem Querbalken versehen. Warnzeichen sind gelbe Dreiecke, Gebotszeichen runde blaue Schilder, Rettungszeichen grüne Rechtecke, Brandschutzzeichen rote Rechtecke."),

        .statement(id: "sch-s01", topic: .schutz,
                   text: "Jugendliche dürfen grundsätzlich höchstens acht Stunden täglich beschäftigt werden.",
                   isTrue: true,
                   explanation: "Das JArbSchG begrenzt die tägliche Arbeitszeit auf grundsätzlich 8 Stunden."),
        .statement(id: "sch-s02", topic: .schutz,
                   text: "Die wöchentliche Arbeitszeit für Jugendliche darf 45 Stunden betragen.",
                   isTrue: false,
                   explanation: "Die wöchentliche Höchstarbeitszeit für Jugendliche beträgt 40 Stunden."),
        .statement(id: "sch-s03", topic: .schutz,
                   text: "Jugendliche dürfen unter keinen Umständen länger als acht Stunden an einem Tag arbeiten.",
                   isTrue: false,
                   explanation: "Bis zu 8,5 Stunden sind zulässig, wenn an anderen Werktagen entsprechend verkürzt wird."),
        .statement(id: "sch-s04", topic: .schutz,
                   text: "Zwischen zwei Arbeitstagen müssen Jugendliche mindestens zwölf Stunden Freizeit haben.",
                   isTrue: true,
                   explanation: "Das JArbSchG schreibt eine Mindestfreizeit von 12 Stunden zwischen zwei Beschäftigungstagen vor."),
        .statement(id: "sch-s05", topic: .schutz,
                   text: "Die Nachtruhe für Jugendliche gilt grundsätzlich von 20 bis 6 Uhr.",
                   isTrue: true,
                   explanation: "Außerhalb dieser Zeit dürfen Jugendliche grundsätzlich nicht beschäftigt werden, Ausnahmen sind branchenabhängig geregelt."),
        .statement(id: "sch-s06", topic: .schutz,
                   text: "Ein Berufsschultag mit mehr als fünf Unterrichtsstunden zu 45 Minuten befreit nicht von der Beschäftigung im Betrieb am selben Tag.",
                   isTrue: false,
                   explanation: "An einem solchen Berufsschultag entfällt einmal pro Woche die betriebliche Beschäftigung; der Tag wird mit acht Stunden angerechnet."),
        .statement(id: "sch-s07", topic: .schutz,
                   text: "Akkordarbeit ist für Jugendliche nach dem JArbSchG verboten.",
                   isTrue: true,
                   explanation: "Das JArbSchG untersagt Akkordarbeit und andere tempoabhängige Arbeit für Jugendliche."),
        .statement(id: "sch-s08", topic: .schutz,
                   text: "Erwachsene dürfen nach dem Arbeitszeitgesetz werktäglich grundsätzlich bis zu zehn Stunden ohne jede Ausgleichspflicht arbeiten.",
                   isTrue: false,
                   explanation: "Die Verlängerung auf bis zu 10 Stunden ist nur zulässig, wenn im Durchschnitt von 6 Monaten 8 Stunden eingehalten werden."),
        .statement(id: "sch-s09", topic: .schutz,
                   text: "Die gesetzliche Ruhezeit zwischen zwei Arbeitstagen beträgt für Erwachsene elf Stunden.",
                   isTrue: true,
                   explanation: "Das ArbZG schreibt eine Mindestruhezeit von 11 Stunden vor."),
        .statement(id: "sch-s10", topic: .schutz,
                   text: "Für die Gefährdungsbeurteilung im Betrieb ist ausschließlich die Berufsgenossenschaft verantwortlich.",
                   isTrue: false,
                   explanation: "Verantwortlich für die Gefährdungsbeurteilung ist der Arbeitgeber; die Berufsgenossenschaft erlässt Unfallverhütungsvorschriften und überwacht."),
        .statement(id: "sch-s11", topic: .schutz,
                   text: "Ein Arbeitsunfall ist meldepflichtig, wenn er zu mehr als drei Kalendertagen Arbeitsunfähigkeit führt.",
                   isTrue: true,
                   explanation: "Ab mehr als drei Kalendertagen Arbeitsunfähigkeit (oder bei Tod) besteht Meldepflicht an die Berufsgenossenschaft."),
        .statement(id: "sch-s12", topic: .schutz,
                   text: "Sicherheitsbeauftragte sind erst ab mehr als 20 Beschäftigten im Betrieb vorgeschrieben.",
                   isTrue: true,
                   explanation: "Diese Schwelle gilt sowohl für Sicherheitsbeauftragte als auch für den Arbeitsschutzausschuss."),
        .statement(id: "sch-s13", topic: .schutz,
                   text: "Warnzeichen nach ASR A1.3 sind runde blaue Schilder.",
                   isTrue: false,
                   explanation: "Warnzeichen sind gelbe Dreiecke mit schwarzem Rand; runde blaue Schilder sind Gebotszeichen."),
        .statement(id: "sch-s14", topic: .schutz,
                   text: "Rettungszeichen nach ASR A1.3 sind grün und rechteckig.",
                   isTrue: true,
                   explanation: "Rettungszeichen wie Fluchtwegschilder sind grün und rechteckig gestaltet."),

        .multiple(id: "sch-m01", topic: .schutz,
                  prompt: "Wähle alle zutreffenden Aussagen zu den Pausenregelungen für Jugendliche (JArbSchG).",
                  correct: ["Bei mehr als 4,5 bis 6 Stunden Arbeitszeit sind 30 Minuten Pause vorgeschrieben.",
                            "Bei mehr als 6 Stunden Arbeitszeit sind 60 Minuten Pause vorgeschrieben.",
                            "Eine Pause muss mindestens 15 Minuten am Stück dauern.",
                            "Akkordarbeit ist für Jugendliche nicht erlaubt."],
                  wrong: ["Pausen dürfen vollständig auf Zuruf des Arbeitgebers entfallen.",
                          "Eine Pause von fünf Minuten erfüllt bereits die Mindestanforderung.",
                          "Jugendliche dürfen ohne jede Pause bis zu acht Stunden arbeiten."],
                  explanation: "Die Pausendauer richtet sich nach der Arbeitszeit, ein Pausenblock muss mindestens 15 Minuten betragen, Akkordarbeit ist untersagt."),
        .multiple(id: "sch-m02", topic: .schutz,
                  prompt: "Wähle alle zutreffenden Aussagen zum Arbeitszeitgesetz für Erwachsene.",
                  correct: ["Die werktägliche Arbeitszeit beträgt grundsätzlich acht Stunden.",
                            "Eine Verlängerung auf bis zu zehn Stunden ist möglich, wenn im Schnitt von sechs Monaten acht Stunden eingehalten werden.",
                            "Bei mehr als sechs Stunden Arbeitszeit sind 30 Minuten Pause vorgeschrieben.",
                            "Die Ruhezeit zwischen zwei Arbeitstagen beträgt elf Stunden."],
                  wrong: ["Pausen dürfen vollständig entfallen, wenn der Arbeitgeber zustimmt.",
                          "Die Ruhezeit zwischen zwei Arbeitstagen beträgt nur sechs Stunden.",
                          "Überstunden sind nach dem Arbeitszeitgesetz vollständig verboten."],
                  explanation: "Das ArbZG legt Höchstarbeitszeit, Ausgleichszeitraum, Pausen und Ruhezeit für Erwachsene fest."),
        .multiple(id: "sch-m03", topic: .schutz,
                  prompt: "Wähle alle zutreffenden Aussagen zum betrieblichen Arbeitsschutz.",
                  correct: ["Der Arbeitgeber muss eine Gefährdungsbeurteilung erstellen.",
                            "Beschäftigte müssen mindestens jährlich unterwiesen werden.",
                            "Ab mehr als 20 Beschäftigten sind Sicherheitsbeauftragte zu bestellen.",
                            "Die Berufsgenossenschaft überwacht die Einhaltung der Unfallverhütungsvorschriften."],
                  wrong: ["Nur die Gewerbeaufsicht darf Unterweisungen durchführen.",
                          "Eine Gefährdungsbeurteilung ist freiwillig.",
                          "Sicherheitsbeauftragte sind in jedem Betrieb unabhängig von der Größe Pflicht."],
                  explanation: "Der Arbeitgeber ist für Gefährdungsbeurteilung und Unterweisung verantwortlich; ab mehr als 20 Beschäftigten kommen Sicherheitsbeauftragte hinzu, überwacht wird u. a. durch die Berufsgenossenschaft."),
        .multiple(id: "sch-m04", topic: .schutz,
                  prompt: "Wähle alle zutreffenden Aussagen zu Sicherheitszeichen nach ASR A1.3.",
                  correct: ["Verbotszeichen sind rund und rot umrandet mit Querbalken.",
                            "Warnzeichen sind gelbe Dreiecke mit schwarzem Rand.",
                            "Gebotszeichen sind rund und blau.",
                            "Rettungszeichen sind grün und rechteckig."],
                  wrong: ["Brandschutzzeichen sind gelb und rund.",
                          "Verbotszeichen sind grün und dreieckig.",
                          "Gebotszeichen sind rot und rechteckig."],
                  explanation: "Jede Zeichenart hat eine feste Form-Farb-Kombination; Brandschutzzeichen sind tatsächlich rot und rechteckig."),

        .match(id: "sch-p01", topic: .schutz,
               prompt: "Ordne dem Sicherheitszeichen die passende Form und Farbe zu.",
               pairs: [("Verbotszeichen", "Rund, rot umrandet mit Querbalken"),
                       ("Warnzeichen", "Gelbes Dreieck mit schwarzem Rand"),
                       ("Gebotszeichen", "Rund und blau"),
                       ("Rettungszeichen", "Grün und rechteckig"),
                       ("Brandschutzzeichen", "Rot und rechteckig")],
               extra: [],
               explanation: "Nach ASR A1.3 sind Form und Farbe der Sicherheitszeichen genormt."),
        .match(id: "sch-p02", topic: .schutz,
               prompt: "Ordne der Altersgruppe den passenden Mindesturlaub nach dem JArbSchG bzw. BUrlG zu.",
               pairs: [("Noch nicht 16 Jahre zu Jahresbeginn", "30 Werktage"),
                       ("Noch nicht 17 Jahre zu Jahresbeginn", "27 Werktage"),
                       ("Noch nicht 18 Jahre zu Jahresbeginn", "25 Werktage"),
                       ("Volljährige Beschäftigte", "24 Werktage (gesetzlicher Mindesturlaub)")],
               extra: [],
               explanation: "Je jünger die Beschäftigten zu Jahresbeginn sind, desto höher ist der gesetzliche Mindesturlaub nach dem JArbSchG."),
        .match(id: "sch-p03", topic: .schutz,
               prompt: "Ordne der Institution die passende Aufgabe im Arbeitsschutz zu.",
               pairs: [("Gewerbeaufsicht", "Überwacht als staatliche Behörde die Einhaltung der Arbeitsschutzgesetze"),
                       ("Berufsgenossenschaft", "Erlässt Unfallverhütungsvorschriften und trägt die Unfallversicherung"),
                       ("Fachkraft für Arbeitssicherheit", "Berät den Arbeitgeber in Fragen der Arbeitssicherheit"),
                       ("Betriebsarzt", "Führt arbeitsmedizinische Vorsorgeuntersuchungen durch")],
               extra: ["Integrationsamt"],
               explanation: "Staatliche Aufsicht, Berufsgenossenschaft und innerbetriebliche Fachkräfte ergänzen sich im Arbeitsschutz."),
        .match(id: "sch-p04", topic: .schutz,
               prompt: "Ordne der Situation die passende Pausenregelung zu.",
               pairs: [("Jonas, 16 Jahre, arbeitet 5 Stunden", "30 Minuten Pause"),
                       ("Mia, 17 Jahre, arbeitet 7 Stunden", "60 Minuten Pause"),
                       ("Noah, 30 Jahre, arbeitet 7 Stunden", "30 Minuten Pause"),
                       ("Aylin, 35 Jahre, arbeitet 10 Stunden", "45 Minuten Pause")],
               extra: [],
               explanation: "Für Jugendliche und Erwachsene gelten unterschiedliche Pausengrenzen je nach Dauer der Arbeitszeit."),

        .order(id: "sch-o01", topic: .schutz,
               prompt: "Bringe den Ablauf nach einem meldepflichtigen Arbeitsunfall in die richtige Reihenfolge.",
               steps: ["Erste Hilfe leisten und Unfallstelle sichern",
                       "Vorgesetzten über den Unfall informieren",
                       "Ärztliche Behandlung des Verletzten",
                       "Prüfen, ob die Arbeitsunfähigkeit mehr als drei Kalendertage dauert",
                       "Unfallanzeige an die Berufsgenossenschaft senden",
                       "Unfallursache untersuchen und Präventionsmaßnahmen ableiten"],
               explanation: "Nach Erster Hilfe und Information folgen ärztliche Behandlung, Prüfung der Meldepflicht, die Unfallanzeige und die Ursachenanalyse."),
        .order(id: "sch-o02", topic: .schutz,
               prompt: "Bringe den Ablauf der Gefährdungsbeurteilung im Betrieb in die richtige Reihenfolge.",
               steps: ["Gefährdungen am Arbeitsplatz ermitteln",
                       "Risiken bewerten",
                       "Schutzmaßnahmen festlegen",
                       "Maßnahmen umsetzen",
                       "Wirksamkeit der Maßnahmen überprüfen",
                       "Gefährdungsbeurteilung bei Veränderungen aktualisieren"],
               explanation: "Die Gefährdungsbeurteilung ist ein fortlaufender Kreislauf aus Ermitteln, Bewerten, Handeln und Überprüfen."),

        .gap(id: "sch-g01", topic: .schutz, title: "Jugendarbeitsschutz",
             sentences: [("Jugendliche dürfen grundsätzlich höchstens acht Stunden pro ___ arbeiten.", "Tag"),
                         ("Die wöchentliche Arbeitszeit darf 40 ___ nicht überschreiten.", "Stunden"),
                         ("Zwischen zwei Arbeitstagen müssen mindestens zwölf Stunden ___ liegen.", "Freizeit"),
                         ("Die Nachtruhe für Jugendliche gilt von 20 bis ___ Uhr.", "6")],
             extra: ["10", "45"],
             explanation: "Das JArbSchG begrenzt Arbeitszeit, Freizeit und Nachtruhe für unter 18-Jährige."),
        .gap(id: "sch-g02", topic: .schutz, title: "Betrieblicher Arbeitsschutz",
             sentences: [("Für die Sicherheit im Betrieb ist in erster Linie der ___ verantwortlich.", "Arbeitgeber"),
                         ("Grundlage für Schutzmaßnahmen ist die ___.", "Gefährdungsbeurteilung"),
                         ("Beschäftigte müssen mindestens einmal jährlich ___ werden.", "unterwiesen"),
                         ("Ein Arbeitsunfall mit mehr als drei Tagen Ausfall wird der Berufsgenossenschaft per ___ gemeldet.", "Unfallanzeige")],
             extra: ["Betriebsrat", "Gewerbeaufsicht"],
             explanation: "Der Arbeitgeber trägt die Hauptverantwortung für Gefährdungsbeurteilung, Unterweisung und Unfallmeldung."),

        .fact(id: "sch-f01", topic: .schutz, group: ExamCatalog.Group.zeitraum,
              question: "Wie lange muss die Freizeit zwischen zwei Arbeitstagen für Jugendliche mindestens betragen?", answer: "12 Stunden",
              explanation: "Das JArbSchG schreibt mindestens 12 Stunden Freizeit zwischen zwei Beschäftigungstagen vor."),
        .fact(id: "sch-f02", topic: .schutz, group: ExamCatalog.Group.zeitraum,
              question: "Wie lang ist die gesetzliche Ruhezeit zwischen zwei Arbeitstagen für Erwachsene?", answer: "11 Stunden",
              explanation: "Das ArbZG schreibt für Erwachsene mindestens 11 Stunden Ruhezeit vor."),
        .fact(id: "sch-f03", topic: .schutz, group: ExamCatalog.Group.alter,
              question: "Bis zu welchem Alter gilt das Jugendarbeitsschutzgesetz?", answer: "18 Jahre",
              explanation: "Das JArbSchG schützt Beschäftigte unter 18 Jahren."),
        .fact(id: "sch-f04", topic: .schutz, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Werktage Mindesturlaub stehen Jugendlichen zu, die zu Jahresbeginn noch nicht 16 Jahre alt sind?", answer: "30 Werktage",
              explanation: "Für unter 16-Jährige gelten 30 Werktage Mindesturlaub."),
        .fact(id: "sch-f05", topic: .schutz, group: ExamCatalog.Group.anzahl,
              question: "Ab wie vielen Beschäftigten ist ein Arbeitsschutzausschuss vorgeschrieben?", answer: "mehr als 20",
              explanation: "Ab mehr als 20 Beschäftigten sind sowohl Sicherheitsbeauftragte als auch der Arbeitsschutzausschuss vorgeschrieben."),
        .fact(id: "sch-f06", topic: .schutz, group: ExamCatalog.Group.anzahl,
              question: "Ab wie vielen Kalendertagen Arbeitsunfähigkeit ist ein Arbeitsunfall meldepflichtig?", answer: "mehr als 3",
              explanation: "Führt ein Arbeitsunfall zu mehr als drei Kalendertagen Arbeitsunfähigkeit oder zum Tod, muss er der Berufsgenossenschaft gemeldet werden."),
        .fact(id: "sch-f07", topic: .schutz, group: ExamCatalog.Group.stelle,
              question: "Welche Institution erlässt Unfallverhütungsvorschriften und trägt die gesetzliche Unfallversicherung?", answer: "Berufsgenossenschaft",
              explanation: "Die Berufsgenossenschaften sind Träger der gesetzlichen Unfallversicherung und erlassen Unfallverhütungsvorschriften."),
        .fact(id: "sch-f08", topic: .schutz, group: ExamCatalog.Group.stelle,
              question: "Welches Gesetz regelt die Arbeitszeit von unter 18-Jährigen?", answer: "Jugendarbeitsschutzgesetz",
              explanation: "Das Jugendarbeitsschutzgesetz (JArbSchG) enthält die besonderen Arbeitszeit- und Schutzregeln für Jugendliche."),
    ]
}
