// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Lino Laske

import Foundation

/// Original practice material for the topics "Markt & Wirtschaftspolitik" and
/// "Nachhaltigkeit & Umwelt". See `ExamCatalog` for the overall structure.
extension ExamCatalog {

    // MARK: - Markt & Wirtschaftspolitik

    static let wirtschaft: [ExamCard] = [
        // Choice
        .choice(id: "wir-c01", topic: .wirtschaft,
                prompt: "Was beschreibt der Gleichgewichtspreis auf einem Markt?",
                options: ["Der Preis, bei dem sich angebotene und nachgefragte Menge genau entsprechen",
                          "Der niedrigste Preis, den Anbieter am Markt verlangen",
                          "Der Preis, den der Staat für ein Gut festlegt",
                          "Der höchste Preis, den Nachfrager zu zahlen bereit sind",
                          "Der Preis, der sich nur bei einem Monopol bildet"],
                explanation: "Beim Gleichgewichtspreis (Marktpreis) ist die angebotene Menge gleich der nachgefragten Menge, der Markt ist geräumt."),
        .choice(id: "wir-c02", topic: .wirtschaft,
                prompt: "Wie reagiert die nachgefragte Menge eines Gutes typischerweise, wenn dessen Preis steigt?",
                options: ["Sie sinkt, weil weniger Nachfrager bereit sind, den höheren Preis zu zahlen",
                          "Sie steigt automatisch im gleichen Verhältnis",
                          "Sie bleibt unverändert, da der Preis keinen Einfluss hat",
                          "Sie sinkt nur, wenn gleichzeitig das Angebot steigt",
                          "Sie steigt, weil Anbieter dadurch mehr produzieren"],
                explanation: "Nach dem Gesetz der Nachfrage sinkt die nachgefragte Menge bei steigendem Preis; das Angebot reagiert umgekehrt."),
        .choice(id: "wir-c03", topic: .wirtschaft,
                prompt: "Wie reagiert die angebotene Menge eines Gutes typischerweise, wenn dessen Preis steigt?",
                options: ["Sie steigt, weil die Produktion für die Anbieter attraktiver wird",
                          "Sie sinkt, weil sich die Produktion nicht mehr lohnt",
                          "Sie bleibt unabhängig vom Preis konstant",
                          "Sie steigt nur bei einem Monopol",
                          "Sie sinkt automatisch im gleichen Verhältnis wie die Nachfrage"],
                explanation: "Mit steigendem Preis lohnt sich für die Anbieter eine höhere Produktion, das Angebot steigt."),
        .choice(id: "wir-c04", topic: .wirtschaft,
                prompt: "Was passiert auf einem Markt bei einem Nachfrageüberhang, wenn also die nachgefragte Menge das Angebot übersteigt?",
                options: ["Der Preis steigt tendenziell, bis sich Angebot und Nachfrage wieder annähern",
                          "Der Preis sinkt, weil Anbieter ihre Ware loswerden wollen",
                          "Der Preis bleibt zwangsläufig unverändert",
                          "Der Staat muss den Preis festsetzen",
                          "Die Anbieter müssen das Gut verschenken"],
                explanation: "Bei einem Nachfrageüberhang übersteigt die Nachfrage das Angebot, wodurch der Preis tendenziell steigt."),
        .choice(id: "wir-c05", topic: .wirtschaft,
                prompt: "Was passiert auf einem Markt bei einem Angebotsüberhang?",
                options: ["Der Preis sinkt tendenziell, weil Anbieter ihre Ware verkaufen wollen",
                          "Der Preis steigt, weil Anbieter knapper werden",
                          "Der Preis bleibt zwangsläufig konstant",
                          "Die Nachfrager müssen zusätzlich zahlen",
                          "Der Markt wird automatisch staatlich reguliert"],
                explanation: "Übersteigt das Angebot die Nachfrage, sinkt der Preis tendenziell, bis sich ein neues Gleichgewicht einstellt."),
        .choice(id: "wir-c06", topic: .wirtschaft,
                prompt: "Wie wird ein Markt bezeichnet, auf dem die Nachfrage größer ist als das Angebot?",
                options: ["Verkäufermarkt", "Käufermarkt", "Vollkommener Markt", "Schwarzmarkt", "Monopolmarkt"],
                explanation: "Auf einem Verkäufermarkt übersteigt die Nachfrage das Angebot, die Verkäufer sitzen am längeren Hebel."),
        .choice(id: "wir-c07", topic: .wirtschaft,
                prompt: "Wie wird ein Markt bezeichnet, auf dem das Angebot größer ist als die Nachfrage?",
                options: ["Käufermarkt", "Verkäufermarkt", "Vollkommener Markt", "Monopolmarkt", "Regulierter Markt"],
                explanation: "Auf einem Käufermarkt übersteigt das Angebot die Nachfrage, die Käufer können Preise eher drücken."),
        .choice(id: "wir-c08", topic: .wirtschaft,
                prompt: "Welche Voraussetzung gehört zu einem vollkommenen Markt?",
                options: ["Die Güter sind homogen und alle Marktteilnehmer haben vollständige Markttransparenz",
                          "Es gibt genau einen Anbieter, der den Preis bestimmt",
                          "Käufer bevorzugen bestimmte Anbieter aus persönlichen Gründen",
                          "Die Reaktion auf Preisänderungen erfolgt erst nach mehreren Wochen",
                          "Es bestehen räumliche Präferenzen der Käufer"],
                explanation: "Ein vollkommener Markt setzt homogene Güter, vollständige Transparenz, keine Präferenzen und eine sofortige Reaktion auf Preisänderungen voraus – ein theoretisches Modell."),
        .choice(id: "wir-c09", topic: .wirtschaft,
                prompt: "Wie nennt man eine Marktform mit vielen Anbietern und vielen Nachfragern?",
                options: ["Polypol", "Oligopol", "Monopol", "Monopson", "Duopol"],
                explanation: "Beim Polypol stehen viele Anbieter vielen Nachfragern gegenüber, keiner kann den Preis allein bestimmen."),
        .choice(id: "wir-c10", topic: .wirtschaft,
                prompt: "Ein fiktiver Markt für Mobilfunknetze wird von nur drei großen Anbietern dominiert. Um welche Marktform handelt es sich?",
                options: ["Oligopol", "Polypol", "Monopol", "Vollkommener Markt", "Käufermarkt"],
                explanation: "Beim Oligopol teilen sich wenige Anbieter den Markt und beeinflussen sich gegenseitig stark."),
        .choice(id: "wir-c11", topic: .wirtschaft,
                prompt: "Wie nennt man eine Marktform mit nur einem einzigen Anbieter eines Gutes?",
                options: ["Monopol", "Oligopol", "Polypol", "Kartell", "Duopol"],
                explanation: "Im Monopol gibt es nur einen Anbieter, der den Preis weitgehend allein bestimmen kann."),
        .choice(id: "wir-c12", topic: .wirtschaft,
                prompt: "Was kennzeichnet die soziale Marktwirtschaft in Deutschland?",
                options: ["Freier Wettbewerb wird mit sozialem Ausgleich und staatlicher Ordnungspolitik verbunden",
                          "Der Staat legt alle Preise und Produktionsmengen zentral fest",
                          "Es gibt kein Privateigentum an Produktionsmitteln",
                          "Löhne werden ausschließlich vom Staat festgelegt",
                          "Wettbewerb ist gesetzlich verboten"],
                explanation: "Die soziale Marktwirtschaft verbindet die freie Marktwirtschaft mit sozialem Ausgleich, Wettbewerbsschutz und sozialer Sicherung."),
        .choice(id: "wir-c13", topic: .wirtschaft,
                prompt: "Was ist ein zentrales Merkmal der Zentralverwaltungswirtschaft?",
                options: ["Der Staat plant Produktion, Preise und Verteilung zentral, es gibt kaum privates Eigentum an Produktionsmitteln",
                          "Angebot und Nachfrage bestimmen frei die Preise",
                          "Unternehmen konkurrieren frei um Kunden",
                          "Der Staat greift überhaupt nicht in die Wirtschaft ein",
                          "Gewerkschaften handeln die Preise mit dem Staat aus"],
                explanation: "In der Zentralverwaltungswirtschaft trifft der Staat die wesentlichen wirtschaftlichen Entscheidungen zentral, im Gegensatz zur freien Marktwirtschaft."),
        .choice(id: "wir-c14", topic: .wirtschaft,
                prompt: "Was fließt im einfachen Wirtschaftskreislauf von den privaten Haushalten zu den Unternehmen?",
                options: ["Konsumausgaben für Güter und Dienstleistungen sowie Faktorleistungen wie Arbeit",
                          "Nur Steuern und Abgaben",
                          "Nur Kredite der Banken",
                          "Nur Subventionen des Staates",
                          "Nur Exporterlöse"],
                explanation: "Haushalte stellen Unternehmen Faktorleistungen wie Arbeit zur Verfügung und zahlen für Güter, im Gegenzug erhalten sie Einkommen."),
        .choice(id: "wir-c15", topic: .wirtschaft,
                prompt: "Welche Geldströme fließen typischerweise zwischen Staat und privaten Haushalten im Wirtschaftskreislauf?",
                options: ["Steuern von den Haushalten an den Staat, Transferzahlungen wie Kindergeld vom Staat an die Haushalte",
                          "Ausschließlich Kredite der Haushalte an den Staat",
                          "Ausschließlich Exporterlöse",
                          "Nur Löhne des Staates an alle Unternehmen",
                          "Nur Sparzinsen der Banken"],
                explanation: "Haushalte zahlen Steuern an den Staat, der Staat zahlt u. a. Transferleistungen wie Kindergeld zurück an die Haushalte."),
        .choice(id: "wir-c16", topic: .wirtschaft,
                prompt: "Was fließt bei einem Export in der Betrachtung des Wirtschaftskreislaufs vom Ausland ins Inland?",
                options: ["Geld als Gegenleistung für die exportierten Güter und Dienstleistungen",
                          "Nur Güter, aber kein Geld",
                          "Steuern für den Staat",
                          "Nur Arbeitskräfte",
                          "Kein Geldstrom, da Export steuerfrei ist"],
                explanation: "Beim Export erhält das Inland Geld vom Ausland, beim Import fließt Geld ins Ausland ab."),
        .choice(id: "wir-c17", topic: .wirtschaft,
                prompt: "Welche vier Ziele nennt das Stabilitätsgesetz im sogenannten magischen Viereck?",
                options: ["Preisniveaustabilität, hoher Beschäftigungsstand, außenwirtschaftliches Gleichgewicht, stetiges Wirtschaftswachstum",
                          "Niedrige Steuern, hohe Exporte, niedrige Zinsen, hohe Aktienkurse",
                          "Vollbeschäftigung, hohe Inflation, hohe Staatsverschuldung, ein starker Euro",
                          "Nur Preisstabilität und Wirtschaftswachstum",
                          "Hohe Löhne, kurze Arbeitszeit, viele Feiertage, hohe Renten"],
                explanation: "Das Stabilitätsgesetz von 1967 nennt diese vier gleichrangigen Ziele der Wirtschaftspolitik."),
        .choice(id: "wir-c18", topic: .wirtschaft,
                prompt: "Was versteht man unter einem Zielkonflikt im magischen Viereck?",
                options: ["Die Verfolgung eines Ziels erschwert die Erreichung eines anderen Ziels, z. B. Wachstum und Umweltschutz",
                          "Alle vier Ziele lassen sich immer gleichzeitig vollständig erreichen",
                          "Ziele der Wirtschaftspolitik widersprechen sich nie",
                          "Ein Zielkonflikt entsteht nur zwischen zwei privaten Unternehmen",
                          "Zielkonflikte betreffen ausschließlich die Geldpolitik der EZB"],
                explanation: "Zielkonflikte entstehen, wenn sich Ziele gegenseitig beeinträchtigen, etwa Vollbeschäftigung und Preisstabilität."),
        .choice(id: "wir-c19", topic: .wirtschaft,
                prompt: "Was ist typisch für die Konjunkturphase der Hochkonjunktur (Boom)?",
                options: ["Hohe Auslastung der Kapazitäten, steigende Preise und niedrige Arbeitslosigkeit",
                          "Sinkende Produktion und stark steigende Arbeitslosigkeit",
                          "Sinkende Preise bei hoher Arbeitslosigkeit",
                          "Stagnierende Preise ohne jede Nachfrage",
                          "Ausschließlich fallende Löhne"],
                explanation: "Im Boom sind die Kapazitäten hoch ausgelastet, die Preise steigen tendenziell und die Arbeitslosigkeit ist niedrig."),
        .choice(id: "wir-c20", topic: .wirtschaft,
                prompt: "Was ist typisch für die Konjunkturphase des Abschwungs (Rezession)?",
                options: ["Die Produktion und die Nachfrage gehen zurück, die Arbeitslosigkeit beginnt zu steigen",
                          "Die Kapazitäten sind voll ausgelastet",
                          "Die Preise steigen besonders stark",
                          "Die Arbeitslosigkeit sinkt kontinuierlich",
                          "Unternehmen investieren verstärkt in neue Kapazitäten"],
                explanation: "In der Rezession gehen Produktion und Nachfrage zurück, wodurch die Arbeitslosigkeit tendenziell steigt."),
        .choice(id: "wir-c21", topic: .wirtschaft,
                prompt: "Welcher Wert gilt als Frühindikator für die konjunkturelle Entwicklung?",
                options: ["Die Auftragseingänge der Unternehmen",
                          "Die Arbeitslosenquote",
                          "Der Verbraucherpreisindex des Vorjahres",
                          "Die Höhe der Staatsverschuldung",
                          "Die Zahl der Unternehmensinsolvenzen des Vorjahres"],
                explanation: "Auftragseingänge gelten als Frühindikator, weil sie künftige Produktion ankündigen; die Arbeitslosenquote reagiert dagegen erst verzögert."),
        .choice(id: "wir-c22", topic: .wirtschaft,
                prompt: "Welcher Wert gilt als Spätindikator für die konjunkturelle Entwicklung?",
                options: ["Die Arbeitslosenquote",
                          "Die Auftragseingänge der Industrie",
                          "Der Geschäftsklimaindex",
                          "Die Investitionsabsichten der Unternehmen",
                          "Die Baugenehmigungen"],
                explanation: "Die Arbeitslosenquote reagiert erst mit Verzögerung auf konjunkturelle Veränderungen und gilt daher als Spätindikator."),
        .choice(id: "wir-c23", topic: .wirtschaft,
                prompt: "Wie verhält sich der Staat bei einer antizyklischen Fiskalpolitik im Abschwung?",
                options: ["Er erhöht die Staatsausgaben oder senkt Steuern, um die Nachfrage zu stärken",
                          "Er senkt die Staatsausgaben und erhöht gleichzeitig die Steuern",
                          "Er greift überhaupt nicht in die Wirtschaft ein",
                          "Er erhöht nur den Leitzins",
                          "Er verstaatlicht alle Unternehmen"],
                explanation: "Antizyklische Fiskalpolitik wirkt dem Konjunkturverlauf entgegen: im Abschwung wird die Nachfrage durch mehr Ausgaben oder niedrigere Steuern gestärkt, im Boom umgekehrt gebremst."),
        .choice(id: "wir-c24", topic: .wirtschaft,
                prompt: "Was ist eine typische Folge, wenn die EZB den Leitzins erhöht?",
                options: ["Kredite werden teurer, Sparen wird attraktiver, die Nachfrage und damit die Inflation werden gedämpft",
                          "Kredite werden günstiger und die Nachfrage steigt weiter an",
                          "Die Inflation steigt automatisch weiter an",
                          "Der Leitzins hat keinen Einfluss auf Kredite",
                          "Unternehmen investieren dadurch automatisch mehr"],
                explanation: "Ein höherer Leitzins verteuert Kredite und macht Sparen attraktiver, wodurch die Nachfrage und damit die Inflation gedämpft werden sollen."),
        .choice(id: "wir-c25", topic: .wirtschaft,
                prompt: "Womit wird die Inflationsrate in Deutschland vor allem gemessen?",
                options: ["Mit dem Verbraucherpreisindex anhand eines Warenkorbs typischer Güter und Dienstleistungen",
                          "Mit der Höhe des Leitzinses der EZB",
                          "Mit der Arbeitslosenquote",
                          "Mit dem Außenwert des Euro",
                          "Mit der Höhe der Staatsverschuldung"],
                explanation: "Das Statistische Bundesamt ermittelt den Verbraucherpreisindex anhand eines repräsentativen Warenkorbs; seine Veränderung zeigt die Inflationsrate."),
        .choice(id: "wir-c26", topic: .wirtschaft,
                prompt: "Der Nominallohn von Frau Bartels steigt um 4 %, die Inflationsrate liegt bei 5 %. Was passiert mit ihrem Reallohn?",
                options: ["Er sinkt um etwa 1 %, da die Preise stärker steigen als der Lohn",
                          "Er steigt um etwa 9 %",
                          "Er bleibt exakt gleich",
                          "Er steigt um genau 4 %",
                          "Er sinkt um 5 %"],
                explanation: "Der Reallohn ergibt sich näherungsweise aus der Nominallohnänderung abzüglich der Inflationsrate: 4 % − 5 % ≈ −1 %."),
        .choice(id: "wir-c27", topic: .wirtschaft,
                prompt: "Was ist eine typische Ursache der Globalisierung?",
                options: ["Sinkende Transport- und Kommunikationskosten sowie der Abbau von Handelshemmnissen",
                          "Steigende Zölle zwischen fast allen Staaten",
                          "Der vollständige Rückzug der Unternehmen aus internationalen Märkten",
                          "Die Abschaffung des Welthandels",
                          "Strengere Einreisebestimmungen weltweit"],
                explanation: "Globalisierung wird u. a. durch sinkende Transport- und Kommunikationskosten, Digitalisierung und den Abbau von Handelshemmnissen, etwa durch die WTO, begünstigt."),
        .choice(id: "wir-c28", topic: .wirtschaft,
                prompt: "Welche vier Grundfreiheiten bilden den EU-Binnenmarkt?",
                options: ["Freier Waren-, Personen-, Dienstleistungs- und Kapitalverkehr",
                          "Freier Waren-, Steuer-, Wohnungs- und Sprachverkehr",
                          "Nur der freie Warenverkehr und die Dienstleistungsfreiheit",
                          "Freizügigkeit für Waren, Militär, Energie und Daten",
                          "Freier Verkehr von Waren, Wetten, Renten und Krediten"],
                explanation: "Der EU-Binnenmarkt beruht auf den vier Grundfreiheiten: Waren-, Personen-, Dienstleistungs- und Kapitalverkehr."),
        .choice(id: "wir-c29", topic: .wirtschaft,
                prompt: "Was bedeutet die Arbeitnehmerfreizügigkeit innerhalb der EU?",
                options: ["EU-Bürger dürfen ohne Arbeitserlaubnis in jedem Mitgliedstaat arbeiten und werden dabei Einheimischen gleichgestellt",
                          "Nur hochqualifizierte Fachkräfte dürfen im EU-Ausland arbeiten",
                          "Arbeitnehmer benötigen für jeden EU-Staat eine eigene Arbeitserlaubnis",
                          "Arbeitnehmerfreizügigkeit gilt nur für Studierende",
                          "Sie gilt nur innerhalb des eigenen Mitgliedstaats"],
                explanation: "Die Arbeitnehmerfreizügigkeit ist Teil der Personenfreizügigkeit: EU-Bürger dürfen ohne Arbeitserlaubnis in jedem Mitgliedstaat arbeiten."),
        .choice(id: "wir-c30", topic: .wirtschaft,
                prompt: "Was unterscheidet eine EU-Verordnung von einer EU-Richtlinie?",
                options: ["Die Verordnung gilt unmittelbar in allen Mitgliedstaaten, die Richtlinie muss erst in nationales Recht umgesetzt werden",
                          "Beide gelten immer erst nach Umsetzung durch die nationalen Parlamente",
                          "Die Richtlinie gilt unmittelbar, die Verordnung muss erst umgesetzt werden",
                          "Eine Richtlinie ist rechtlich unverbindlich",
                          "Nur Verordnungen werden vom Europäischen Parlament beschlossen"],
                explanation: "EU-Verordnungen, etwa die DSGVO, gelten unmittelbar, EU-Richtlinien müssen erst durch nationale Gesetze umgesetzt werden."),
        .choice(id: "wir-c31", topic: .wirtschaft,
                prompt: "Wer wird als Sozialpartner (Tarifparteien) bezeichnet?",
                options: ["Gewerkschaften und Arbeitgeberverbände bzw. einzelne Arbeitgeber",
                          "Betriebsrat und Geschäftsführung",
                          "Bundesregierung und IHK",
                          "Finanzamt und Unternehmen",
                          "Aufsichtsrat und Vorstand"],
                explanation: "Sozialpartner (Tarifparteien) sind Gewerkschaften auf der einen und Arbeitgeberverbände bzw. einzelne Arbeitgeber auf der anderen Seite."),

        // Statements
        .statement(id: "wir-s01", topic: .wirtschaft,
                   text: "Steigt der Preis eines Gutes, sinkt in der Regel die nachgefragte Menge.",
                   isTrue: true,
                   explanation: "Das ist das grundlegende Gesetz der Nachfrage."),
        .statement(id: "wir-s02", topic: .wirtschaft,
                   text: "Ein Nachfrageüberhang führt tendenziell zu sinkenden Preisen.",
                   isTrue: false,
                   explanation: "Ein Nachfrageüberhang führt tendenziell zu steigenden Preisen, nicht zu sinkenden."),
        .statement(id: "wir-s03", topic: .wirtschaft,
                   text: "Auf einem vollkommenen Markt reagieren alle Marktteilnehmer sofort auf Preisänderungen.",
                   isTrue: true,
                   explanation: "Die sofortige Reaktion auf Preisänderungen gehört zu den Merkmalen des vollkommenen Marktes."),
        .statement(id: "wir-s04", topic: .wirtschaft,
                   text: "Ein Polypol ist eine Marktform mit nur einem einzigen Anbieter.",
                   isTrue: false,
                   explanation: "Nur ein Anbieter kennzeichnet das Monopol, das Polypol hat viele Anbieter."),
        .statement(id: "wir-s05", topic: .wirtschaft,
                   text: "Die soziale Marktwirtschaft verbindet freien Wettbewerb mit sozialem Ausgleich.",
                   isTrue: true,
                   explanation: "Das ist das Grundprinzip der sozialen Marktwirtschaft in Deutschland."),
        .statement(id: "wir-s06", topic: .wirtschaft,
                   text: "In der Zentralverwaltungswirtschaft bestimmen Angebot und Nachfrage frei die Preise.",
                   isTrue: false,
                   explanation: "In der Zentralverwaltungswirtschaft plant der Staat Produktion und Preise zentral."),
        .statement(id: "wir-s07", topic: .wirtschaft,
                   text: "Im Wirtschaftskreislauf fließen Steuern von den Haushalten an den Staat.",
                   isTrue: true,
                   explanation: "Steuern sind einer der zentralen Geldströme zwischen Haushalten und Staat."),
        .statement(id: "wir-s08", topic: .wirtschaft,
                   text: "Das magische Viereck nennt vier gleichrangige Ziele der Wirtschaftspolitik.",
                   isTrue: true,
                   explanation: "Preisniveaustabilität, Beschäftigung, außenwirtschaftliches Gleichgewicht und Wirtschaftswachstum sind gleichrangig."),
        .statement(id: "wir-s09", topic: .wirtschaft,
                   text: "Ziele des magischen Vierecks stehen nie in einem Zielkonflikt zueinander.",
                   isTrue: false,
                   explanation: "Ziele wie Wachstum und Umweltschutz oder Vollbeschäftigung und Preisstabilität können sich gegenseitig beeinträchtigen."),
        .statement(id: "wir-s10", topic: .wirtschaft,
                   text: "In der Hochkonjunktur sind die Kapazitäten der Unternehmen meist hoch ausgelastet.",
                   isTrue: true,
                   explanation: "Hohe Auslastung ist typisch für den Boom."),
        .statement(id: "wir-s11", topic: .wirtschaft,
                   text: "Die Arbeitslosenquote gilt als Frühindikator der Konjunktur.",
                   isTrue: false,
                   explanation: "Die Arbeitslosenquote reagiert verzögert und gilt daher als Spätindikator; Auftragseingänge sind ein Frühindikator."),
        .statement(id: "wir-s12", topic: .wirtschaft,
                   text: "Antizyklische Fiskalpolitik erhöht im Abschwung die Staatsausgaben oder senkt die Steuern.",
                   isTrue: true,
                   explanation: "So soll die Nachfrage im Abschwung gestärkt werden."),
        .statement(id: "wir-s13", topic: .wirtschaft,
                   text: "Die EZB verfolgt als vorrangiges Ziel Preisniveaustabilität.",
                   isTrue: true,
                   explanation: "Das Inflationsziel der EZB liegt mittelfristig bei 2 %."),
        .statement(id: "wir-s14", topic: .wirtschaft,
                   text: "Eine Leitzinserhöhung der EZB macht Kredite tendenziell günstiger.",
                   isTrue: false,
                   explanation: "Eine Leitzinserhöhung verteuert Kredite, sie werden nicht günstiger."),
        .statement(id: "wir-s15", topic: .wirtschaft,
                   text: "Inflation bedeutet einen anhaltenden Anstieg des allgemeinen Preisniveaus.",
                   isTrue: true,
                   explanation: "Das ist die Definition von Inflation, gemessen mit dem Verbraucherpreisindex."),
        .statement(id: "wir-s16", topic: .wirtschaft,
                   text: "Bei Inflation gewinnen tendenziell Sparer und verlieren Schuldner.",
                   isTrue: false,
                   explanation: "Bei Inflation ist es umgekehrt: Schuldner profitieren, weil sie mit entwertetem Geld zurückzahlen, Gläubiger und Sparer verlieren Kaufkraft."),

        // Multiple
        .multiple(id: "wir-m01", topic: .wirtschaft,
                  prompt: "Wähle alle Merkmale aus, die zu einem vollkommenen Markt gehören.",
                  correct: ["Homogene Güter ohne Unterschiede",
                            "Vollständige Markttransparenz",
                            "Keine persönlichen, räumlichen oder zeitlichen Präferenzen",
                            "Sofortige Reaktion auf Preisänderungen"],
                  wrong: ["Ein einzelner Anbieter bestimmt den Preis",
                          "Kunden bevorzugen bestimmte Marken",
                          "Die Reaktion auf Preisänderungen erfolgt erst nach Wochen"],
                  explanation: "Diese vier Merkmale kennzeichnen den theoretischen vollkommenen Markt; Präferenzen einzelner Anbieter oder verzögerte Reaktionen widersprechen dem."),
        .multiple(id: "wir-m02", topic: .wirtschaft,
                  prompt: "Wähle alle Ziele aus, die im magischen Viereck des Stabilitätsgesetzes genannt werden.",
                  correct: ["Preisniveaustabilität",
                            "Hoher Beschäftigungsstand",
                            "Außenwirtschaftliches Gleichgewicht",
                            "Stetiges und angemessenes Wirtschaftswachstum"],
                  wrong: ["Niedrige Unternehmenssteuern",
                          "Ein möglichst schwacher Euro",
                          "Hohe Aktienkurse"],
                  explanation: "Das Stabilitätsgesetz von 1967 nennt genau diese vier gleichrangigen Ziele der Wirtschaftspolitik."),
        .multiple(id: "wir-m03", topic: .wirtschaft,
                  prompt: "Wähle alle Aussagen aus, die für die Konjunkturphase der Hochkonjunktur zutreffen.",
                  correct: ["Die Kapazitäten sind hoch ausgelastet",
                            "Die Preise steigen tendenziell",
                            "Die Arbeitslosigkeit ist niedrig"],
                  wrong: ["Die Produktion geht deutlich zurück",
                          "Die Arbeitslosigkeit steigt stark an",
                          "Unternehmen bauen massiv Personal ab"],
                  explanation: "Hochkonjunktur ist durch hohe Auslastung, steigende Preise und niedrige Arbeitslosigkeit gekennzeichnet – das Gegenteil einer Rezession."),
        .multiple(id: "wir-m04", topic: .wirtschaft,
                  prompt: "Wähle alle Aussagen aus, die zu den vier Grundfreiheiten des EU-Binnenmarkts zählen.",
                  correct: ["Freier Warenverkehr",
                            "Freizügigkeit für Personen",
                            "Dienstleistungsfreiheit",
                            "Freier Kapital- und Zahlungsverkehr"],
                  wrong: ["Freie Wahl der Amtssprache in jedem Mitgliedstaat",
                          "Steuerfreiheit für alle EU-Bürger",
                          "Einheitliche Löhne in allen Mitgliedstaaten"],
                  explanation: "Die vier Grundfreiheiten des EU-Binnenmarkts sind Waren-, Personen-, Dienstleistungs- und Kapitalverkehr."),

        // Match
        .match(id: "wir-p01", topic: .wirtschaft,
               prompt: "Ordne die Situation der passenden Konjunkturphase zu.",
               pairs: [("Auftragsbücher sind voll, Unternehmen investieren kräftig, Preise steigen", "Hochkonjunktur"),
                       ("Nachfrage und Produktion gehen zurück, erste Entlassungen", "Abschwung"),
                       ("Arbeitslosigkeit ist hoch, Investitionen bleiben aus", "Tiefstand"),
                       ("Produktion und Beschäftigung nehmen wieder zu", "Aufschwung")],
               extra: ["Deflation"],
               explanation: "Die vier Konjunkturphasen Aufschwung, Hochkonjunktur, Abschwung und Tiefstand lassen sich an typischen Situationen erkennen."),
        .match(id: "wir-p02", topic: .wirtschaft,
               prompt: "Ordne den Geldstrom dem passenden Sektor-Paar im Wirtschaftskreislauf zu.",
               pairs: [("Arbeitnehmer erhält Lohn für seine Arbeitsleistung", "Unternehmen → Haushalte"),
                       ("Haushalt kauft Lebensmittel im Supermarkt", "Haushalte → Unternehmen"),
                       ("Staat zahlt Kindergeld an eine Familie", "Staat → Haushalte"),
                       ("Unternehmen zahlt Umsatzsteuer ans Finanzamt", "Unternehmen → Staat"),
                       ("Bank vergibt einen Kredit an ein Unternehmen", "Banken → Unternehmen")],
               extra: ["Ausland → Staat"],
               explanation: "Im Wirtschaftskreislauf lassen sich Geldströme den beteiligten Sektoren Haushalte, Unternehmen, Staat und Banken eindeutig zuordnen."),
        .match(id: "wir-p03", topic: .wirtschaft,
               prompt: "Ordne das Merkmal der passenden Marktform zu.",
               pairs: [("Viele Anbieter, viele Nachfrager, niemand kann den Preis bestimmen", "Polypol"),
                       ("Wenige große Anbieter beeinflussen sich gegenseitig stark", "Oligopol"),
                       ("Nur ein Anbieter bestimmt den Preis weitgehend allein", "Monopol")],
               extra: ["Vollkommener Markt"],
               explanation: "Die Marktformen unterscheiden sich vor allem in der Zahl der Anbieter und ihrer Marktmacht."),
        .match(id: "wir-p04", topic: .wirtschaft,
               prompt: "Ordne das Beispiel der passenden EU-Grundfreiheit zu.",
               pairs: [("Ein Ingenieur aus Polen arbeitet ohne Arbeitserlaubnis in Deutschland", "Personenfreizügigkeit"),
                       ("Ein deutsches Unternehmen verkauft Maschinen ohne Zoll nach Frankreich", "Warenverkehrsfreiheit"),
                       ("Eine IT-Beraterin aus Österreich erbringt Leistungen für einen Kunden in Italien", "Dienstleistungsfreiheit"),
                       ("Ein Sparer legt sein Geld bei einer Bank in Spanien an", "Kapitalverkehrsfreiheit")],
               extra: [],
               explanation: "Jede der vier Grundfreiheiten lässt sich an einem typischen grenzüberschreitenden Beispiel festmachen."),
        .match(id: "wir-p05", topic: .wirtschaft,
               prompt: "Ordne der Aufgabe das passende EU-Organ zu.",
               pairs: [("Schlägt neue EU-Gesetze vor", "Europäische Kommission"),
                       ("Wird von den Bürgerinnen und Bürgern direkt gewählt", "Europäisches Parlament"),
                       ("Legt den Leitzins für die Eurozone fest", "Europäische Zentralbank"),
                       ("Entscheidet über die Auslegung des EU-Rechts", "Europäischer Gerichtshof")],
               extra: ["Bundeskartellamt"],
               explanation: "Die EU-Organe haben klar getrennte Aufgaben von der Gesetzesinitiative über die Gesetzgebung bis zur Rechtsprechung."),

        // Order
        .order(id: "wir-o01", topic: .wirtschaft,
               prompt: "Bringe den klassischen Konjunkturzyklus ausgehend vom Tiefstand in die richtige Reihenfolge.",
               steps: ["Tiefstand: Arbeitslosigkeit hoch, Investitionen bleiben aus",
                       "Aufschwung: Produktion und Beschäftigung nehmen wieder zu",
                       "Hochkonjunktur: Kapazitäten hoch ausgelastet, Preise steigen",
                       "Abschwung: Nachfrage und Produktion gehen zurück"],
               explanation: "Der klassische Konjunkturzyklus durchläuft ausgehend vom Tiefstand die Phasen Aufschwung, Hochkonjunktur und Abschwung, bevor er erneut im Tiefstand endet."),
        .order(id: "wir-o02", topic: .wirtschaft,
               prompt: "Bringe die Wirkungskette einer Leitzinserhöhung der EZB in die richtige Reihenfolge.",
               steps: ["Die EZB erhöht den Leitzins",
                       "Banken erhöhen die Zinsen für Kredite und Sparanlagen",
                       "Kredite werden teurer, Sparen wird attraktiver",
                       "Konsum- und Investitionsnachfrage gehen zurück",
                       "Die Inflation wird gedämpft"],
               explanation: "Über diese Wirkungskette versucht die EZB, mit einer Leitzinserhöhung die Inflation zu bremsen."),

        // Gap
        .gap(id: "wir-g01", topic: .wirtschaft, title: "Markt und Preisbildung",
             sentences: [("Der Preis, bei dem sich angebotene und nachgefragte Menge entsprechen, heißt ___.", "Gleichgewichtspreis"),
                         ("Übersteigt die Nachfrage das Angebot, spricht man von einem ___.", "Nachfrageüberhang"),
                         ("Ein Markt mit vielen Anbietern und vielen Nachfragern heißt ___.", "Polypol"),
                         ("Gibt es nur einen einzigen Anbieter eines Gutes, spricht man von einem ___.", "Monopol")],
             extra: ["Angebotsüberhang", "Oligopol"],
             explanation: "Die Begriffe beschreiben die grundlegende Preisbildung und die Marktformen im Modell von Angebot und Nachfrage."),
        .gap(id: "wir-g02", topic: .wirtschaft, title: "Konjunktur und Geldpolitik",
             sentences: [("Die Phase mit hoher Auslastung und steigenden Preisen heißt ___.", "Hochkonjunktur"),
                         ("Auftragseingänge gelten als ___ für die Konjunkturentwicklung.", "Frühindikator"),
                         ("Erhöht der Staat im Abschwung die Ausgaben, spricht man von ___ Fiskalpolitik.", "antizyklischer"),
                         ("Die EZB verfolgt als vorrangiges Ziel die ___.", "Preisniveaustabilität")],
             extra: ["Spätindikator", "Rezession"],
             explanation: "Die Begriffe ordnen Konjunkturphasen, Indikatoren und die Geldpolitik der EZB richtig ein."),
        .gap(id: "wir-g03", topic: .wirtschaft, title: "EU und Globalisierung",
             sentences: [("Der EU-Binnenmarkt beruht auf vier ___.", "Grundfreiheiten"),
                         ("EU-Bürger dürfen dank der Arbeitnehmerfreizügigkeit ohne Arbeitserlaubnis in jedem Mitgliedstaat ___.", "arbeiten"),
                         ("Eine EU-___ gilt unmittelbar in allen Mitgliedstaaten, ohne dass sie erst umgesetzt werden muss.", "Verordnung"),
                         ("Eine EU-Richtlinie muss erst in nationales ___ umgesetzt werden.", "Recht")],
             extra: ["Gesetz", "Abkommen"],
             explanation: "Die Begriffe beschreiben zentrale Grundlagen des EU-Binnenmarkts und den Unterschied zwischen Verordnung und Richtlinie."),

        // Facts
        .fact(id: "wir-f01", topic: .wirtschaft, group: ExamCatalog.Group.stelle,
              question: "Welche Institution legt den Leitzins für die Eurozone fest?",
              answer: "Europäische Zentralbank (EZB)",
              explanation: "Die EZB steuert über den Leitzins die Geldpolitik im Euroraum mit dem vorrangigen Ziel der Preisniveaustabilität."),
        .fact(id: "wir-f02", topic: .wirtschaft, group: ExamCatalog.Group.stelle,
              question: "Welches EU-Organ schlägt neue EU-Gesetze vor?",
              answer: "Europäische Kommission",
              explanation: "Die Europäische Kommission hat als einziges EU-Organ das Initiativrecht für Gesetzesvorschläge."),
        .fact(id: "wir-f03", topic: .wirtschaft, group: ExamCatalog.Group.stelle,
              question: "Welches Amt ermittelt in Deutschland den Verbraucherpreisindex?",
              answer: "Statistisches Bundesamt",
              explanation: "Das Statistische Bundesamt erhebt monatlich die Preise eines Warenkorbs und berechnet daraus den Verbraucherpreisindex."),
        .fact(id: "wir-f04", topic: .wirtschaft, group: ExamCatalog.Group.stelle,
              question: "Wie heißt der Dachverband der deutschen Gewerkschaften?",
              answer: "DGB (Deutscher Gewerkschaftsbund)",
              explanation: "Der DGB ist der Dachverband der deutschen Einzelgewerkschaften wie ver.di oder IG Metall."),
        .fact(id: "wir-f05", topic: .wirtschaft, group: ExamCatalog.Group.stelle,
              question: "Wie heißt der Dachverband der deutschen Arbeitgeberverbände?",
              answer: "BDA (Bundesvereinigung der Deutschen Arbeitgeberverbände)",
              explanation: "Die BDA bündelt die Interessen der Arbeitgeberverbände auf Bundesebene, als Gegenstück zum DGB."),
        .fact(id: "wir-f06", topic: .wirtschaft, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Grundfreiheiten hat der EU-Binnenmarkt?",
              answer: "4",
              explanation: "Waren-, Personen-, Dienstleistungs- und Kapitalverkehr sind die vier Grundfreiheiten des EU-Binnenmarkts."),
        .fact(id: "wir-f07", topic: .wirtschaft, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Mitgliedstaaten hat die Europäische Union (Stand 2026)?",
              answer: "27",
              explanation: "Die EU besteht Stand 2026 aus 27 Mitgliedstaaten."),
        .fact(id: "wir-f08", topic: .wirtschaft, group: ExamCatalog.Group.prozent,
              question: "Auf welchen Wert hat die EZB ihr mittelfristiges Inflationsziel festgelegt?",
              answer: "2 %",
              explanation: "Die EZB strebt mittelfristig eine Inflationsrate von 2 % an, um Preisniveaustabilität zu gewährleisten."),
    ]

    // MARK: - Nachhaltigkeit & Umwelt

    static let nachhaltigkeit: [ExamCard] = [
        // Choice
        .choice(id: "nac-c01", topic: .nachhaltigkeit,
                prompt: "Welche drei Dimensionen umfasst das Drei-Säulen-Modell der Nachhaltigkeit?",
                options: ["Ökologische, ökonomische und soziale Dimension",
                          "Politische, rechtliche und technische Dimension",
                          "Nur ökologische und ökonomische Dimension",
                          "Lokale, nationale und globale Dimension",
                          "Ökologische, digitale und finanzielle Dimension"],
                explanation: "Nachhaltigkeit wird klassischerweise in eine ökologische, ökonomische und soziale Dimension unterteilt."),
        .choice(id: "nac-c02", topic: .nachhaltigkeit,
                prompt: "Woher stammt der ursprüngliche Gedanke der Nachhaltigkeit?",
                options: ["Aus der Forstwirtschaft: Es sollte nur so viel Holz geschlagen werden, wie nachwachsen kann",
                          "Aus der Automobilindustrie des 20. Jahrhunderts",
                          "Aus dem internationalen Finanzwesen",
                          "Aus der Informatik",
                          "Aus der Landwirtschaft der Antike"],
                explanation: "Der Begriff Nachhaltigkeit geht auf die Forstwirtschaft zurück, in der nur so viel Holz genutzt werden sollte, wie nachwachsen kann."),
        .choice(id: "nac-c03", topic: .nachhaltigkeit,
                prompt: "Was sind die SDGs der Agenda 2030 der Vereinten Nationen?",
                options: ["17 Ziele für eine nachhaltige Entwicklung weltweit",
                          "Ein Klimaabkommen der EU-Staaten",
                          "Die Umweltgesetze Deutschlands",
                          "Ein Förderprogramm nur für Entwicklungsländer",
                          "Die Grundsätze der Kreislaufwirtschaft in Deutschland"],
                explanation: "Die Agenda 2030 der Vereinten Nationen enthält 17 Sustainable Development Goals (SDGs) für nachhaltige Entwicklung."),
        .choice(id: "nac-c04", topic: .nachhaltigkeit,
                prompt: "Was beschreibt der sogenannte Erdüberlastungstag (Earth Overshoot Day)?",
                options: ["Den Tag im Jahr, an dem die Menschheit rechnerisch alle Ressourcen verbraucht hat, die die Erde in diesem Jahr regenerieren kann",
                          "Den Tag, an dem weltweit die meisten Naturkatastrophen auftreten",
                          "Den letzten Tag des Geschäftsjahres vieler Unternehmen",
                          "Den Tag, an dem die meisten Länder ihre Klimaziele veröffentlichen",
                          "Den Tag, an dem eine CO₂-Steuer erhoben wird"],
                explanation: "Ab dem Erdüberlastungstag lebt die Menschheit rechnerisch von den Ressourcenreserven künftiger Jahre."),
        .choice(id: "nac-c05", topic: .nachhaltigkeit,
                prompt: "Was misst der ökologische Fußabdruck?",
                options: ["Wie viel Fläche und Ressourcen der Lebensstil eines Menschen oder Landes beansprucht",
                          "Wie viel Geld ein Unternehmen für Umweltschutz ausgibt",
                          "Wie viele Bäume ein Unternehmen pflanzt",
                          "Wie hoch die Stromrechnung eines Haushalts ist",
                          "Wie viele Recyclinghöfe es in einer Region gibt"],
                explanation: "Der ökologische Fußabdruck zeigt, wie viel Fläche und wie viele Ressourcen für den Lebensstil eines Menschen oder Landes nötig wären."),
        .choice(id: "nac-c06", topic: .nachhaltigkeit,
                prompt: "Welche Stufe steht in der Abfallhierarchie des Kreislaufwirtschaftsgesetzes an erster Stelle?",
                options: ["Vermeidung von Abfall",
                          "Recycling",
                          "Beseitigung",
                          "Energetische Verwertung",
                          "Vorbereitung zur Wiederverwendung"],
                explanation: "Die Abfallhierarchie stellt die Vermeidung von Abfall an die erste Stelle, vor Wiederverwendung, Recycling, sonstiger Verwertung und Beseitigung."),
        .choice(id: "nac-c07", topic: .nachhaltigkeit,
                prompt: "Wie muss ausrangierter Elektroschrott nach dem Elektrogesetz (ElektroG) entsorgt werden?",
                options: ["Getrennt vom Hausmüll, z. B. über Wertstoffhöfe oder die Rücknahme im Handel",
                          "Über den normalen Hausmüll",
                          "Über den Biomüll",
                          "Nur durch professionelle Entsorgungsunternehmen gegen Gebühr",
                          "Ausschließlich durch Rückgabe an den Hersteller per Post"],
                explanation: "Elektroschrott darf nicht in den Hausmüll, sondern muss getrennt entsorgt werden, etwa über Wertstoffhöfe oder die Rücknahme im Handel."),
        .choice(id: "nac-c08", topic: .nachhaltigkeit,
                prompt: "Was bedeutet Green IT im betrieblichen Umfeld?",
                options: ["Der möglichst energie- und ressourcenschonende Einsatz von IT, z. B. durch Virtualisierung und lange Nutzungsdauer",
                          "Die ausschließliche Nutzung von IT-Geräten in grüner Farbe",
                          "Der vollständige Verzicht auf IT im Unternehmen",
                          "Ein Zertifikat für besonders schnelle Server",
                          "Die Nutzung von IT nur für Umweltbehörden"],
                explanation: "Green IT umfasst Maßnahmen wie effiziente Server, Virtualisierung, lange Nutzungsdauer und Energiesparmodi, um den Ressourcenverbrauch der IT zu senken."),
        .choice(id: "nac-c09", topic: .nachhaltigkeit,
                prompt: "Welche Maßnahme zählt zu Green IT?",
                options: ["Server-Virtualisierung, um mit weniger Hardware auszukommen",
                          "Der Kauf möglichst vieler neuer Geräte pro Jahr",
                          "Das dauerhafte Betreiben aller Geräte im Standby statt im Energiesparmodus",
                          "Der Verzicht auf jede Form von IT-Wartung",
                          "Die Nutzung von IT ausschließlich in Rechenzentren ohne Kühlung"],
                explanation: "Virtualisierung reduziert die Anzahl benötigter physischer Server und senkt so Energie- und Ressourcenverbrauch."),
        .choice(id: "nac-c10", topic: .nachhaltigkeit,
                prompt: "Ein fiktives Unternehmen ersetzt Dienstreisen häufig durch Videokonferenzen. Welchem Nachhaltigkeitsziel dient das vor allem?",
                options: ["Der Reduktion von CO₂-Emissionen und Ressourcenverbrauch",
                          "Der Erhöhung der Mitarbeiterzahl",
                          "Der Steigerung des Umsatzes im laufenden Quartal",
                          "Der Vermeidung von Steuerzahlungen",
                          "Der Einhaltung von Exportvorschriften"],
                explanation: "Weniger Dienstreisen sparen CO₂-Emissionen, Energie und Kosten – eine typische betriebliche Nachhaltigkeitsmaßnahme."),
        .choice(id: "nac-c11", topic: .nachhaltigkeit,
                prompt: "Was beschreibt der Begriff Upcycling?",
                options: ["Alte oder gebrauchte Materialien werden zu einem höherwertigen Produkt weiterverarbeitet",
                          "Ein Produkt wird bei der Wiederverwertung minderwertiger als das Ausgangsmaterial",
                          "Elektrogeräte werden ohne Aufbereitung weggeworfen",
                          "Neue Rohstoffe werden ausschließlich importiert",
                          "Ein Produkt wird ohne Veränderung erneut verkauft"],
                explanation: "Beim Upcycling entsteht aus einem gebrauchten Material ein höherwertiges neues Produkt, im Gegensatz zum Downcycling, bei dem die Qualität sinkt."),
        .choice(id: "nac-c12", topic: .nachhaltigkeit,
                prompt: "Was versteht man unter sozialer Nachhaltigkeit im Betrieb?",
                options: ["Faire Löhne, Arbeitsschutz und Maßnahmen wie eine bessere Vereinbarkeit von Familie und Beruf",
                          "Ausschließlich die Reduktion des CO₂-Ausstoßes",
                          "Nur die Einhaltung von Umweltauflagen",
                          "Ausschließlich die Steigerung des Aktienkurses",
                          "Der Verzicht auf jede Automatisierung"],
                explanation: "Soziale Nachhaltigkeit umfasst u. a. faire Löhne, Arbeitsschutz, Diversität und Vereinbarkeit von Familie und Beruf, z. B. durch flexible Arbeitszeiten oder eine Betriebskita."),
        .choice(id: "nac-c13", topic: .nachhaltigkeit,
                prompt: "Welche Maßnahme fördert die Vereinbarkeit von Familie und Beruf besonders direkt?",
                options: ["Flexible Arbeitszeiten und eine betriebliche Kinderbetreuung",
                          "Eine strikte Anwesenheitspflicht von 9 bis 18 Uhr",
                          "Der Verzicht auf jede Form von Teilzeit",
                          "Die Streichung von Elternzeit",
                          "Ausschließlich Überstunden am Wochenende"],
                explanation: "Flexible Arbeitszeitmodelle und Angebote wie eine Betriebskita erleichtern es Beschäftigten, Familie und Beruf zu vereinbaren."),
        .choice(id: "nac-c14", topic: .nachhaltigkeit,
                prompt: "Was ist das Ziel des Pariser Klimaabkommens?",
                options: ["Die Erderwärmung deutlich unter 2 °C, möglichst auf 1,5 °C, gegenüber dem vorindustriellen Niveau zu begrenzen",
                          "Den weltweiten CO₂-Ausstoß bis 2030 vollständig zu verbieten",
                          "Alle Staaten zu einer einheitlichen Klimasteuer zu verpflichten",
                          "Fossile Energieträger sofort weltweit zu verbieten",
                          "Nur europäische Staaten zur Emissionsminderung zu verpflichten"],
                explanation: "Das Pariser Abkommen verfolgt das Ziel, die Erderwärmung deutlich unter 2 °C, möglichst auf 1,5 °C, zu begrenzen."),
        .choice(id: "nac-c15", topic: .nachhaltigkeit,
                prompt: "Welches Instrument soll den Ausstoß von Treibhausgasen wirtschaftlich verteuern?",
                options: ["Die CO₂-Bepreisung, z. B. über den Emissionshandel",
                          "Die Mehrwertsteuer auf Lebensmittel",
                          "Der Leitzins der EZB",
                          "Die Kfz-Versicherungspflicht",
                          "Der Mindestlohn"],
                explanation: "Über CO₂-Bepreisung bzw. Emissionshandel soll der Ausstoß von Treibhausgasen wirtschaftlich unattraktiver gemacht werden."),
        .choice(id: "nac-c16", topic: .nachhaltigkeit,
                prompt: "Welche Energieform zählt NICHT zu den erneuerbaren Energien?",
                options: ["Erdgas", "Windenergie", "Sonnenenergie", "Wasserkraft", "Biomasse"],
                explanation: "Erdgas ist ein fossiler, endlicher Energieträger; Wind, Sonne, Wasser, Biomasse und Geothermie zählen zu den erneuerbaren Energien."),
        .choice(id: "nac-c17", topic: .nachhaltigkeit,
                prompt: "Welche internationale Norm regelt ein betriebliches Umweltmanagementsystem?",
                options: ["ISO 14001", "ISO 9001", "ISO 27001", "ISO 50001", "ISO 26000"],
                explanation: "ISO 14001 legt Anforderungen an ein Umweltmanagementsystem fest; ISO 50001 betrifft speziell das Energiemanagement."),
        .choice(id: "nac-c18", topic: .nachhaltigkeit,
                prompt: "Welche internationale Norm betrifft speziell das betriebliche Energiemanagement?",
                options: ["ISO 50001", "ISO 14001", "ISO 9001", "ISO 27001", "ISO 45001"],
                explanation: "ISO 50001 regelt das Energiemanagement, während ISO 14001 das allgemeine Umweltmanagement betrifft."),
        .choice(id: "nac-c19", topic: .nachhaltigkeit,
                prompt: "Was unterscheidet Recycling von Downcycling?",
                options: ["Beim Recycling bleibt möglichst die ursprüngliche Qualität erhalten, beim Downcycling entsteht ein minderwertigeres Produkt",
                          "Downcycling ist ein anderes Wort für Vermeidung",
                          "Recycling findet nur bei Elektrogeräten statt",
                          "Downcycling bedeutet, dass ein Produkt gar nicht wiederverwertet wird",
                          "Recycling und Downcycling sind gesetzlich identisch geregelt"],
                explanation: "Recycling erhält im Idealfall die Materialqualität, während beim Downcycling die Qualität mit jedem Kreislauf sinkt."),

        // Statements
        .statement(id: "nac-s01", topic: .nachhaltigkeit,
                   text: "Nachhaltigkeit wird häufig in eine ökologische, ökonomische und soziale Dimension unterteilt.",
                   isTrue: true,
                   explanation: "Das ist das Drei-Säulen-Modell der Nachhaltigkeit."),
        .statement(id: "nac-s02", topic: .nachhaltigkeit,
                   text: "Der Begriff Nachhaltigkeit stammt ursprünglich aus der Automobilindustrie.",
                   isTrue: false,
                   explanation: "Der Begriff stammt aus der Forstwirtschaft, nicht aus der Automobilindustrie."),
        .statement(id: "nac-s03", topic: .nachhaltigkeit,
                   text: "Die Agenda 2030 der Vereinten Nationen umfasst 17 Ziele für nachhaltige Entwicklung.",
                   isTrue: true,
                   explanation: "Diese 17 Ziele werden auch Sustainable Development Goals (SDGs) genannt."),
        .statement(id: "nac-s04", topic: .nachhaltigkeit,
                   text: "Der Erdüberlastungstag markiert den Tag, ab dem die Menschheit von den Ressourcenreserven künftiger Jahre lebt.",
                   isTrue: true,
                   explanation: "Ab diesem Tag übersteigt der Ressourcenverbrauch das, was die Erde im Jahr regenerieren kann."),
        .statement(id: "nac-s05", topic: .nachhaltigkeit,
                   text: "In der Abfallhierarchie steht die Beseitigung von Abfall an erster Stelle.",
                   isTrue: false,
                   explanation: "An erster Stelle steht die Vermeidung von Abfall, die Beseitigung ist die letzte Stufe."),
        .statement(id: "nac-s06", topic: .nachhaltigkeit,
                   text: "Elektroschrott darf laut ElektroG über den normalen Hausmüll entsorgt werden.",
                   isTrue: false,
                   explanation: "Elektroschrott muss getrennt entsorgt werden, z. B. über Wertstoffhöfe oder den Handel."),
        .statement(id: "nac-s07", topic: .nachhaltigkeit,
                   text: "Green IT zielt u. a. auf einen energieeffizienten Einsatz von Servern und Rechenzentren ab.",
                   isTrue: true,
                   explanation: "Das ist ein zentrales Anliegen von Green IT."),
        .statement(id: "nac-s08", topic: .nachhaltigkeit,
                   text: "Virtualisierung von Servern kann den Energieverbrauch eines Rechenzentrums senken.",
                   isTrue: true,
                   explanation: "Durch Virtualisierung werden weniger physische Server benötigt, was Energie spart."),
        .statement(id: "nac-s09", topic: .nachhaltigkeit,
                   text: "Beim Downcycling entsteht aus einem Altmaterial ein höherwertigeres Produkt als vorher.",
                   isTrue: false,
                   explanation: "Beim Downcycling sinkt die Qualität, ein höherwertiges Produkt entsteht beim Upcycling."),
        .statement(id: "nac-s10", topic: .nachhaltigkeit,
                   text: "Soziale Nachhaltigkeit umfasst unter anderem faire Löhne und Arbeitsschutz.",
                   isTrue: true,
                   explanation: "Faire Löhne und Arbeitsschutz gehören zur sozialen Dimension der Nachhaltigkeit."),
        .statement(id: "nac-s11", topic: .nachhaltigkeit,
                   text: "Flexible Arbeitszeiten können die Vereinbarkeit von Familie und Beruf erleichtern.",
                   isTrue: true,
                   explanation: "Flexible Modelle wie Gleitzeit oder Homeoffice erleichtern die Vereinbarkeit."),
        .statement(id: "nac-s12", topic: .nachhaltigkeit,
                   text: "Das Pariser Klimaabkommen strebt an, die Erderwärmung möglichst auf 1,5 °C zu begrenzen.",
                   isTrue: true,
                   explanation: "Das ist das ambitionierte Ziel des Pariser Abkommens gegenüber dem vorindustriellen Niveau."),
        .statement(id: "nac-s13", topic: .nachhaltigkeit,
                   text: "Erdgas zählt zu den erneuerbaren Energien.",
                   isTrue: false,
                   explanation: "Erdgas ist ein fossiler, endlicher Energieträger und zählt nicht zu den erneuerbaren Energien."),
        .statement(id: "nac-s14", topic: .nachhaltigkeit,
                   text: "ISO 14001 regelt speziell das betriebliche Energiemanagement.",
                   isTrue: false,
                   explanation: "ISO 14001 regelt das Umweltmanagement; das Energiemanagement ist Gegenstand der ISO 50001."),

        // Multiple
        .multiple(id: "nac-m01", topic: .nachhaltigkeit,
                  prompt: "Wähle alle Stufen aus, die zur Abfallhierarchie des Kreislaufwirtschaftsgesetzes zählen.",
                  correct: ["Vermeidung",
                            "Vorbereitung zur Wiederverwendung",
                            "Recycling",
                            "Sonstige (energetische) Verwertung",
                            "Beseitigung"],
                  wrong: ["Export ins Ausland ohne Kontrolle",
                          "Unbegrenzte Lagerung auf Deponien ohne Verwertung",
                          "Verbrennung als gesetzlich vorgeschriebene erste Stufe"],
                  explanation: "Die Abfallhierarchie umfasst fünf Stufen: Vermeidung, Vorbereitung zur Wiederverwendung, Recycling, sonstige Verwertung und Beseitigung."),
        .multiple(id: "nac-m02", topic: .nachhaltigkeit,
                  prompt: "Wähle alle Maßnahmen aus, die zu Green IT im Unternehmen zählen.",
                  correct: ["Server-Virtualisierung",
                            "Lange Nutzungsdauer und Refurbished-Geräte",
                            "Energiesparmodi statt Dauerbetrieb im Standby",
                            "Reduzierter Druckerausstoß durch digitale Prozesse"],
                  wrong: ["Jährlicher Kauf komplett neuer Hardware",
                          "Dauerhafter Betrieb aller Bildschirme im Standby",
                          "Verzicht auf jede Form von Energiemanagement"],
                  explanation: "Green IT umfasst u. a. Virtualisierung, lange Nutzungsdauer, Energiesparmodi und die Reduktion von Papierverbrauch."),
        .multiple(id: "nac-m03", topic: .nachhaltigkeit,
                  prompt: "Wähle alle Energieformen aus, die zu den erneuerbaren Energien zählen.",
                  correct: ["Windenergie", "Sonnenenergie", "Wasserkraft", "Biomasse", "Geothermie"],
                  wrong: ["Erdgas", "Steinkohle", "Erdöl"],
                  explanation: "Wind-, Sonnen-, Wasserkraft, Biomasse und Geothermie sind erneuerbare Energien; Erdgas, Kohle und Erdöl sind fossile Energieträger."),
        .multiple(id: "nac-m04", topic: .nachhaltigkeit,
                  prompt: "Wähle alle Maßnahmen aus, die die soziale Nachhaltigkeit im Betrieb fördern.",
                  correct: ["Faire Löhne",
                            "Betriebliche Kinderbetreuung",
                            "Maßnahmen zum Arbeitsschutz",
                            "Weiterbildungsangebote für Beschäftigte"],
                  wrong: ["Verzicht auf jede Mitarbeiterbeteiligung",
                          "Ausschließlich befristete Verträge ohne Perspektive",
                          "Systematische Überstunden ohne Ausgleich"],
                  explanation: "Faire Löhne, Kinderbetreuung, Arbeitsschutz und Weiterbildung stärken die soziale Dimension der Nachhaltigkeit im Betrieb."),

        // Match
        .match(id: "nac-p01", topic: .nachhaltigkeit,
               prompt: "Ordne die Maßnahme der passenden Nachhaltigkeitsdimension zu.",
               pairs: [("Einführung von Ökostrom im Rechenzentrum", "Ökologische Dimension"),
                       ("Faire Löhne und Arbeitsschutz für Beschäftigte", "Soziale Dimension"),
                       ("Langfristige Sicherung der Wirtschaftlichkeit des Unternehmens", "Ökonomische Dimension"),
                       ("Betriebliche Kinderbetreuung zur besseren Vereinbarkeit von Familie und Beruf", "Soziale Dimension")],
               extra: ["Rechtliche Dimension"],
               explanation: "Nachhaltige Maßnahmen lassen sich der ökologischen, sozialen oder ökonomischen Dimension zuordnen; Labels können sich wiederholen."),
        .match(id: "nac-p02", topic: .nachhaltigkeit,
               prompt: "Ordne den Begriff der passenden Beschreibung in der Kreislaufwirtschaft zu.",
               pairs: [("Aus einem alten Material entsteht ein höherwertiges neues Produkt", "Upcycling"),
                       ("Ein Material wird bei der Wiederverwertung minderwertiger", "Downcycling"),
                       ("Ein Produkt wird ohne Veränderung erneut genutzt", "Wiederverwendung"),
                       ("Material wird aufbereitet und erneut zu einem gleichwertigen Produkt verarbeitet", "Recycling")],
               extra: [],
               explanation: "Die Begriffe beschreiben unterschiedliche Formen der Wiederverwertung von Materialien in der Kreislaufwirtschaft."),
        .match(id: "nac-p03", topic: .nachhaltigkeit,
               prompt: "Ordne die Norm bzw. das Abkommen dem passenden Bereich zu.",
               pairs: [("ISO 14001", "Umweltmanagement"),
                       ("ISO 50001", "Energiemanagement"),
                       ("Pariser Klimaabkommen", "Begrenzung der Erderwärmung"),
                       ("Elektrogesetz (ElektroG)", "Rücknahme von Elektroschrott")],
               extra: ["ISO 9001"],
               explanation: "Normen und Gesetze im Nachhaltigkeitsbereich regeln jeweils klar abgegrenzte Themenfelder."),
        .match(id: "nac-p04", topic: .nachhaltigkeit,
               prompt: "Ordne der betrieblichen Situation die passende Nachhaltigkeitsmaßnahme zu.",
               pairs: [("Ein altes Firmenhandy wird ausgetauscht", "Rückgabe beim Handel oder Wertstoffhof"),
                       ("Ein Server-Rack wird nur zu 20 % ausgelastet betrieben", "Virtualisierung zur besseren Auslastung"),
                       ("Mitarbeitende pendeln täglich lange Strecken ins Büro", "Homeoffice oder mobile Arbeit ermöglichen"),
                       ("Ein Meeting mit Kolleginnen in einer anderen Stadt steht an", "Videokonferenz statt Dienstreise")],
               extra: ["Verbrennung ohne Verwertung"],
               explanation: "Zu typischen betrieblichen Situationen passen jeweils konkrete Maßnahmen der Nachhaltigkeit, insbesondere im Bereich Green IT."),

        // Order
        .order(id: "nac-o01", topic: .nachhaltigkeit,
               prompt: "Bringe die Abfallhierarchie des Kreislaufwirtschaftsgesetzes in die richtige Reihenfolge.",
               steps: ["Vermeidung von Abfall",
                       "Vorbereitung zur Wiederverwendung",
                       "Recycling",
                       "Sonstige (energetische) Verwertung",
                       "Beseitigung"],
               explanation: "Die Abfallhierarchie gibt eine klare Rangfolge vor: Vermeidung hat immer Vorrang vor der Beseitigung."),
        .order(id: "nac-o02", topic: .nachhaltigkeit,
               prompt: "Bringe den Weg eines fiktiven Elektrogeräts vom Kauf bis zur Wiederverwertung in die richtige Reihenfolge.",
               steps: ["Ein neues Gerät wird gekauft und über Jahre genutzt",
                       "Das Gerät funktioniert nicht mehr richtig und wird ausgemustert",
                       "Es wird bei einem Wertstoffhof oder im Handel zurückgegeben",
                       "Wiederverwendbare Bauteile werden aufbereitet und weiterverwendet",
                       "Nicht verwertbare Reste werden fachgerecht entsorgt"],
               explanation: "Der Weg eines Elektrogeräts folgt idealerweise der Abfallhierarchie: erst Wiederverwendung möglicher Teile, dann fachgerechte Entsorgung der Reste."),

        // Gap
        .gap(id: "nac-g01", topic: .nachhaltigkeit, title: "Grenzen der Erde",
             sentences: [("Der Tag im Jahr, an dem die Menschheit rechnerisch alle nachwachsenden Ressourcen des Jahres verbraucht hat, heißt ___.", "Erdüberlastungstag"),
                         ("Wie viel Fläche und Ressourcen der Lebensstil eines Menschen beansprucht, zeigt der ökologische ___.", "Fußabdruck"),
                         ("Werden Altmaterialien zu einem gleichwertigen neuen Produkt verarbeitet, spricht man von ___.", "Recycling"),
                         ("Ausrangierte Geräte wie Laptops oder Smartphones zählen zum sogenannten ___.", "Elektroschrott")],
             extra: ["Upcycling", "Downcycling"],
             explanation: "Die Begriffe beschreiben, wie der Ressourcenverbrauch der Menschheit gemessen wird und wie Materialien nach der Nutzung wieder in den Kreislauf zurückgeführt werden können."),
        .gap(id: "nac-g02", topic: .nachhaltigkeit, title: "Nachhaltigkeit im Betrieb",
             sentences: [("Ein möglichst energie- und ressourcenschonender IT-Einsatz wird als ___ bezeichnet.", "Green IT"),
                         ("Werden mehrere physische Server zu wenigen leistungsfähigen Systemen zusammengefasst, spricht man von ___.", "Virtualisierung"),
                         ("Statt einer Dienstreise nutzt ein Team eine ___.", "Videokonferenz"),
                         ("Flexible Arbeitszeiten erleichtern die Vereinbarkeit von ___ und Beruf.", "Familie")],
             extra: ["Kurzarbeit", "Homeoffice"],
             explanation: "Diese Begriffe stehen für typische betriebliche Maßnahmen der ökologischen und sozialen Nachhaltigkeit."),
        .gap(id: "nac-g03", topic: .nachhaltigkeit, title: "Klimaschutz und Energie",
             sentences: [("Das Pariser Klimaabkommen will die Erderwärmung möglichst auf ___ Grad begrenzen.", "1,5"),
                         ("Energie aus Sonne, Wind, Wasser oder Biomasse wird als ___ bezeichnet.", "erneuerbar"),
                         ("Der Ausstoß von Treibhausgasen soll u. a. durch den ___ verteuert werden.", "Emissionshandel")],
             extra: ["Kohleausstieg", "Mindestlohn"],
             explanation: "Die Begriffe stehen für zentrale Instrumente und Ziele des Klimaschutzes."),

        // Facts
        .fact(id: "nac-f01", topic: .nachhaltigkeit, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Dimensionen umfasst das Drei-Säulen-Modell der Nachhaltigkeit?",
              answer: "3",
              explanation: "Ökologische, ökonomische und soziale Dimension bilden die drei Säulen."),
        .fact(id: "nac-f02", topic: .nachhaltigkeit, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Ziele umfasst die Agenda 2030 der Vereinten Nationen?",
              answer: "17",
              explanation: "Die Agenda 2030 nennt 17 Sustainable Development Goals (SDGs)."),
        .fact(id: "nac-f03", topic: .nachhaltigkeit, group: ExamCatalog.Group.anzahl,
              question: "Wie viele Stufen umfasst die Abfallhierarchie des Kreislaufwirtschaftsgesetzes?",
              answer: "5",
              explanation: "Vermeidung, Vorbereitung zur Wiederverwendung, Recycling, sonstige Verwertung und Beseitigung ergeben fünf Stufen."),
        .fact(id: "nac-f04", topic: .nachhaltigkeit, group: ExamCatalog.Group.stelle,
              question: "Welches Gesetz regelt in Deutschland die Rückgabe von Elektroschrott?",
              answer: "Elektrogesetz (ElektroG)",
              explanation: "Das ElektroG verpflichtet u. a. zur getrennten Rückgabe von Altgeräten über Wertstoffhöfe oder den Handel."),
        .fact(id: "nac-f05", topic: .nachhaltigkeit, group: ExamCatalog.Group.stelle,
              question: "Welche internationale Norm regelt betriebliches Umweltmanagement?",
              answer: "ISO 14001",
              explanation: "ISO 14001 legt die Anforderungen an ein Umweltmanagementsystem in Unternehmen fest."),
        .fact(id: "nac-f06", topic: .nachhaltigkeit, group: ExamCatalog.Group.stelle,
              question: "Welche internationale Norm regelt betriebliches Energiemanagement?",
              answer: "ISO 50001",
              explanation: "ISO 50001 legt die Anforderungen an ein Energiemanagementsystem in Unternehmen fest."),
    ]
}
